### ISSUE TITLE
error in full-nat mode when configure port for both tcp and udp

### ISSUE THREAD

**Issue by linxiaocong** [iqiyi/dpvs#103]
test script:

```
VIP=
LIP=
RS=

./dpip addr add ${VIP}/25 dev dpdk0

./ipvsadm -A -t ${VIP}:80 -s rr
./ipvsadm -a -t ${VIP}:80 -r ${RS} -b
./ipvsadm -P -z ${LIP} -t ${VIP}:80 -F dpdk0

./ipvsadm -A -u ${VIP}:80 -s rr
./ipvsadm -a -u ${VIP}:80 -r ${RS} -b
./ipvsadm -P -z ${LIP} -u ${VIP}:80 -F dpdk0  # this line will print an error
```

the error msg is: [sockopt_msg_recv] errcode set in socket msg#400 header: already exist(-3)

**Comment by beacer** [comment]
Pls ignore this error, because LIP will be added into two modules, first is ipvs/service, second is IP address management. IP address management module has no idea of "vip:port", so the LIP will be added to an interface (dpdk0) twice, which is harmless and can be ignore.
