### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by treemanzhou** [iqiyi/dpvs#108]
你好 我是按照安装步骤一步一步安装的，但是到最后一步出现了问题提示

![image](https://user-images.githubusercontent.com/20250698/35269557-50310e74-0067-11e8-9a19-2fae73ca1e8c.png)
这个sh是什么原因啊， 我的环境和测试环境相同

**Comment by ywc689** [comment]
看代码是pthread_setaffinity_np这个线程函数失败了，你测试是什么环境？操作系统、CPU数量是什么？

**Comment by treemanzhou** [comment]
CentOS Linux release 7.2.1511 (Core) 
Linux l20-2-10 4.9.0 #1 SMP Tue Jan 23 16:05:40 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
40核CPU

**Comment by beacer** [comment]
这个函数是一个pthread库函数，而且在它之前都是些库函数和系统调用．可能和环境有关，我看你的kernel比较新．
