### ISSUE TITLE
黑名单添加语义与生效情况不匹配

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#110]
添加里需要指定service而不是vip
\# ./ipvsadm -U -t 192.168.10.5:80 -k 192.168.10.3
\# ./ipvsadm -B
VIP                  DENY_IP
192.168.10.5         192.168.10.3
真正生效是按VIP生效的，验证发现该VIP下的UDP服务也无法访问；
不过不是什么大问题。线上用的时候明确预期就行。

**Comment by mscbg** [comment]
是的，确实是这样的。目前的黑名单是按照源IP和目的IP做的哈希。不区分端口和协议。

**Comment by icymoon** [comment]
是因为添加的接口都带Service而不是VIP，这样实现起来省事？
这个不是什么问题。。完全可以接受。。。

**Comment by beacer** [comment]
加上端口可以更精确一些，也不容易引起误解．　不过这个fix优先级确实不高．
