### ISSUE TITLE
start keepalived with -f failed, and -n seems not right.

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#112]
keepalived only load /etc/keepalived/keepalived.conf now, -f doesn't work.
Start it with -n, keepalived still forks child processes.

**Comment by mscbg** [comment]
How did you try this. I just try this and it worked.
![image](https://user-images.githubusercontent.com/20103281/35367751-ff7f18a4-01ba-11e8-981a-abf534206b42.png)

**Comment by icymoon** [comment]
I tried it like this:
keepalived -f ./keepalived.conf

**Comment by beacer** [comment]
Pls try `-f` with abstract path, and `-n` means no daemon.

**Comment by icymoon** [comment]
OK, abstract path works well, thank you. :-)
