### ISSUE TITLE
keepalived crashed in reloading, check_data.c. Thank you very much.

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#120]
Binary keepalived is not striped.
Run reloading with two conf file, only LIP list is different, one is more than another.
 
\# gdb ./keepalived ./core.111689
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/xxxxx/dpvs/bin/keepalived...done.
[New LWP 111689]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./keepalived -d -f /etc/keepalived/keepalived.conf -S 6'.
Program terminated with signal 11, Segmentation fault.
#0  free_ssl () at check_data.c:45
45		ssl_data_t *ssl = check_data->ssl;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libselinux-2.5-11.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  free_ssl () at check_data.c:45
#1  0x000000000040563f in stop_check () at check_daemon.c:57
#2  0x0000000000405785 in start_check () at check_daemon.c:94
#3  0x0000000000405889 in reload_check_thread (thread=<optimized out>) at check_daemon.c:212
#4  0x000000000042136d in thread_call (thread=0x7ffd6f8ee4c0) at scheduler.c:759
#5  launch_scheduler () at scheduler.c:782
#6  0x00000000004058cd in start_check_child () at check_daemon.c:311
#7  0x0000000000403127 in start_keepalived () at main.c:80
#8  main (argc=<optimized out>, argv=<optimized out>) at main.c:303
(gdb)

**Comment by mscbg** [comment]
Can you attach the whole configuration file?

**Comment by icymoon** [comment]
I will try to reproduce it with simpler condition.

**Comment by beacer** [comment]
Fixed by several commits related to keepalived.
