### ISSUE TITLE
Can kpvs run  in the vm based on kvm ?

### ISSUE THREAD

**Issue by keloyang** [iqiyi/dpvs#121]
As we know, dpdk can run in the vm, can dpvs run  in the vm based on kvm ?
>Other environment should also OK if DPDK works, pls check dpdk.org for more info.
 Pls check this link for NICs supported by DPDK: http://dpdk.org/doc/nics.
 Note flow-director (fdir) is needed for Full-NAT and SNAT mode

Is it(fdir) optional or must to run dpvs , and can we run dpvs without  Full-NAT and SNAT mode ?

ping @beacer @ywc689 @icymoon @kldeng

**Comment by beacer** [comment]
We have no experience to run dpvs on VM, if someone has tried that, pls provide some info.
Fdir is must for FullNAT and SNAT mode, and these two are most popular mode used, although DPVS support DR mode.
