### ISSUE TITLE
How to use  dpvs as a SNAT gateway

### ISSUE THREAD

**Issue by davidmama** [iqiyi/dpvs#127]
Thanks Authors,  Fullnat works well, Now i want to try snat as a gateway.
I checked the doc, found little doc introducing this mode. could author/someone else give a example how to using it?

thanks
-David

**Comment by beacer** [comment]
The `SNAT Mode (two-arm)` section of `doc/tutorial.md` including all essential configurations for `SNAT`, if you met any issue to try this example, pls point out where fails. And `scripts/config_snat_sample.sh` is another example.
If any further question, pls let us know.

**Comment by davidmama** [comment]
thanks your quick reply, will try it!

**Comment by beacer** [comment]
Any update ? @davidmama

**Comment by davidmama** [comment]
thanks Bacer,  it works now!
