### ISSUE TITLE
help!  how to solve this  trouble ？

### ISSUE THREAD

**Issue by guzhangyang** [iqiyi/dpvs#129]
.
              .
              .
              .
NETIF: worker cpu7:dpdk0 rx_queue_id += 6
NETIF: worker cpu7:dpdk0 tx_queue_id += 6
NETIF: worker cpu8:dpdk0 rx_queue_id += 7
NETIF: worker cpu8:dpdk0 tx_queue_id += 7
dpvs: /root/dpvs/src/netif.c:3657: netif_loop: Assertion `LCORE_ID_ANY != cid && cid < NETIF_MAX_LCORES' failed.
dpvs: /root/dpvs/src/netif.c:3657: netif_loop: Assertion `LCORE_ID_ANY != cid && cid < NETIF_MAX_LCORES' failed.
Aborted (core dumped)

hi, when i was ran the command ' ./bin/dpvs '  something of trouble persented  above。pls  help me ？

**Comment by mscbg** [comment]
How many cores have you configured？ The error/asset fail shows you have configured cores too many.

**Comment by beacer** [comment]
Each cpu (lcore) should handle one TX and RX queue of a NIC. For example, your NIC have 16 TX/RX queues. The config could be:

cpu | role |  TX-queue |  RX-queue 
------|-------|---------------|---------------
cpu 0  | master |  N/A    |  N/A  |
cpu 1 |  worker |  txq-0  | rxq-0 |
cpu 2 |  worker |  txq-1  | rxq-1 |
... | ... | ... | ...
cpu 16 |  worker |  txq-15  | rxq-15 |

**Comment by guzhangyang** [comment]
first  thanks all.
i followed guide to  build  this  environment  and  got  wrong  when i  execute  the last command 

[root@server-p9 bin]# ./dpvs 
dpvs version: 1.0.0 build on 2018.02.09.23:58:12
current thread affinity is set to FFFFFFFFFFFFFFFF
EAL: Detected 88 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:02:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:04:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
……
refer two guys answer above  ，how  to  set   the  correct   number  of  core ？
 /etc/dpvs.conf    that  config  file  is  default.  8 queue .

**Comment by beacer** [comment]
I saw you have 4 NICs detected by DPDK (EAL), how many NICs are configured in `/etc/dpvs.conf`?
And the core number should be same as each NIC's TX/RX queue number.
