### ISSUE TITLE
snat运行8h左右，tcp协议无法转发

### ISSUE THREAD

**Issue by zeably** [iqiyi/dpvs#138]
snat运行8h左右，tcp协议无法转发，icmp协议正常，故障可以复现

**Comment by beacer** [comment]
初步查看发现，使用`dpip neigh del ...`删除ＷＡＮ接口的ARP后就能恢复．目前怀疑和neigh模块相关，可能是某些cpu的ＡＲＰ表项出现异常．　使用调试版本尝试复现，进一步调试．

**Comment by icymoon** [comment]
icmp也需要arp，没看明白并且没能复现出来 ：（

**Comment by beacer** [comment]
这个arp的问题可能是每个cpu不一样的，每个cpu有自己独立的arp表，如果出问题，只会影响它自己．表现就是curl有时候通有时候不通，因为curl的源端口不一样，每次在不同的cpu．ＩＣＭＰ之所以一直正常是因为，ＲＳＳ只针对ＴＣＰ，ＩＣＭＰ总是在第一个worker．

**Comment by icymoon** [comment]
谢谢，Got！

**Comment by mscbg** [comment]
#140
