### ISSUE TITLE
DPVS server is not stable

### ISSUE THREAD

**Issue by tiepnv-viosoft** [iqiyi/dpvs#139]
Hello,
I'm planning to setup Simple Full-NAT (two-arm). However, I rarely have access to real servers from the client side (using curl).
My topo as belows:
- Client:	Ubuntu 16.04.1 LTS:	NIC i40e: 10.0.0.48/16:		ping 10.0.0.100 successfully
- DPVS:		Ubuntu 16.04.3 LTS:	NIC1 i40e: 10.0.0.100/32
                                                                NIC2 i40e: 192.168.100.200/32
- RS1 (nginx):	Ubuntu 16.04.3 LTS:	NIC i40e: 192.168.100.2/24:	ping 192.168.100.200 and 10.0.0.100 successfully
- RS2 (nginx):	Ubuntu 16.04.3 LTS:	NIC i40e: 192.168.100.3/24:	ping 192.168.100.200 and 10.0.0.100 successfully

This is my configuration:
```
./dpip addr add 10.0.0.100/32 dev dpdk1
./dpip route add 10.0.0.0/16 dev dpdk1
./dpip route add 192.168.100.0/24 dev dpdk0
./ipvsadm -A -t 10.0.0.100:80 -s rr
./ipvsadm -a -t 10.0.0.100:80 -r 192.168.100.2 -b
./ipvsadm -a -t 10.0.0.100:80 -r 192.168.100.3 -b
./ipvsadm --add-laddr -z 192.168.100.200 -t 10.0.0.100:80 -F dpdk0
```

Here is the information on my DPVS:
```
# ./dpip link show
1: dpdk0: socket 0 mtu 1500 rx-queue 8 tx-queue 8
    UP 10000 Mbps full-duplex fixed-nego 
    addr 3C:FD:FE:A0:CE:20 OF_RX_IP_CSUM OF_TX_IP_CSUM OF_TX_TCP_CSUM OF_TX_UDP_CSUM 
2: dpdk1: socket 0 mtu 1500 rx-queue 8 tx-queue 8
    UP 10000 Mbps full-duplex fixed-nego 
    addr 3C:FD:FE:A0:D3:50 OF_RX_IP_CSUM OF_TX_IP_CSUM OF_TX_TCP_CSUM OF_TX_UDP_CSUM
```

```
# ./dpip addr show
inet 10.0.0.100/32 scope global dpdk1
     valid_lft forever preferred_lft forever
inet 192.168.100.200/32 scope global dpdk0
     valid_lft forever preferred_lft forever sa_used 0 sa_free 1032176 sa_miss 0
```

```
# ./dpip route show
inet 10.0.0.100/32 via 0.0.0.0 src 0.0.0.0 dev dpdk1 mtu 1500 tos 0 scope host metric 0 proto auto 
inet 192.168.100.200/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope host metric 0 proto auto 
inet 192.168.100.0/24 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope link metric 0 proto auto 
inet 10.0.0.0/16 via 0.0.0.0 src 0.0.0.0 dev dpdk1 mtu 1500 tos 0 scope link metric 0 proto auto
```

```
# ./ipvsadm -Ln --stats
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
TCP  10.0.0.100:80                       2        5        0      300        0
  -> 192.168.100.2:80                    1        2        0      120        0
  -> 192.168.100.3:80                    1        3        0      180        0
```

Could you let me know the reason why Client rarely runs "curl 10.0.0.100" successfully?

Thanks!

**Comment by ywc689** [comment]
Is the NIC support flow director? You can try run dpvs with single lcore and see if it works.

**Comment by ywc689** [comment]
Does the NIC support flow director? You can run dpvs with single lcore and see if it works.

**Comment by tiepnv-viosoft** [comment]
Thank ywc689 for quick reply.
My NICs supports Flow director. 
I'm a newbie, could you show me how to run dpvs with single lcore?

Thanks,

**Comment by tiepnv-viosoft** [comment]
Thank ywc689,
It worked with single lcore in /etc/dpvs.conf.

**Comment by ywc689** [comment]
You can verify if your NIC supports flow director using DPDK API `rte_eth_dev_filter_supported(port_id, RTE_ETH_FILTER_FDIR)`.  We will deal with such device feature related exceptions in later releases.

**Comment by tiepnv-viosoft** [comment]
Thank for your support!
