### ISSUE TITLE
FNAT with two ports

### ISSUE THREAD

**Issue by lapnd** [iqiyi/dpvs#168]
Hi,
I'm going to setup FNAT (two arm) that expose port 80 and 443 to Internet.
I tried to use ipvsadm to add two ports but at step "ipvsadm --add-laddr" it says the address already added.
Can you suggest on how to add two ports for FNAT modes? (Or how to redirect traffic from port 80 to 443  in WAN side with DPVS)?
Thank you!

**Comment by beacer** [comment]
Pls ignore 'address already added', it should works by adding multiple `VIP:port`. No redirect needed.

**Comment by lapnd** [comment]
Thank you!
It works fine.
