### ISSUE TITLE
Can not capture with device as dpdk.0 or dpdk.bond0

### ISSUE THREAD

**Issue by aguaiyoung** [iqiyi/dpvs#18]
dpvs test in my enviroment is ok. It's very nice job.Greaet!!!
but it can't capture packet on uesrspace .
my test envrioment ：
CentOS release 6.5
2.6.32
CPU E5-2650
gcc version 4.4.7

and some little bug like this:
1. redefinition
typedef uint8_t lcoreid_t;
typedef uint8_t portid_t;
typedef uint16_t queueid_t;
in include/dpdk.h and in include/conf/netif.h so it redefinition with my compile.so i think it place in include/common.h

diff --git a/include/conf/netif.h b/include/conf/netif.h
index 2f445ab..8d6851e 100644
--- a/include/conf/netif.h
+++ b/include/conf/netif.h
@@ -18,6 +18,7 @@
 #ifndef __NETIF_CONF_H__
 #define __NETIF_CONF_H__
 #include <linux/if_ether.h>
+#include "common.h"
 
 #define NETIF_MAX_PORTS     64
 #define NETIF_MAX_LCORES    64
@@ -30,9 +31,9 @@
 #define RTE_ETHDEV_QUEUE_STAT_CNTRS     16
 #define NETIF_MAX_BOND_SLAVES           32
 
-typedef uint8_t lcoreid_t;
-typedef uint8_t portid_t;
-typedef uint16_t queueid_t;
+//typedef uint8_t lcoreid_t;
+//typedef uint8_t portid_t;
+//typedef uint16_t queueid_t;
 
 #define NETIF_PORT_FLAG_RX_IP_CSUM_OFFLOAD  0x1<<3
 #define NETIF_PORT_FLAG_TX_IP_CSUM_OFFLOAD  0x1<<4
[root@lvs-master dpvs]# git diff include/conf/netif.h include/dpdk.h  include/common.h
diff --git a/include/common.h b/include/common.h
index 5643f0d..af87f5a 100644
--- a/include/common.h
+++ b/include/common.h
@@ -21,6 +21,10 @@
 #include <stdint.h>
 #include <linux/if_ether.h>
 
+typedef uint8_t lcoreid_t;
+typedef uint8_t portid_t;
+typedef uint16_t queueid_t;
+
 #ifndef NELEMS
 #define NELEMS(a)       (sizeof(a) / sizeof((a)[0]))
 #endif
diff --git a/include/conf/netif.h b/include/conf/netif.h
index 2f445ab..8d6851e 100644
--- a/include/conf/netif.h
+++ b/include/conf/netif.h
@@ -18,6 +18,7 @@
 #ifndef __NETIF_CONF_H__
 #define __NETIF_CONF_H__
 #include <linux/if_ether.h>
+#include "common.h"
 
 #define NETIF_MAX_PORTS     64
 #define NETIF_MAX_LCORES    64
@@ -30,9 +31,9 @@
 #define RTE_ETHDEV_QUEUE_STAT_CNTRS     16
 #define NETIF_MAX_BOND_SLAVES           32
 
-typedef uint8_t lcoreid_t;
-typedef uint8_t portid_t;
-typedef uint16_t queueid_t;
+//typedef uint8_t lcoreid_t;
+//typedef uint8_t portid_t;
+//typedef uint16_t queueid_t;
 
 #define NETIF_PORT_FLAG_RX_IP_CSUM_OFFLOAD  0x1<<3
 #define NETIF_PORT_FLAG_TX_IP_CSUM_OFFLOAD  0x1<<4
diff --git a/include/dpdk.h b/include/dpdk.h
index c8ff11a..5fc6ae9 100644
--- a/include/dpdk.h
+++ b/include/dpdk.h
@@ -55,9 +55,10 @@
 #include <rte_ip_frag.h>
 #include <rte_eth_bond.h>
 #include "mbuf.h"
+#include "common.h"
 
-typedef uint8_t lcoreid_t;
-typedef uint8_t portid_t;
-typedef uint16_t queueid_t;
+//typedef uint8_t lcoreid_t;
+//typedef uint8_t portid_t;
+//typedef uint16_t queueid_t;
 
 #endif /* __DPVS_DPDK_H__ */
2. can not show conn like as ./ipvsadm -ln -c

**Comment by beacer** [comment]
1. What do you mean packet capture, use tcpdump? It can be used on KNI device, like `dpdk0.kni`, but not DPDK device, and forwarding packet cannot be captured now.
2. For "no connection", can you show more info like `ipvsadm -ln`, `dpip link show`, `dpip route show` ?

**Comment by aguaiyoung** [comment]
thank your replay 
1. i means forwarding packet. I think we can copy forwarding packet to caputure ring to like dpdk0.capure.
2. like this
PVS connection entries
pro expire state       source             virtual            destination

**Comment by beacer** [comment]
@aguaiyoung 
1. to test forwarding, pls follow `doc/tutorial.md`.
2. "capture ring"? do you mean capturing packets by DPDK's `pdump`? it need rebuild DPDK and a bit of code changing. you can refer DPDK document for `pdump`.

**Comment by aguaiyoung** [comment]
ok,3q
