### ISSUE TITLE
Is iptables conflict with dpvs

### ISSUE THREAD

**Issue by haosdent** [iqiyi/dpvs#185]
In private network, I use the default devices without DPVS.
In public network, I use the DPDK devices with DPVS.

Currently, I found if I settings iptables rules on the private network, it would make the DPDK could not be accessed by others. Is there any requirements on iptables for DPDK?

**Comment by beacer** [comment]
`iptables` should not affect basic dpvs function, however, it may affect health-check by `keepalived`, which is running on `kni` interface from Linux side.

**Comment by haosdent** [comment]
Noted, many thx
