### ISSUE TITLE
Stats API 

### ISSUE THREAD

**Issue by ba0f3** [iqiyi/dpvs#195]
Hello, is there any docs about getting stats from `dvps_ctrl` socket? How do I get inbound/outbound packets rate, traffic rate per second on specified interface?

Thank you for a great project!

**Comment by ywc689** [comment]
use `dpip link show -s  dpdk0 ` for total stats for dpdk0
use `dpip link show -s -i 3 -C dpdk0`  to watch current PPS/BPS

**Comment by ba0f3** [comment]
Thank you, I were able to create a small tool to export stats to Prometheus, hope it useful. https://gitlab.com/ba0f3/dpvs_exporter
