### ISSUE TITLE
Add the timestamp in ttgw.log

### ISSUE THREAD

**Issue by andrewhit** [iqiyi/dpvs#197]
Currently, there is no time stamp in ttgw.log and it is not convenient for debugging.

It is better to have the similar time stamp as below nginx's error.log.

2018/06/11 10:51:40 [alert] 1649136#0: *2699686907 write() to "/var/log/nginx/access.log" was incomplete: 36 of 101 while logging request, client: 10.10.127.69, server: localhost9090, request: "GET / HTTP/1.1", host: "10.10.76.66:2007", referrer: "http://10.10.76.66:2007"

**Comment by beacer** [comment]
if you use default `syslog`, it do has timestamp. if you wan to separate `dpvs` log from other logs in `/var/log/message`, you can configure `syslog` to achieve that.

**Comment by beacer** [comment]
顶一下。

**Comment by beacer** [comment]
It's `/var/log/message` by default, instead of  `/var/log/syslog`.

**Comment by beacer** [comment]
By default, it's save to `syslogd` (`/var/log/message`  on `CentOS`), `DPVS` use DPDK `RTE_LOG`, if redirect the log to normal file, `RTE_LOG` do not support timestamp.
You can use  `grep` and `tail -f` to check the log file for DPVS log.
If you want to separate app's log from syslogd  default file (etc, `/var/log/message`)， you can try config syslogd and make little code change.
https://stackoverflow.com/questions/10376020/how-to-configure-syslog-so-that-an-applications-log-goes-to-a-specific-file

**Comment by andrewhit** [comment]
My some colleague has solved this issue.

dpvs的log是使用的dpdk提供的RTE_LOG接口，支持syslog。
dpdk为应用程序提供了 --syslog 这个命令行参数 
--syslog
Set the syslog facility.

可以修改dpvs的启动脚本(/opt/dpvs/dpvs)在DAEMON_OPTS中增加参数
--syslog local7

同时修改syslog的配置文件(debian下为 /etc/rsyslog.conf）增加一行：
local7.*                -/var/log/dpvs.log

同时删除dpvs.conf中的log_file选项
重启syslog服务 systemctl restart rsyslog 再重启dpvs，dpvs的log将会输出到/var/log/dpvs.log中，同时附带有时间戳。

root@n10-023-013:~# tail  /var/log/dpvs.log
Aug 30 18:35:02 n10-023-013 ttgw[3032041]: IPVS: conn lookup: [4] TCP 10.10.127.2:8080 -> 10.10.127.66:49398 miss
Aug 30 18:35:02 n10-023-013 ttgw[3032041]: IPVS: tcp_conn_sched: [4] try sched non-SYN packet: [S.A.] 10.10.127.2:8080->10.10.127.66:49398
Aug 30 18:35:03 n10-023-013 ttgw[3032041]: IPVS: conn lookup: [2] TCP 10.10.127.67:80 -> 10.10.127.66:44446 miss

dpvs的log等级仍然由dpvs.conf中的log_level字段控制。

在dpvs.conf中直接设置log_file会导致日志没有时间戳信息，只能按照上述方法操作。但是该方法必须要重启dpvs服务。
