### ISSUE TITLE
Inconsistent neighbour static flag

### ISSUE THREAD

**Issue by ba0f3** [iqiyi/dpvs#204]
https://github.com/iqiyi/dpvs/blob/d6f33d85e3628ce037b9be52f5e4341917e76b7c/tools/dpip/neigh.c#L29
https://github.com/iqiyi/dpvs/blob/0b7b038601aafd78afa25439d2734bd5bca0d156/src/neigh.c#L73

`dpip neigh show` won't displays static flag

**Comment by mscbg** [comment]
@ba0f3 ；Thanks a lot. This is really a bug because of commit "add state for neighbour 2c93f7c4c3b9948f52cc42879da4bf952ecfc747". I will fix this.

**Comment by mscbg** [comment]
#209
