### ISSUE TITLE
Keepalived性能优化建议

### ISSUE THREAD

**Issue by taylor3768** [iqiyi/dpvs#218]
![image](https://user-images.githubusercontent.com/19178969/42307862-6f725ebc-8066-11e8-82d3-3dcb4ac61c6e.png)
**如上图所示，阿里云SLB负载均衡，对于keepalived的优化。原来的select模型在后端RS超过1024之后，会面临性能瓶颈的吧。可否考虑改成epoll模型**

**Comment by beacer** [comment]
1. RS超过1024个？ 如果确实有这种部署情况，是可以改成epoll的，但目前我们这边的线上环境还没这种需求。
3. reload的优化，文章里没有看出是针对什么场景。是否有更详细的描述？

**Comment by taylor3768** [comment]
@beacer 
1.云计算公司，后台超过1024很正常吧。
2.reload优化，LSB也没讲，有两种可能，1.优化了配置重新加载 2.吹牛逼。。。
还有，有没有内部交流群。拉下我，wechat号  taylorcheerup

**Comment by ywc689** [comment]
DPVS 已移植 keepalived v2.0.19，支持 epoll.
