### ISSUE TITLE
How to improve the performance of SNAT

### ISSUE THREAD

**Issue by haosdent** [iqiyi/dpvs#221]
For fullnat, we know we could add more LIP if sa pool is full.

For snat, since don't have LIP, how to improve its performance? Add more WAN IP via

`ipvsadm -a -H $MATCH0 -r $WAN_IP:0 -w 100 -J`？

**Comment by beacer** [comment]
Yes, you can add more WIP. By default Round-Robin algo is used for selecting WIP from WIP-list.

**Comment by haosdent** [comment]
Noted, thank you Orz
