### ISSUE TITLE
ipvsadm -ln 查看时经常 报错 errcode set in sockopt msg reply: msg dropped

### ISSUE THREAD

**Issue by snailq** [iqiyi/dpvs#225]
MSGMGR: multicast_msg_send: mc_msg(type:11, cid:0->slaves) timeout(2000 us), drop...
SERVICE: dp_vs_copy_stats: send message fail.
MSGMGR: sockopt_ctl: socket msg<type=GET, id=202> callback failed
MSGMGR: [sockopt_msg_send:msg#202] errcode set in sockopt msg reply: msg dropped

**Comment by beacer** [comment]
描述下具体的环境、和复现步骤。比如，fnat还是snat, 具体vip配置，流量大小，并发数，命令调用频率等。
还有详细的log和dpvs版本。

**Comment by czn911** [comment]
@snailq 
Hello, may I ask if your problem has been solved? I have the same problem as you, but it is not easy to reproduce, I am still review the code, I don’t know how to solve it.

MSGMGR: multicast_msg_send: mc_msg(type:17, cid:0->slaves) timeout(2000 us), drop...

**Comment by czn911** [comment]
@beacer 
我的场景是，创建删除 黑名单，我的配置量很大。

**Comment by snailq** [comment]
@beacer funat模式，只是上线测试服务 无流量   执行ipvsadm -ln查看状态 就会出现，不是100%出现 但至少有30-40%概率
硬件配置 
cpu 16核  mem 128G 已关闭ht
LIP配置40个

dpvs -v
dpvs version: 1.6-1, build on 2018.08.28.17:30:23

ipvsadm -ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.120.101.1:80 wrr
  -> 10.136.27.200:80             FullNat 100    0          0
  -> 10.136.27.201:80             FullNat 100    0          0
  -> 10.136.27.202:80             FullNat 100    0          0
  -> 10.136.27.203:80             FullNat 100    0          0

配置文件 dpvs.conf
global_defs {
!    #daemon
    log_level   DEBUG
    log_file    /var/log/dpvs.log
}

! netif config
netif_defs {
    <init> pktpool_size     524287
    <init> pktpool_cache    256

    <init> device dpdk0 {
        rx {
            queue_number        16
            descriptor_number   1024
            rss                 tcp
        }
        tx {
            queue_number        16
            descriptor_number   1024
        }
        promisc_mode
        kni_name                dpdk0.kni
    }
}

! worker config (lcores)
worker_defs {
    <init> worker cpu0 {
        type    master
        cpu_id  0
    }

    <init> worker cpu1 {
        type    slave
        cpu_id  1
        port    dpdk0 {
            rx_queue_ids     0
            tx_queue_ids     0
            ! isol_rx_cpu_ids  9
            ! isol_rxq_ring_sz 1048576
        }
   }

    <init> worker cpu2 {
        type    slave
        cpu_id  2
        port    dpdk0 {
            rx_queue_ids     1
            tx_queue_ids     1
            ! isol_rx_cpu_ids  10
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu3 {
        type        slave
        cpu_id      3
        port        dpdk0 {
            rx_queue_ids     2
            tx_queue_ids     2
            ! isol_rx_cpu_ids  11
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker   cpu4 {
        type        slave
        cpu_id      4
        port        dpdk0 {
            rx_queue_ids     3
            tx_queue_ids     3
            ! isol_rx_cpu_ids  12
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker   cpu5 {
        type        slave
        cpu_id      5
        port        dpdk0 {
            rx_queue_ids     4
            tx_queue_ids     4
            ! isol_rx_cpu_ids  13
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker   cpu6 {
        type        slave
        cpu_id      6
        port        dpdk0 {
            rx_queue_ids     5
            tx_queue_ids     5
            ! isol_rx_cpu_ids  14
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker   cpu7 {
        type        slave
        cpu_id      7
        port        dpdk0 {
            rx_queue_ids     6
            tx_queue_ids     6
            ! isol_rx_cpu_ids  15
            ! isol_rxq_ring_sz 1048576
        }
    }

    <init> worker   cpu8 {
        type        slave
        cpu_id      8
        port        dpdk0 {
            rx_queue_ids     7
            tx_queue_ids     7
            ! isol_rx_cpu_ids  16
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu9 {
        type        slave
        cpu_id      9
        port        dpdk0 {
            rx_queue_ids     8
            tx_queue_ids     8
            ! isol_rx_cpu_ids  17
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu10 {
        type        slave
        cpu_id      10
        port        dpdk0 {
            rx_queue_ids     9
            tx_queue_ids     9
            ! isol_rx_cpu_ids  18
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu11 {
        type        slave
        cpu_id      11
        port        dpdk0 {
            rx_queue_ids     10
            tx_queue_ids     10
            ! isol_rx_cpu_ids  19
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu12 {
        type        slave
        cpu_id      12
        port        dpdk0 {
            rx_queue_ids     11
            tx_queue_ids     11
            ! isol_rx_cpu_ids  20
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu13 {
        type        slave
        cpu_id      13
        port        dpdk0 {
            rx_queue_ids     12
            tx_queue_ids     12
            ! isol_rx_cpu_ids  21
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu14 {
        type        slave
        cpu_id      14
        port        dpdk0 {
            rx_queue_ids     13
            tx_queue_ids     13
            ! isol_rx_cpu_ids  22
            ! isol_rxq_ring_sz 1048576
        }
    }
    <init> worker   cpu15 {
        type        slave
        cpu_id      15
        port        dpdk0 {
            rx_queue_ids     14
            tx_queue_ids     14
            ! isol_rx_cpu_ids  23
            ! isol_rxq_ring_sz 1048576
        }
    }
}

! timer config
timer_defs {
    # cpu job loops to schedule dpdk timer management
    schedule_interval    500
}

! dpvs neighbor config
neigh_defs {
    <init> unres_queue_length  128
    <init> timeout             60
}

! dpvs ipv4 config
ipv4_defs {
    <init> default_ttl         64
    fragment {
        <init> bucket_number   4096
        <init> bucket_entries  16
        <init> max_entries     4096
        <init> ttl             1
    }
}

! control plane config
ctrl_defs {
    lcore_msg {
        <init> ring_size                4096
        <init> multicast_queue_length   256
        sync_msg_timeout_us             5000
    }
    ipc_msg {
        <init> unix_domain /var/run/dpvs_ctrl
    }
}

! ipvs config
ipvs_defs {
    conn {
        <init> conn_pool_size       2097152
        <init> conn_pool_cache      256
        conn_init_timeout           3
    !    expire_quiescent_template
    !    fast_xmit_close
    }

    udp {
        defence_udp_drop
        timeout {
            normal      300
            last        3
        }
    }

    tcp {
        defence_tcp_drop
        timeout {
            none        2
            established 360
            syn_sent    3
            syn_recv    30
            fin_wait    3
            time_wait   3
            close       3
            close_wait  3
            last_ack    3
            listen      120
            synack      30
            last        2
        }
        synproxy {
            synack_options {
                mss             1452
                ttl             63
                sack
            !    wscale
            !    timestamp
            }
        !    defer_rs_syn
            rs_syn_max_retry    3
            ack_storm_thresh    10
            max_ack_saved       3
            conn_reuse_state {
                close
                time_wait
            !    fin_wait
            !    close_wait
            !    last_ack
           }
        }
    }
}

! sa_pool config
sa_pool {
    pool_hash_size   16
}


相关log
MSGMGR: sockopt_ctl: socket msg<type=GET, id=204> callback failed
MSGMGR: [sockopt_msg_send:msg#204] errcode set in sockopt msg reply: invalid parameter
MSGMGR: multicast_msg_send: mc_msg(type:11, cid:0->slaves) timeout(2000 us), drop...
SERVICE: dp_vs_copy_stats: send message fail.
MSGMGR: sockopt_ctl: socket msg<type=GET, id=202> callback failed
MSGMGR: [sockopt_msg_send:msg#202] errcode set in sockopt msg reply: msg dropped
MSGMGR: multicast_msg_send: mc_msg(type:11, cid:0->slaves) timeout(2000 us), drop...
SERVICE: dp_vs_copy_stats: send message fail.
MSGMGR: sockopt_ctl: socket msg<type=GET, id=203> callback failed
MSGMGR: [sockopt_msg_send:msg#203] errcode set in sockopt msg reply: msg dropped
MSGMGR: multicast_msg_send: mc_msg(type:11, cid:0->slaves) timeout(2000 us), drop...
SERVICE: dp_vs_copy_stats: send message fail.
MSGMGR: sockopt_ctl: socket msg<type=GET, id=203> callback failed
MSGMGR: [sockopt_msg_send:msg#203] errcode set in sockopt msg reply: msg dropped
MSGMGR: multicast_msg_send: mc_msg(type:11, cid:0->slaves) timeout(2000 us), drop...
SERVICE: dp_vs_copy_stats: send message fail.
请大神帮忙分析下 
发现有个别服务器是20核cpu但是配置 使用16核的就会好一些不经常出现这个报错

@beacer 请问下  黑名单是怎么添加的

**Comment by superpanpan** [comment]
MSGMGR: sockopt_ctl: socket msg<type=SET, id=207> callback failed
MSGMGR: [sockopt_msg_send:msg#207] errcode set in sockopt msg reply: invalid parameter
MSGMGR: sockopt_ctl: socket msg<type=SET, id=401> callback failed
MSGMGR: [sockopt_msg_send:msg#401] errcode set in sockopt msg reply: not exist
Kni: 3 events received!
Kni: kni_update_maddr: set mcast to bond0.kni
Kni: dev bond0 link mcast:
Kni:     new [00] 33:33:00:00:00:01
Kni:     new [01] 01:00:5e:00:00:01
Kni: kni_mc_list_cmp_set: add mc addr: 33:33:00:00:00:01 bond0 OK
Kni: kni_mc_list_cmp_set: add mc addr: 01:00:5e:00:00:01 bond0 OK
NETIF: __netif_hw_addr_sync_multiple: sync 33:33:00:00:00:01 to dpdk0 OK!
NETIF: __netif_hw_addr_sync_multiple: sync 01:00:5e:00:00:01 to dpdk0 OK!
NETIF: __netif_hw_addr_sync_multiple: sync 33:33:00:00:00:01 to dpdk2 OK!
NETIF: __netif_hw_addr_sync_multiple: sync 01:00:5e:00:00:01 to dpdk2 OK!
Kni: update maddr of bond0 OK!
MSGMGR: sockopt_ctl: socket msg<type=SET, id=205> callback failed
MSGMGR: [sockopt_msg_send:msg#205] errcode set in sockopt msg reply: invalid parameter
MSGMGR: sockopt_ctl: socket msg<type=SET, id=205> callback failed
MSGMGR: [sockopt_msg_send:msg#205] errcode set in sockopt msg reply: invalid parameter
MSGMGR: sockopt_ctl: socket msg<type=SET, id=205> callback failed
MSGMGR: [sockopt_msg_send:msg#205] errcode set in sockopt msg reply: invalid parameter
PMD: ixgbe_dev_link_status_print(): Port 0: Link Up - speed 10000 Mbps - full-duplex
PMD: ixgbe_dev_link_status_print(): PCI Address: 0000:08:00.0
PMD: ixgbe_dev_link_status_print(): Port 1: Link Up - speed 10000 Mbps - full-duplex
PMD: ixgbe_dev_link_status_print(): PCI Address: 0000:08:00.1
MSGMGR: sockopt_ctl: socket msg<type=SET, id=205> callback failed
MSGMGR: [sockopt_msg_send:msg#205] errcode set in sockopt msg reply: invalid parameter
MSGMGR: sockopt_ctl: socket msg<type=SET, id=205> callback failed
MSGMGR: [sockopt_msg_send:msg#205] errcode set in sockopt msg reply: invalid paramete

**Comment by ywc689** [comment]
The problem is caused by locking. DPVS remove all locks on critical datapath and core modules are implemented per-cpu since v1.8. The problem is alleviated dramatically then.
