### ISSUE TITLE
使用intel I350与I210 型号的网卡  dpvs full NAT 模式无法正常工作

### ISSUE THREAD

**Issue by wangdwcsd** [iqiyi/dpvs#228]
[root@swift04 bin]# **./dpip addr show**
inet 172.21.7.20/24 scope global dpdk0
     valid_lft forever preferred_lft forever
inet 172.21.7.14/32 scope global dpdk0
     valid_lft forever preferred_lft forever sa_used 0 sa_free 1032176 sa_miss 0
[root@swift04 bin]# **./dpip route show**
inet 172.21.7.14/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope host metric 0 proto auto 
inet 172.21.7.20/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope host metric 0 proto auto 
inet 172.21.7.0/24 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope link metric 0 proto auto 

[root@swift04 bin]# **more setup.sh** 
VIP=172.21.7.20
LIP=172.21.7.14
RS=172.21.7.4

./dpip addr add ${VIP}/24 dev dpdk0
./ipvsadm -A -t ${VIP}:80 -s rr
./ipvsadm -a -t ${VIP}:80 -r ${RS} -b

./ipvsadm --add-laddr -z ${LIP} -t ${VIP}:80 -F dpdk0

**在同vlan的客户端测试：**
[root@swift02 ~]# **ping 172.21.7.20** 
PING 172.21.7.20 (172.21.7.20) 56(84) bytes of data.
64 bytes from 172.21.7.20: icmp_seq=1 ttl=64 time=0.147 ms
64 bytes from 172.21.7.20: icmp_seq=2 ttl=64 time=0.053 ms
^C
--- 172.21.7.20 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.053/0.100/0.147/0.047 ms
[root@swift02 ~]# **ping 172.21.7.14**
PING 172.21.7.14 (172.21.7.14) 56(84) bytes of data.
64 bytes from 172.21.7.14: icmp_seq=1 ttl=64 time=0.052 ms
64 bytes from 172.21.7.14: icmp_seq=2 ttl=64 time=0.077 ms
64 bytes from 172.21.7.14: icmp_seq=3 ttl=64 time=0.050 ms

[root@swift02 ~]# **telnet 172.21.7.4 80 **
Trying 172.21.7.4...
Connected to 172.21.7.4.
Escape character is '^]'

[root@swift02 ~]# **telnet 172.21.7.20 80**
Trying 172.21.7.20...

[root@swift02 ~]# **telnet 172.21.7.20 80**
Trying 172.21.7.20...
Connected to 172.21.7.20.
Escape character is '^]'.

使用vip 访问80 端口，一会可以正常访问，一会无法访问

**Comment by wangdwcsd** [comment]
使用Intel 82599 型号的网卡测试时没有发现上述问题

**Comment by beacer** [comment]
i350 (igb驱动）的网卡不支持flow director, FullNAT必须用fdir.
http://doc.dpdk.org/guides/nics/overview.html#id1

**Comment by wangdwcsd** [comment]
非常感谢！！!
