### ISSUE TITLE
求教：绑定dpdk0和dpdk1为bond1失败

### ISSUE THREAD

**Issue by sailq21** [iqiyi/dpvs#234]
编辑 /etc/dpvs.conf配置文件，讲bond0相关的内容的注释去掉，如下
   <init> bonding bond1 {
        mode        6
        slave       dpdk0
        slave       dpdk1
        primary     dpdk0
        kni_name    bond1.kni
    }
然后启动dpvs服务报错。
./dpvs &
报错内容如下
Kni: kni_add_dev: fail to set mac 00:00:00:00:00:00 for bond1.kni: Cannot assign requested address
NETIF: netif_port_start: no queues to setup for dpdk0
DPVS: Start dpdk0 failed, skipping ...
NETIF: netif_port_start: no queues to setup for dpdk1
DPVS: Start dpdk1 failed, skipping ...
NETIF: netif_port_start: no queues to setup for bond1
DPVS: Start bond1 failed, skipping ...

请大神赐教。

**Comment by figo731** [comment]
看文档，目前bond只支持mode0和mode4。mode6不支持
