### ISSUE TITLE
.ndo_change_mtu = kni_net_change_mtu

### ISSUE THREAD

**Issue by luffycjf** [iqiyi/dpvs#239]
内核Linux version 3.10.0-327.el7.x86_64和要求的一样，
dpdk-stable-17.05.2
make总是报错
 
INSTALL-LIB librte_eal.a
== Build lib/librte_eal/linuxapp/igb_uio
  LD      /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/built-in.o
  CC [M]  /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.mod.o
  LD [M]  /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.ko
INSTALL-MODULE igb_uio.ko
== Build lib/librte_eal/linuxapp/kni
  LD      /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/built-in.o
  CC [M]  /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_misc.o
  CC [M]  /root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.o
/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c:772:2: error: unknown field ‘ndo_change_mtu’ specified in initializer
  .ndo_change_mtu = kni_net_change_mtu,
  ^
/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c:772:2: error: missing braces around initializer [-Werror=missing-braces]
/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c:772:2: error: (near initialization for ‘kni_net_netdev_ops.<anonymous>’) [-Werror=missing-braces]
/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c:772:2: error: initialization from incompatible pointer type [-Werror]
/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c:772:2: error: (near initialization for ‘kni_net_netdev_ops.<anonymous>.ndo_select_queue’) [-Werror]
cc1: all warnings being treated as errors
make[10]: *** [/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.o] Error 1
make[9]: *** [_module_/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni] Error 2
make[8]: *** [sub-make] Error 2
make[7]: *** [rte_kni.ko] Error 2
make[6]: *** [kni] Error 2
make[5]: *** [linuxapp] Error 2
make[4]: *** [librte_eal] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [all] Error 2
make[1]: *** [pre_install] Error 2
make: *** [install] Error 2

**Comment by halidaltuner** [comment]
How is the problem solved?

**Comment by luffycjf** [comment]
最小化安装就没这个问题。

否则可以看下/usr/src/kernels/3.10.0-327.el7.x86_64/include/linux/netdevice.h这个里面ndo_change_mtu定义的是什么名称，我的是ndo_change_mtu_rh74，将/root/dpvs/dpdk-stable-17.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/kni_net.c这里面的ndo_change_mtu换成ndo_change_mtu_rh74就行了。

官方说这个是个bug，在dpdk 18.0.2之后就修复了。
