### ISSUE TITLE
DPVS could not receive OSPF multiple cast package from switch

### ISSUE THREAD

**Issue by haosdent** [iqiyi/dpvs#256]
@beacer @mscbg masters, I configure ospf following this guide https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#fnat-ospf . However, after I using dpvs in this server, quagga could not establish correctly with switch. quagga could ping switch, however the connection stuck at INIT state in switch.

If I rollback to kernel driver, quagga could discover the switch successfully.
I try to enable forward2kni in dpdk interfaces, iptables are disabled as well. I still could not see OSPF multiple cast package from switch via tcpdump. Do you have any clues on this? Thank you in advance.

**Comment by mscbg** [comment]
You can run dpip link show -v to see whether it has ospf multiple mac.
![image](https://user-images.githubusercontent.com/20103281/45405235-9ff74e80-b694-11e8-85e2-b0143a161b60.png)

**Comment by hulinfan** [comment]
这个坑我也踩过，如何将组播 MAC 地址添加到网口？建议更新一下 tutorial 文档
