### ISSUE TITLE
ARP entry is not updated in NAT-mode after arp request is sent out.

### ISSUE THREAD

**Issue by andrewhit** [iqiyi/dpvs#278]
After fixing [issue 276](https://github.com/iqiyi/dpvs/issues/276), another issue is found that ARP reply is not received by dpvs.

dpvs 10.10.127.66/26 ---- RS (10.10.127.67/26)

```
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IPVS: conn lookup: [1] TCP 10.2.196.1:54785 -> 10.10.76.66:6000 miss
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IPVS: new conn:  [1] TCP 10.2.196.1:54785 10.10.76.66:6000 10.2.196.1:54785 10.10.127.67:80 refs 2
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IPVS: state trans: TCP in [S...] 10.2.196.1:54785->10.10.127.67:80  state NONE->SYN_RECV conn.refcnt 2
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: NEIGHBOUR: [neigh_arp_confirm] daddr 10.10.127.67
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IFA: inet_addr_select: idev 0x7f68e25f0b00, port eth3, ifa_cnt 2, list is not empty
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IFA: inet_addr_select (1000): flags 80, scope 0, plen 26, addr 10.10.127.66
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: IFA: inet_addr_select (2000): flags 80, scope 0, plen 26, addr 10.10.127.66
Sep 14 17:16:15 n10-023-013 ttgw[1212094]: NEIGHBOUR: [neigh_arp_confirm] saddr 10.10.127.66
```

It is observed that ARP request is sent out to 10.10.127.67 from 10.10.127.66. And RS does send back the ARP reply. However #dpip neigh show as below.

```
root@n10-023-013:/var/log# dpip neigh show
ip: 10.10.127.67      mac: 00:00:00:00:00:00      mbuf: 0
```

**Comment by andrewhit** [comment]
The root cause is that the route is not found within neigh_resolve_input() so the received ARP reply is not processed.

**Comment by mscbg** [comment]
inet_addr_select: idev 0x7f68e25f0b00, port eth3, ifa_cnt 2, list is not empty
You can configure dpvs as tutorial.md.
You can add 10.10.127.66 as 'dpip addr add 10.10.127.66/26 dev dpdk1'. 10.10.127.66**/26** doesn't mean anything in keepalived

**Comment by andrewhit** [comment]
10.10.127.66/26 is the lan-side link address configured on dpvs and it 

Firstly, it does not make sense to configure local_address_group{} in nat-mode which does not need to allocate any sapool resource. 

So I choose to use static_ipaddress{} to configure the lan-side link address. However, I found some bug [issue 276](https://github.com/iqiyi/dpvs/issues/276) and provide the fix, [pull 277](https://github.com/iqiyi/dpvs/pull/277).

static_ipaddress {
    10.10.127.66/26  dev eth3
}

Since the route to 10.10.127.66/32 is configured as RTF_KNI duriing my dpvs startup script via dpip route add command, the ARP entry fails to be updated though the ARP reply is received from the peer and the previously created ARP entry is found within route4_local().

```
# dpip route show 
...
inet 10.10.127.66/32 via 0.0.0.0 src 0.0.0.0 dev eth3 mtu 1500 tos 0 scope kni_host metric 0 proto auto
...
```

When ARP reply is received via neigh_resolve_input() from 10.10.127.67, we need to find the route to the target IP, 10.10.127.66. However since the found route is NOT RTF_LOCALIN type within route4_local(), we failed to update the found APR entry.

The solution is adding one more condition, RTF_KNI within route4_local() to allow the arp entry to be updated per the received arp reply.

**Comment by mscbg** [comment]
Yes, you are right. And you should also be noticed that log(select src_ip) also means something wrong. As result, dpvs find no src_ip and it will just select the first one. That may cause something wrong.

**Comment by andrewhit** [comment]
[pull 277](https://github.com/iqiyi/dpvs/pull/277/commits) provides the fix.

**Comment by andrewhit** [comment]
Here is the debugging info to which some debugging info is added.

```
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IPVS: conn lookup: [1] TCP 10.2.196.1:64992 -> 10.10.76.66:6000 miss
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IPVS: new conn:  [1] TCP 10.2.196.1:64992 10.10.76.66:6000 10.2.196.1:64992 10.10.127.67:80 refs 2
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IPVS: state trans: TCP in [S...] 10.2.196.1:64992->10.10.127.67:80  state NONE->SYN_RECV conn.refcnt 2
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: [neigh_arp_confirm] daddr 10.10.127.67
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IFA: inet_addr_select: idev 0x7f40e25f0b00, port eth3, ifa_cnt 2, list is not empty
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IFA: inet_addr_select (1000): flags 10080, scope 0, plen 32, addr 10.10.127.68
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IFA: inet_addr_select (1000): flags 80, scope 0, plen 26, addr 10.10.127.66
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: IFA: inet_addr_select (2000): flags 80, scope 0, plen 26, addr 10.10.127.66
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: [neigh_arp_confirm] saddr 10.10.127.66
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NETIF: send lcore 1 port1 arp hlen 6 plen 4 op 1
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NETIF:  sha 90:e2:ba:ea:dc:c1 sip 10.10.127.66 tha 00:00:00:00:00:00 tip 10.10.127.67
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: NONE trans state to SEND.
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NETIF: netif_deliver_mbuf: received pkt type 0x608
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NETIF: recv lcore 1 port0 arp hlen 6 plen 4 op 2
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NETIF:  sha 0c:c4:7a:f4:29:fd sip 10.10.127.67 tha 90:e2:ba:ea:dc:c1 tip 10.10.127.66
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: [neigh_resolve_input] -> reply (1000)
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: ROUTE: route4_local: route 0x7f4309beff00
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: ROUTE: route4_local: route 0x7f4309beff00, flag 0x2000
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: [neigh_resolve_input] -> reply (1004)
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: [neigh_resolve_input] -> 2000, ipaddr 437f0a0a
Sep 17 15:00:51 n10-023-013 ttgw[2689998]: NEIGHBOUR: SEND trans state to REACHABLE.
```
