### ISSUE TITLE
configure DPVS via dr mode

### ISSUE THREAD

**Issue by wjgme1971** [iqiyi/dpvs#28]
Can dpvs do supports DR mode? how to configured /etc/keepalived/keepalived.conf ,here interface  use dpdk0 or dpd0.kni ? I set as it, but it cannot work ! no keepalived package sendout!

**Comment by beacer** [comment]
Keepalived should be run on kni device. And the addr/route should also be config correctly on KNI device.
Can you show the output of `dpip addr show`, `dpip route show` , `ip addr show` and ` ip rout show` ?

________________________________
beacer_chen@hotmail.com

**Comment by wjgme1971** [comment]
thanks

**Comment by beacer** [comment]
We will add some documents for `FullNAT`, `DR`, `SNAT` mode configuration, with and without `ospfd`, `keepalived`. Currentlly, it's really need a lot of background knowlage about `LVS/FNAT` and `DPDK/kni` to config DPVS.

**Comment by wjgme1971** [comment]
thanks, now DPVS use 'dpip addr LIP dev dpdk0' , so it can work, the RS device can received LIP'arprequest and RS sent arpack to DPVS, the client use curl command and request http OK.
  Another problem is 'keepalived via DR mode can't work',maybe keepalived on DPVS not supported. Can you give me some example for configuration keepalived on DPVS? thanks.

**Comment by beacer** [comment]
Glad to know you got `DR` mode works. DPVS support `keepalived` and `ospfd`, actually we're using them on our IDC. Both `keepalived` and `ospfd` need `kni` interface and some networking configs. And we're writing the config examples, will upload the example config to GIT soon.

**Comment by wjgme1971** [comment]
OK，I am very eager to get the idea. thanks greatly.

**Comment by beacer** [comment]
@wjgme1971 pls check `doc/tutorial.md`, if you still have problem not covered by the tutorial, you can reopen this issue.
