### ISSUE TITLE
请问dpvs将来支持dnat功能吗？

### ISSUE THREAD

**Issue by jiangsuwwj1** [iqiyi/dpvs#281]
请问dpvs将来支持dnat功能吗？看了文档，貌似只有snat功能。

**Comment by andrewhit** [comment]
> 请问dpvs将来支持dnat功能吗？看了文档，貌似只有snat功能。

可以试试这个pull request，只会多核NAT-mode.
https://github.com/iqiyi/dpvs/pull/289

**Comment by jiangsuwwj1** [comment]
好的，谢谢
