### ISSUE TITLE
安装报错，请支援

### ISSUE THREAD

**Issue by 59471032** [iqiyi/dpvs#30]
CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_i210.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_api.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_mac.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_manage.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_mbx.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_nvm.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/e1000_phy.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_ethtool.o
  CC [M]  /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.o
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在函数‘igb_ndo_bridge_getlink’中:
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c:2288:2: 错误：提供给函数‘ndo_dflt_bridge_getlink’的实参太少
  return ndo_dflt_bridge_getlink(skb, pid, seq, dev, mode, 0, 0, nlflags);
  ^
In file included from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/net/dst.h:13:0,
                 from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/net/sock.h:72,
                 from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/linux/tcp.h:23,
                 from /home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c:34:
/usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/linux/rtnetlink.h:115:12: 附注：在此声明
 extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
            ^
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在文件作用域：
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c:2317:2: 错误：初始值设定项里有未知的字段‘ndo_set_vf_vlan’
  .ndo_set_vf_vlan = igb_ndo_set_vf_vlan,
  ^
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在函数‘igb_ndo_bridge_getlink’中:
/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.c:2296:1: 错误：在有返回值的函数中，控制流程到达函数尾 [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[8]: *** [/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni/igb_main.o] 错误 1
make[7]: *** [_module_/home/yinfan/dpvs/dpdk-stable-16.11.3/build/build/lib/librte_eal/linuxapp/kni] 错误 2
make[6]: *** [sub-make] 错误 2
make[5]: *** [rte_kni.ko] 错误 2
make[4]: *** [kni] 错误 2
make[3]: *** [linuxapp] 错误 2
make[2]: *** [librte_eal] 错误 2
make[1]: *** [lib] 错误 2
make: *** [all] 错误 2

**Comment by ywc689** [comment]
The errors are from DPDK library. Please follow DPDK user guide to compile dpdk library.
[DPDK documentation](http://dpdk.org/doc/guides/)

**Comment by wjgme1971** [comment]
see: http://m.sohu.com/a/198747248_354963

**Comment by thinalai** [comment]
kernel: 3.10.0-514.el7.x86_64
dpdk-16.11.3

2017-11-03 7:37 GMT+08:00 wjgme1971 <notifications@github.com>:

**Comment by beacer** [comment]
the kernel and DPDK is not match: http://dpdk.org/ml/archives/users/2017-February/001511.html
For DPDK-16.07, you can try with the Kernel  we mentioned in README.md

**Comment by amjy** [comment]
kernel 3.10.0-693.5.2.el7.x86_64 for centos 7.4 does  not match with dpdk 16.07;
1. Degrade kernel to  3.10.0-327.el7.x86_64 or install centos 7.2
2. ``yum remove kernel-devel kernel-headers``
3. ``yum install kernel-devel-`uname -r` kernel-headers-`headers` ``
Maybe rpm not found !! Download from http://vault.centos.org/7.2.1511/os/x86_64/Packages/
4. ``rpm -qa | grep kernel``  The same version of kernel, kernel-devel and kernel-headers.
5. ``yum install gcc``

**Comment by okletswin** [comment]
installed with dpdk-16.11 with kernel 3.10.0-514, but fullnat test failed. I will try 3.10.0-327 with 16.07.2

@amjy 
one more question, I want to add toa patch into kernel 3.10, is it difficult to do? Do you Have experience in this area, all documents show build on 2.6 kernel.

**Comment by ywc689** [comment]
The issue is expired. High version of dpvs/dpdk/toa are released, and you can try them.
