### ISSUE TITLE
No 'CONTRIBUTING.md' was found.

### ISSUE THREAD

**Issue by lubinsz** [iqiyi/dpvs#31]
Hi all,
What is the agreement for contributions?

It seems that I didn't find the inbound agreement.
In general, the inbound license should be 'Developer Certificate of Origin, version 1.1'.
The outbound license should be 'Apache License 2.0'
And the legal information of inbound license should be in CONTRIBUTING.md.

My boss want to know the inbound license of this project and the link.

Please see this link as reference: 
https://github.com/hyperhq/runv/blob/master/CONTRIBUTING.md

Thanks.

**Comment by birdofprey** [comment]
授权协议不错😊，GPLV2 gplv2 gplv2

**Comment by ywc689** [comment]
fixed
