### ISSUE TITLE
how to config ospf?

### ISSUE THREAD

**Issue by rivergood** [iqiyi/dpvs#33]
I want to use ospf, in ospfd.conf need config interface as:
interface eth0
 ip ospf message-digest-key 1 md5 hellotencent
...
but eth0 is down, i set dpdk0 failed! as:
ifconfig dpdk0 192.168.1.140 broadcast 192.168.1.128 netmask 255.255.255.128
dpdk0: ERROR while getting interface flags: No such device
SIOCSIFBRDADDR: No such device

**Comment by ywc689** [comment]
Ospf packets are processed by kernel. So you should setup KNI interface for dpdk0, say dpdk0.kni. Then use dpdk0.kni as ospf interface in ospf.conf.

**Comment by beacer** [comment]
@rivergood Pls check `doc/tutorial.md` (just uploaded) for ospf details.
I'll close this issue, if you still have problem with ospf, you can re-open it.
