### ISSUE TITLE
双网卡配置DPVS启动报错

### ISSUE THREAD

**Issue by hq262866869** [iqiyi/dpvs#342]
网卡型号：X540-AT2 1528
内存：32G   
CPU： 24cores
绑定了2个网卡，配置文件用的默认的dpvs.conf.sample
启动报错：
CFG_FILE: not supported keyword -- type
CFG_FILE: not supported keyword -- cpu_id
CFG_FILE: not supported keyword -- port
CFG_FILE: not supported keyword -- rx_queue_ids
CFG_FILE: not supported keyword -- tx_queue_ids
CFG_FILE: not supported keyword -- worker
EAL: Error - exiting with code : 1
 Caouse : [netif_lcore_init] bad lcore configuration (error=-7),exit ...

**Comment by hq262866869** [comment]
NETIF: netif_lcore_init: lcore23 is enabled
NETIF: netif_lcore_init: lcore24 is disabled
......
NETIF: netif_lcore_init: lcore63 is disabled

**Comment by dongzerun** [comment]
![image](https://user-images.githubusercontent.com/5662235/50329876-f0076c00-0533-11e9-838a-4ffe667a80d8.png)
这少个大括号，改下吧

**Comment by dongzerun** [comment]
己经 merge 代码，可以关了 @ywc689
