### ISSUE TITLE
虚拟机上无法测试示例程序。

### ISSUE THREAD

**Issue by ygm521** [iqiyi/dpvs#360]
我的环境VMware使用centos7.4，两个网卡e1000,(一张用于管理，一张用于DPDK)，1个socket 4个cpu，8G内存。
配置文件从dpvs.conf.single-nic.sample拷贝后修改如下：
[root@localhost dpvs-master]# cat /etc/dpvs.conf
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! This is dpvs default configuration file.
!
! The attribute "" denotes the configuration item at initialization stage. Item of
! this type is configured oneshoot and not reloadable. If invalid value configured in the
! file, dpvs would use its default value.
!
! Note that dpvs configuration file supports the following comment type:
! * line comment: using '#" or '!'
! * inline range comment: using '<' and '>', put comment in between
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! global config
global_defs {
log_level WARNING
! log_file /var/log/dpvs.log
}

! netif config
netif_defs {
pktpool_size 524287
pktpool_cache 256

<init> device dpdk0 {
    rx {
        queue_number        8
        descriptor_number   1024
        rss                 all
    }
    tx {
        queue_number        8
        descriptor_number   1024
    }
    fdir {
        mode                perfect
        pballoc             64k
        status              matched
    }
    ! promisc_mode
    kni_name                dpdk0.kni
}
}

! worker config (lcores)
worker_defs {
worker cpu0 {
type master
cpu_id 0
}

<init> worker cpu1 {
    type    slave
    cpu_id  1
    port    dpdk0 {
        rx_queue_ids     0
        tx_queue_ids     0
        ! isol_rx_cpu_ids  9
        ! isol_rxq_ring_sz 1048576
    }
}
}

! timer config
timer_defs {
# cpu job loops to schedule dpdk timer management
schedule_interval 500
}

! dpvs neighbor config
neigh_defs {
unres_queue_length 128
timeout 60
}

! dpvs ipv4 config
ipv4_defs {
forwarding off
default_ttl 64
fragment {
bucket_number 4096
bucket_entries 16
max_entries 4096
ttl 1
}
}

! dpvs ipv6 config
ipv6_defs {
disable off
forwarding off
route6 {
method "hlist"
recycle_time 10
}
}

! control plane config
ctrl_defs {
lcore_msg {
ring_size 4096
multicast_queue_length 256
sync_msg_timeout_us 20000
}
ipc_msg {
unix_domain /var/run/dpvs_ctrl
}
}

! ipvs config
ipvs_defs {
conn {
conn_pool_size 2097152
conn_pool_cache 256
conn_init_timeout 3
! expire_quiescent_template
! fast_xmit_close
}

udp {
    ! defence_udp_drop
    timeout {
        normal      300
        last        3
    }
}

tcp {
    ! defence_tcp_drop
    timeout {
        none        2
        established 90
        syn_sent    3
        syn_recv    30
        fin_wait    7
        time_wait   7
        close       3
        close_wait  7
        last_ack    7
        listen      120
        synack      30
        last        2
    }
    synproxy {
        synack_options {
            mss             1452
            ttl             63
            sack
            ! wscale
            ! timestamp
        }
        ! defer_rs_syn
        rs_syn_max_retry    3
        ack_storm_thresh    10
        max_ack_saved       3
        conn_reuse_state {
            close
            time_wait
            ! fin_wait
            ! close_wait
            ! last_ack
       }
    }
}
}

! sa_pool config
sa_pool {
pool_hash_size 16
}
程序起来了但是报错如下：
[root@localhost bin]# ./dpvs
current thread affinity is set to F
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL: Invalid NUMA socket, default to 0
EAL: probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:05.0 on NUMA socket -1
EAL: Invalid NUMA socket, default to 0
EAL: probe driver: 8086:100f net_e1000_em
DPVS: dpvs version: 1.6-1, build on 2018.12.27.18:55:03
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
**NETIF: fail to flush FDIR filters for device dpdk0**
DPVS: Start dpdk0 failed, skipping ...
查看ip:
[root@localhost bin]# ./dpip addr show
inet 192.168.66.200/32 scope global dpdk0
valid_lft forever preferred_lft forever sa_used 0 sa_free 4294950896 sa_miss 0
inet 192.168.66.50/24 scope global dpdk0
valid_lft forever preferred_lft forever
在别的设备上访问：192.168.66.50 ，可以ping通但不能访问80端口。

**Comment by chenjianjian** [comment]
这后面虚机可以跑DPVS了吗？

**Comment by rockzhouj** [comment]
> @beacer @ywc689 建议给个虚拟机上跑dpvs的环境配置要求，这样便于个人开发测试，谢谢！

你好！我目前用的 vmxnet3 也遇到该问题，请问您是怎么解决的。
