### ISSUE TITLE
DPVS进程异常退出后，keepalived配置加载异常

### ISSUE THREAD

**Issue by superpanpan** [iqiyi/dpvs#368]
dpvs/src/dpvs --version
dpvs version: 1.6-0, build on 2018.06.15.15:32:50

using one-arm mode
dpvs.conf
```
config
! global config
global_defs {
    log_level    WARNING
    log_file    /var/log/dpvs.log
}

! netif config
netif_defs {
    <init> pktpool_size     524287
    <init> pktpool_cache    256

    <init> device dpdk0 {
        rx {
            queue_number        8
            descriptor_number   1024
            rss                 tcp
        }
        tx {
            queue_number        8
            descriptor_number   1024
        }
    !    promisc_mode
    !    kni_name                dpdk0.kni
    }

    <init> device dpdk2 {
        rx {
            queue_number        8
            descriptor_number   1024
            rss                 tcp
        }
        tx {
            queue_number        8
            descriptor_number   1024
        }
    !    promisc_mode
    !    kni_name                dpdk2.kni
    }

    <init> bonding bond0 {
        mode                    0
        slave                   dpdk0
        slave                   dpdk2
        primary                 dpdk0
        kni_name                bond0.kni
    }
}

! worker config (lcores)
worker_defs {
    <init> worker cpu0 {
        type    master
        cpu_id  0
    }

    <init> worker cpu1 {
        type    slave
        cpu_id  1
        port    bond0 {
            rx_queue_ids     0
            tx_queue_ids     0
            isol_rx_cpu_ids  9
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu2 {
        type    slave
        cpu_id  2
        port    bond0 {
            rx_queue_ids     1
            tx_queue_ids     1
            isol_rx_cpu_ids  10
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu3 {
        type    slave
        cpu_id  3
        port    bond0 {
            rx_queue_ids     2
            tx_queue_ids     2
            isol_rx_cpu_ids  11
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu4 {
        type    slave
        cpu_id  4
        port    bond0 {
            rx_queue_ids     3
            tx_queue_ids     3
            isol_rx_cpu_ids  12
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu5 {
        type    slave
        cpu_id  5
        port    bond0 {
            rx_queue_ids     4
            tx_queue_ids     4
            isol_rx_cpu_ids  13
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu6 {
        type    slave
        cpu_id  6
        port    bond0 {
            rx_queue_ids     5
            tx_queue_ids     5
            isol_rx_cpu_ids  14
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu7 {
        type    slave
        cpu_id  7
        port    bond0 {
            rx_queue_ids     6
            tx_queue_ids     6
            isol_rx_cpu_ids  15
            isol_rxq_ring_sz 1048576
        }
    }

    <init> worker cpu8 {
        type    slave
        cpu_id  8
        port    bond0 {
            rx_queue_ids     7
            tx_queue_ids     7
            isol_rx_cpu_ids  16
            isol_rxq_ring_sz 1048576
        }
    }
}

! timer config
timer_defs {
    # cpu job loops to schedule dpdk timer management
    schedule_interval    500
}

! dpvs neighbor config
neigh_defs {
    <init> unres_queue_length  128
    <init> timeout             60
}

! dpvs ipv4 config
ipv4_defs {
    <init> default_ttl         64
    fragment {
        <init> bucket_number   4096
        <init> bucket_entries  16
        <init> max_entries     4096
        <init> ttl             1
    }
}

! control plane config
ctrl_defs {
    lcore_msg {
        <init> ring_size                4096
        <init> multicast_queue_length   256
        sync_msg_timeout_us             2000
    }
    ipc_msg {
        <init> unix_domain /var/run/dpvs_ctrl
    }
}

! ipvs config
ipvs_defs {
    conn {
        <init> conn_pool_size       2097152
        <init> conn_pool_cache      256
        conn_init_timeout           3
    !    expire_quiescent_template
    !    fast_xmit_close
    }

    udp {
        defence_udp_drop
        timeout {
            normal      300
            last        3
        }
    }

    tcp {
        defence_tcp_drop
        timeout {
            none        2
            established 90
            syn_sent    3
            syn_recv    30
            fin_wait    7
            time_wait   7
            close       3
            close_wait  7
            last_ack    7
            listen      120
            synack      30
            last        2
        }
        synproxy {
            synack_options {
                mss             1452
                ttl             63
                sack
            !    wscale
            !    timestamp
            }
        !    defer_rs_syn
            rs_syn_max_retry    3
            ack_storm_thresh    10
            max_ack_saved       3
            conn_reuse_state {
                close
                time_wait
            !    fin_wait
            !    close_wait
            !    last_ack
           }
        }
    }
}

! sa_pool config
sa_pool {
    pool_hash_size   16
}
```

it crashes a few days ago
Jan  3 22:04:10 int-lvs2 kernel: [10810210.543822] lcore-slave-4[89625]: segfault at 100 ip 000000000057f443 sp 00007f83785fd1a0 error 6 in dpvs[400000+243000]
Jan  3 22:04:10 int-lvs2 kernel: lcore-slave-4[89625]: segfault at 100 ip 000000000057f443 sp 00007f83785fd1a0 error 6 in dpvs[400000+243000]

and ther problem is after dpvs restart, keepalived configuration will not be fully loaded 

ipvsadm -ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.253.40.2:389 wrr synproxy
  -> 10.253.0.197:389             FullNat 100    0          0         
  -> 10.253.0.198:389             FullNat 100    0          0         
TCP  10.253.40.2:636 wrr synproxy
  -> 10.253.0.197:636             FullNat 100    0          0         
  -> 10.253.0.198:636             FullNat 100    0          0         
TCP  10.253.40.3:25 wrr synproxy
  -> 10.253.0.135:25              FullNat 100    0          0         
  -> 10.253.0.136:25              FullNat 100    0          0         
  -> 10.253.1.218:25              FullNat 100    0          0         
TCP  10.253.40.3:80 wrr synproxy
  -> 10.253.0.135:80              FullNat 100    0          0         
  -> 10.253.0.136:80              FullNat 100    0          0         
  -> 10.253.1.218:80              FullNat 100    0          0         
TCP  10.253.40.3:135 wrr synproxy
  -> 10.253.0.135:135             FullNat 100    0          0         
  -> 10.253.0.136:135             FullNat 100    0          0         
  -> 10.253.1.218:135             FullNat 100    0          0         
TCP  10.253.40.3:443 wrr persistent 3600 synproxy conn_timeout 3600
  -> 10.253.0.135:443             FullNat 100    0          0         
  -> 10.253.0.136:443             FullNat 100    0          0         
  -> 10.253.1.218:443             FullNat 100    0          0         
TCP  10.253.40.3:587 wrr synproxy
  -> 10.253.0.135:587             FullNat 100    0          0         
  -> 10.253.0.136:587             FullNat 100    0          0         
  -> 10.253.1.218:587             FullNat 100    0          0         
[sockopt_msg_recv] errcode set in socket msg#204 header: invalid parameter(-1)
Success
(a lot of configuration missed here...)

**Comment by superpanpan** [comment]
NETIF: worker cpu7:bond0 tx_queue_id += 6
NETIF: worker cpu8:bond0 rx_queue_id += 7
NETIF: worker cpu8:bond0 tx_queue_id += 7
Kni: kni_add_dev: fail to set mac 00:00:00:00:00:00 for bond0.kni: Cannot assign requested address
SERVICE: dp_vs_new_stats: no memory!
SERVICE: dp_vs_new_stats: no memory!
SERVICE: dp_vs_new_stats: no memory!
SERVICE: dp_vs_new_stats: no memory

**Comment by mscbg** [comment]
从报错可以看出来，是内存不够了。dpvs进程挂了后，keepalived进程需要在dpvs起来后，再重启。
