### ISSUE TITLE
`ipvsadmin -Ln` doesn't work for SNAT

### ISSUE THREAD

**Issue by haosdent** [iqiyi/dpvs#373]
Previously `ipvsadmin -Ln' could list all set up services, but now this looks broken. Could you help to check it, many thx!

**Comment by mscbg** [comment]
Did you try devel branch？

**Comment by haosdent** [comment]
hi. thx @mscbg 's reply for devel branch, dpvs could not run when i using dpdk.conf.sample

**Comment by mscbg** [comment]
Did you use dpvs.conf in devel branch ? What error did it show?

**Comment by mscbg** [comment]
If your error is just like this, you should update your tools
![image](https://user-images.githubusercontent.com/20103281/51510012-466b1180-1e36-11e9-8478-14271b77f97c.png)

**Comment by haosdent** [comment]
ohoh, so only need to use the ipvsadmin for devel branch and keep rest code using master branch?

**Comment by mscbg** [comment]
I mean, if you use devel branch, ipvsadm should make/install from devel branch; if you use master branch , ipvsadm should make/install from master branch. You should not use dpvs from master/devel branch but ipvsadm from 1.6

**Comment by haosdent** [comment]
thx @mscbg , I rebuild 1.6 from a fresh env, it works Orz
