### ISSUE TITLE
ipvsadm --rate does not show counters

### ISSUE THREAD

**Issue by Tolyar** [iqiyi/dpvs#386]
On latest master branch sources ipvsadm --rate always show zero counters but --stats show correct information. For example:

--stats
TCP  VIP:https        2515932  125426K        0   13034M        0
sleep 1
TCP  VIP:https        2516461  125451K        0   13036M        0

--rate
TCP  VIP:https              0        0        0        0        0

On native system's IPVS ---rate works fine.

**Comment by ywc689** [comment]
Ipvsadm hasn’t support rate now.

**Comment by Tolyar** [comment]
Thank you. Closing issue.
