### ISSUE TITLE
keepalived健康检查间歇性失效,kni接口有tx dropped包

### ISSUE THREAD

**Issue by xrayou** [iqiyi/dpvs#457]
目前我们搭建3个集群，每个集群2台DPVS,3个集群都出现keepalived健康检查TCP_CHECK间歇性失效剔除现象
1、DPVS运行外部FNAT双臂模式（LAN不跑OSPF）通过bond1.kni配置IP进行健康检查，内部FNAT单臂模式（LAN与交换机跑OSPF）通过bond0.kni配置与互换机的互联IP进行健康检查（互联IP可通全网RIP），2种模式都有问题；
2、系统CentOS 7.3和CentOS 7.2都换过，也是同样的问题，但CentOS 7.2检查失效频率会低点；
3、1.6-1  1.7-2版本均有这种现象，dpvs bond网卡模式为mode 0，kni接口IP也配置在dpvs接口；
4、ipvsadm -G查看所有的LIP SAPOOL都正常配置的；
5、目前线上跑的RIP:RPORT条目约260多，目前测试跑的RIP:RPORT条目约900多；
6、两边抓包发现有端口复用情况，尝试过修改系统内核参数没有效果，RS关闭tcp_tw_recycle没有效果；
7、查看bond0.kni接口有TX  dropped 包且不断增长(不确认是否有关）；
8、DPVS上基于kni接口用ping及tcpping（探测端口)探测RS会有丢包和超时，内部其它服务器ping及tcpping（探测端口)探测RS则正常

**Comment by ywc689** [comment]
KNI TX performance problem. Fixed by pr #672.
