### ISSUE TITLE
TX descriptor number issues.

### ISSUE THREAD

**Issue by Shadowu410** [iqiyi/dpvs#46]
1. Does port->txq_desc_nb relates to the tx descriptor_number value of netif_defs in configuration file? If it does, the change of tx descriptor_number will NOT affect port->txq_desc_nb, since i set tx descriptor_number to 4096 and dpvs passes 128 to dpdk when setting up tx queues in netif_port_start() int netif.c file.

2. Passing 128 as tx  descriptor number to dpdk will cause problem to some device such as VMXNET3 NIC, since port->txq_desc_nb will be set as tx ring size to the device and VMXNET3 requires it in range 512-4096.

Refers to: http://dpdk.org/ml/archives/dev/2015-November/028809.html

**Comment by beacer** [comment]
For 1, yes, it's related to `descriptor_number`. We'll have a look.
For 2, we'll consider to change the default value.
