### ISSUE TITLE
单网卡在配置lip的是没问题，但是bond的情况下配置lip就抛异常

### ISSUE THREAD

**Issue by marchlhw** [iqiyi/dpvs#465]
单网卡在配置lip的是没问题，但是bond的情况下配置lip就抛异常，异常如下：
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of bond1 !

说明：dpvs版本1.7.2 dpdk版本17.11.2，试过intel x520和82599的网卡

**Comment by ywc689** [comment]
忽略bond设备的这个错误日志吧，这是正常的，bond设备没有实现获取 flow director信息的接口，不影响正常使用。
