### ISSUE TITLE
Connsync for fullnat mode

### ISSUE THREAD

**Issue by Dongsheng-LI** [iqiyi/dpvs#466]
we use dpvs to support L4 load balance from edge to the region. 
so fullnat is the only choice here, however connsync seems not support here
is there any plan for this feature

**Comment by ywc689** [comment]
Session sync for fullnat is very complicated, and not perfomance friendly.  we have not get up with efficient solution for this feature.  thus no plan for the feature yet, but we would continue to make efforts to get an effective solution.
