### ISSUE TITLE
几个dpvs问题

### ISSUE THREAD

**Issue by xmutcyq** [iqiyi/dpvs#467]
1、在fullnat-双臂模式下，dpvs在dpdk1开启kni时会报“NETIF: kni_send2kern_loop: fail to send pkts to kni”，该网口有开启vlan
2、在fullnat-双臂模式下，多个LB连接在同个交换机上通过ospf做负载均衡，且vip都配置在dpdk1上，dpvs是怎么关闭这些vip的arp公告的？

**Comment by ywc689** [comment]
该issue 搁置时间有点久了，不确定你是否已经解决。

问题1：应该是配置问题，请检查配置是否正确。
问题2：ospf 工作在三层，arp 工作在二层，两者不冲突，dpvs 没必要关闭vip的 arp 公告。
