### ISSUE TITLE
bond4配置问题

### ISSUE THREAD

**Issue by zeably** [iqiyi/dpvs#472]
官网上有说网卡已经支持bond4模式，但相关文档里面没有bond4相关的案例
求大神给个bond4的配置文

     <init> bonding bond0 {
        mode                    0    ---->  改成4  ？？？其它地方不动？？？
        slave                   dpdk0
        slave                   dpdk1
        primary                 dpdk0
        kni_name                bond0.kni
    }

**Comment by ywc689** [comment]
只需要把mode改成4即可。
