### ISSUE TITLE
Intel Xeon Gold 6230安装完DPVS无法启动

### ISSUE THREAD

**Issue by xrayou** [iqiyi/dpvs#486]
系统：Centos 7.6
CPU: Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
网卡：Intel(R) 2P X550

解决：
通过gdb调试发现，Intel Xeon Gold 6230超线程最大支持80核，DPVS代码DPVS_MAX_LCORE只支持64核，需要改成128再重装编译安装DPVS:

$vim /dpvs/src/config.mk
CFLAGS += -D DPVS_MAX_LCORE=128

$vim /dpvs/src/ctrl.c
#define MSG_MAX_LCORE_SUPPORTED 128
    if (slave_lcore_nb > 128) {
        RTE_LOG(ERR, MSGMGR, "%s: only %d lcores supported for ctrl\n", __func__, 128);

$vim /dpvs/tools/dpip/Makefile
DEFS = -D DPVS_MAX_LCORE=128

重新编译：
make clean
make 
make install

**Comment by ywc689** [comment]
DPVS supports 64 lcores at max. You can use one of the following EAL args when starting DPVS.
```
./dpvs -- -c COREMASK
./dpvs -- -l CORELIST
./dpvs -- --lcores COREMAP
```
