### ISSUE TITLE
DPVS_MPOOL: dpvs_mempool_get: mempool mp_msg_s32768_n32 full, allocate memory from heap!

### ISSUE THREAD

**Issue by snailq** [iqiyi/dpvs#494]
麻烦大神帮看下，这个报错，运行几分钟后dpvs进程就crash掉了，没有流量的情况下 不会出现。
相关配置不合理吗？dpvs version: 1.7-8    3.10.0-327.el7.x86_64
**dpvs.conf**

`netif_defs {
    <init> pktpool_size     1048575
    <init> pktpool_cache    256

ipvs_defs {
    conn {
        <init> conn_pool_size       2097152
        <init> conn_pool_cache      256
        conn_init_timeout           3
        ! expire_quiescent_template
        ! fast_xmit_close
        ! <init> redirect           off
    }

! sa_pool config
sa_pool {
    pool_hash_size   16
}`

**dpvs.log**

IFA: add 10.136.54.50 in ifa_add_set failed
MSGMGR: msg_slave_process:msg@0x7fff958be648, msg_type 30 callback failed on lcore 1
MSGMGR: msg_slave_process:msg@0x7fff958bfb88, msg_type 30 callback failed on lcore 7
MSGMGR: msg_slave_process:msg@0x7fff958bc008, msg_type 30 callback failed on lcore 5
MSGMGR: msg_slave_process:msg@0x7fff958a8e08, msg_type 30 callback failed on lcore 2
MSGMGR: msg_slave_process:msg@0x7fff958c1948, msg_type 30 callback failed on lcore 4
MSGMGR: msg_slave_process:msg@0x7fff9584fe48, msg_type 30 callback failed on lcore 3
MSGMGR: msg_slave_process:msg@0x7fff9584c708, msg_type 30 callback failed on lcore 6
MSGMGR: msg_slave_process:msg@0x7fff958825c8, msg_type 30 callback failed on lcore 8
DPVS_MPOOL: dpvs_mempool_get: mempool mp_msg_s32768_n32 full, allocate memory from heap!

**messages**

Nov  8 11:57:25 l-dpvs-cnc1 kernel: lcore-slave-8[12733]: segfault at 0 ip 000000000052e7d3 sp 00007ff7f0dfc140 error 6 in dpvs[400000+26c000]

Nov  8 11:57:26 l-dpvs-cnc1 abrt-server: Executable '/usr/src/dpvs-master/bin/dpvs' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Nov  8 11:57:26 l-dpvs-cnc1 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2019-11-08-11:57:25-12669' exited with 1

**Comment by ywc689** [comment]
DPVS_MPOOL的日志不是SEGFAULT的原因，内存的非法写错误触发了SEGFAULT，gdb 调试看看具体挂在什么函数里吧。

**Comment by ywc689** [comment]
"msg_type 30"消息类型不是dpvs标准版本注册的消息类型，该消息是否你们自己注册的？如果是，请使用“msg_reply_alloc/msg_reply_free”分配和释放响应消息内存。

**Comment by ywc689** [comment]
fixed in commit "mempool: fix memory underflow problem and add more debug info"
