### ISSUE TITLE
启动dpvs报错，另一个报错提示

### ISSUE THREAD

**Issue by xmjlong** [iqiyi/dpvs#50]
[root@localhost bin]# ./dpvs &
[1] 2902
[root@localhost bin]# EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:08:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
NETIF: worker cpu2:dpdk0 rx_queue_id += 1
NETIF: worker cpu2:dpdk0 tx_queue_id += 1
NETIF: worker cpu3:dpdk0 rx_queue_id += 2
NETIF: worker cpu3:dpdk0 tx_queue_id += 2
NETIF: worker cpu4:dpdk0 rx_queue_id += 3
NETIF: worker cpu4:dpdk0 tx_queue_id += 3
NETIF: worker cpu5:dpdk0 rx_queue_id += 4
NETIF: worker cpu5:dpdk0 tx_queue_id += 4
NETIF: worker cpu6:dpdk0 rx_queue_id += 5
NETIF: worker cpu6:dpdk0 tx_queue_id += 5
NETIF: worker cpu7:dpdk0 rx_queue_id += 6
NETIF: worker cpu7:dpdk0 tx_queue_id += 6
NETIF: worker cpu8:dpdk0 rx_queue_id += 7
NETIF: worker cpu8:dpdk0 tx_queue_id += 7
EAL: Error - exiting with code: 1
  Cause: [netif_lcore_init] bad lcore configuration (err=-5), exit ...

[1]+  Exit 1                  ./dpvs

**Comment by beacer** [comment]
1. How much NIC are bound to DPDK, show with `dpdk-devbind --st`. Is the DPDK NIC number match `/etc/dpvs.conf` ?
2. is the NIC supported by DPDK ? `http://dpdk.org/doc/nics`
3. Pls check README.md or `doc/tutialor.md` for examples.

**Comment by beacer** [comment]
The return value `-5` means DPDK NIC is not enough according to config file. It's possible the NIC is not supported by DPDK. Pls check the return value of `rte_eth_dev_count` in `check_lcore_conf`.
You can also run DPDK examples like `l2fwd` first to see if NIC works with DPDK.

**Comment by xmjlong** [comment]
my server's CPU core number is 8, and i find there are cpu0--cpu8 in /etc/dpvs.conf, so i Commented-Out cpu8 , like this:
#    <init> worker   cpu8 {
#        type        slave
#        cpu_id      8
#        port        dpdk0 {
#            rx_queue_ids     7
#            tx_queue_ids     7
#            ! isol_rx_cpu_ids  16
#            ! isol_rxq_ring_sz 1048576
#        }
#    }

and then it works
