### ISSUE TITLE
请问这是网卡不支持FDIR么？谢谢

### ISSUE THREAD

**Issue by cnshawncao** [iqiyi/dpvs#507]
日志：
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
NETIF: netif_mask_fdir_filter: Fail to fetch fdir info of dpdk0.317 !
IFA: add fd00:abcd:dc2:a018::10 in ifa_add_set failed

硬件：
Intel 82599ES 10G 网卡。

0000:02:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe

**Comment by hulinfan** [comment]
看起来你想配IPv6的 fdir，IXGBE不支持IPv6的perfect match，IPv6地址+加端口的fdir不生效的

**Comment by cnshawncao** [comment]
你这边有什么使用上的建议？目前采购网卡时间来不及了，估计要2周+。

**Comment by cnshawncao** [comment]
比如，怎么规避这个问题？

**Comment by hulinfan** [comment]
你这个应该是fullnat的部署模式，设置laddr的时候报的错，可以先忽略，并在配置文件打开redirect选项，通过软件的方式让回程的流命中源lcore

**Comment by cnshawncao** [comment]
启用redirect选项对应能有多大影响，和硬件fdir相比？

**Comment by ywc689** [comment]
10G网卡服务器如果能给DPVS 分配 6-8个 worker Core，打开redirect正常不会有丢包。
