### ISSUE TITLE
How to break the bottleneck of stand-alone ? About  “All Active No backup”  and “full utilization of scheduling resources” !

### ISSUE THREAD

**Issue by JermineHu** [iqiyi/dpvs#51]
DPVS is a great LB，Thank you very much for the DPVS provided by AIQIYI first！My question is the DPVS cluster can be an **“All Active No backup”** for **“full utilization of scheduling resources”** solution？ such as maglev ？

**Comment by beacer** [comment]
1. Sure, for **All Active**, `DPVS` support OSPF/ECMP cluster solution, pls refer `doc/tutorial.md` for further info.
2. What do yo mean "full utilization of scheduling resources", all Real Server should be scheduled ?
   We have different Scheduling algorithm, like RR, WLC, WRR, etc.

**Comment by JermineHu** [comment]
@beacer  Excellent！I will continue to focus on this project!
