### ISSUE TITLE
issue of svc/dest/laddr per-core support

### ISSUE THREAD

**Issue by flyinskyabc** [iqiyi/dpvs#524]
I got a error message when running 'ipvsadm -l'.
![image](https://user-images.githubusercontent.com/58936237/72432530-3defb180-37d2-11ea-8eb2-b6e19e80eb3a.png)

I traced it by gdb,  and found there is a service with two 'dests' on master lcore whereas the same service with only one 'dest' on slave lcores,  so got the error message above.

I checked the code,  but got confused. Why do operations asynchronously in 'dp_vs_set_svc'? As I know, 'keepalived' not support to load configurations asynchronously yet. 
![image](https://user-images.githubusercontent.com/58936237/72428925-b1d98c00-37c9-11ea-9260-e68e50d5a403.png)

I tested the scene below:
Firstly, I add the first 'dest' to a exist service, 'multicast_msg_send' return immediately after sent requests to all slave lcores, but do not wait for any replies,  and add 'dest' continuously on master lcore.  
Then, I add the second 'dest' ,  but get anther error message: 'repeated sequence number for multicast msg' because the previous message reply still in queue.
Finally, I run 'ipvsdam -l', and get the same message i mentions at the begining.

It seems like a bug.

**Comment by ywc689** [comment]
The async message for dpvs service/dest setting is a compromise for performance. DPVS  uses polling-based scheduler,  and  processes all jobs in a round-robin fashion. Sync message blocks other jobs, which may lead to packet loss, timer inaccuracy..... The mismatch problem is the negative effect of using aync message, but it's only a transient state when setting services/dests.
