### ISSUE TITLE
make dpvs-1.7-8

### ISSUE THREAD

**Issue by Hubonzi** [iqiyi/dpvs#531]
[root@dpvs01 dpvs-1.7-8]# make
for i in src tools; do make -C $i || exit 1; done
make[1]: Entering directory `/root/build/dpvs-1.7-8/src'
In file included from /root/build/dpvs-1.7-8/src/cfgfile.c:20:0:
/root/build/dpvs-1.7-8/src//../include/dpdk.h:20:24: fatal error: rte_common.h: No such file or directory
 #include <rte_common.h>
                        ^
compilation terminated.
\make[1]: *** [/root/build/dpvs-1.7-8/src/cfgfile.o] Error 1
make[1]: Leaving directory `/root/build/dpvs-1.7-8/src'
make: *** [all] Error 1

**Comment by Hubonzi** [comment]
> _No description provided._

**Comment by andrewhit** [comment]
Try the below steps under dpvs-1.7.8/src:
# make clean 
# make distclean 
# reboot -f
