### ISSUE TITLE
请问ipvsadm -G输出的内容里面CONFLICTS有什么特别含义吗？

### ISSUE THREAD

**Issue by welliamcao** [iqiyi/dpvs#538]
> $ ./ipvsadm  -G
VIP:VPORT            TOTAL    SNAT_IP              CONFLICTS  CONNS
10.0.0.100:80         1
                                            192.168.100.200      0          0

**Comment by ywc689** [comment]
`CONFLICTS` derives from Linux LVS. DPVS doesn't use it.
