### ISSUE TITLE
Compile keepalived error during build dpvs.

### ISSUE THREAD

**Issue by Darkczc** [iqiyi/dpvs#541]
system: Ubuntu 16.04.2 LTS
gcc：4.8.5
Error occur when `make `  in <path-to-dpvs>:
keepalived_netlink.c: In function ‘parse_af_spec’:
keepalived_netlink.c:1634:35: error: ‘IPV4_DEVCONF_ARP_IGNORE’ undeclared (first use in this function)
    ifp->arp_ignore = inet_devconf[IPV4_DEVCONF_ARP_IGNORE - 1];
                                   ^
keepalived_netlink.c:1634:35: note: each undeclared identifier is reported only once for each function it appears in
keepalived_netlink.c:1635:35: error: ‘IPV4_DEVCONF_ARPFILTER’ undeclared (first use in this function)
    ifp->arp_filter = inet_devconf[IPV4_DEVCONF_ARPFILTER - 1];
                                   ^
keepalived_netlink.c:1637:35: error: ‘IPV4_DEVCONF_RP_FILTER’ undeclared (first use in this function)
     ifp->rp_filter = inet_devconf[IPV4_DEVCONF_RP_FILTER - 1];
                                   ^
keepalived_netlink.c:1639:44: error: ‘IPV4_DEVCONF_PROMOTE_SECONDARIES’ undeclared (first use in this function)
    ifp->promote_secondaries = inet_devconf[IPV4_DEVCONF_PROMOTE_SECONDARIES - 1];
                                            ^
Makefile:373: recipe for target 'keepalived_netlink.o' failed
make[2]: *** [keepalived_netlink.o] Error 1

**Comment by jotde22** [comment]
I have the same issue with
Ubuntu 18.04.4 LTS
Kernel 4.15.0
gcc 7.5.0

As a workaround I have added the following lines at line 1091 in configure.ac (values from vrrp_if_config.c):
```
    AC_DEFINE([IPV4_DEVCONF_ARP_IGNORE], [ 1 ], [value from vrrp_if_config.c])
    AC_DEFINE([IPV4_DEVCONF_ACCEPT_LOCAL], [ 1 ], [value from vrrp_if_config.c])
    AC_DEFINE([IPV4_DEVCONF_RP_FILTER], [ 0 ], [value from vrrp_if_config.c])
    AC_DEFINE([IPV4_DEVCONF_ARPFILTER], [ 1 ], [value from vrrp_if_config.c])
    AC_DEFINE([IPV4_DEVCONF_PROMOTE_SECONDARIES], [ 1 ], [value from vrrp_if_config.c])
```

But actually, these parameters should be set while compiling vrrp_if_config.c. I don't know why it works with CentOS but not with Ubuntu.

**Comment by ywc689** [comment]
refer to issue #586
