### ISSUE TITLE
dpvs-1.8.2版本snat模式下无法加载keepalived配置

### ISSUE THREAD

**Issue by xrayou** [iqiyi/dpvs#542]
版本信息：
centos7.6
dpvs version: 1.8-2
Keepalived v2.0.19

ipvsadm报错：
# ipvsadm  -ln
IP Virtual Server version 0.0.0 (size=0)
[sockopt_msg_recv] errcode set in socket msg#202 header: msg callback failed(-23)
Success

keepalived日志：
#cat /var/log/keepalived.log
Misc check for [[100.100.100.100]:?:0 VS [`ʵ<U+052D>U]:?:0] by [/home/product/dpvs-1.8.2/scripts/ping.sh] succeeded.
Adding service [100.100.100.100]:?:0 to VS [@f<B5><U+052D>U]:?:0
IPVS: Operation not supported with specified address family
IPVS (cmd 1159, errno 97): Operation not supported with specified address family
Misc check for [[100.100.100.100]:tcp:0 VS [ ڵ<U+052D>U]:tcp:0] by [/home/product/dpvs-1.8.2/scripts/ping.sh] succeeded.
Adding service [100.100.100.100]:tcp:0 to VS [<A0>Y<B5><U+052D>U]:tcp:0
IPVS: Operation not supported with specified address family
IPVS (cmd 1159, errno 97): Operation not supported with specified address family

#配置样例
#keepalived.conf example:
virtual_server match  SNAT  {
    protocol TCP 
    delay_loop 3
    lb_algo rr
    lb_kind SNAT
    src-range  10.13.64.1-10.13.64.254
    oif bond0
    alpha
    omega
    quorum 1
    quorum_up "ip addr add 10.13.254.1/32 dev bond1.kni;"
    quorum_down "ip addr del 10.13.254.1/32 dev bond1.kni;"
    real_server 100.100.100.100 0 {
        weight 1
        MISC_CHECK {
            misc_path "/dpvs/scripts/ping.sh"
            misc_timeout 3
        }
    }
}

**Comment by ywc689** [comment]
fixed in [release v1.8.4](https://github.com/iqiyi/dpvs/releases)
