### ISSUE TITLE
Is it suitable for CGNAT?

### ISSUE THREAD

**Issue by torabkheslat** [iqiyi/dpvs#553]
Dears 

We're gonna to prepare a server to NAT our customers (in a private network) to pool of public ip addresses (CGNat - Carrier-grade NAT)

We find this repo for this suitable for our needs , Is it suitable for CGNAT?
If so  , please bring me a guideline.

thanks in advanced.

**Comment by ywc689** [comment]
I think you mean SNAT forwarding mode. DPVS support SNAT, refer to [tutorial doc](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#snat) for how to config SNAT forwarding with DPVS.
