### ISSUE TITLE
sant sapool error

### ISSUE THREAD

**Issue by zeably** [iqiyi/dpvs#56]
dpip addr add 172.20.2.122/24 dev dpdk0 sapool  
[sockopt_msg_recv] errcode set in socket msg#400 header: failed dpdk api(-11)
dpip: failed dpdk api

[root@dpvs bin]# MSGMGR: [sockopt_msg_send:msg#400] errcode set in sockopt msg reply: failed dpdk api

**Comment by beacer** [comment]
It seems you NIC not support Flow Director. For this kind of NIC, Full-NAT and SNAT mode are not supported. http://dpdk.org/doc/guides/nics/overview.html#id1

**Comment by zeably** [comment]
intel I350 是否可以有其它办法，让他支持 Flow Director 功能，还是说要买intel X710系列的网卡才可以

**Comment by beacer** [comment]
The `i350` uses `igb` driver (http://dpdk.org/doc/nics) which does not support flow director.
You can ask Intel for more info, or use the NICs support flow director.
The NICs drivers support flow director can be found in http://dpdk.org/doc/guides/nics/overview.html#id1
