### ISSUE TITLE
What is ipset and outwall route in DPVS?

### ISSUE THREAD

**Issue by hulinfan** [iqiyi/dpvs#564]
New feature is added in DPVS 1.7.8: 
https://github.com/iqiyi/dpvs/pull/487

One of which is:
- Simple ipset and outwall route for IPv4

There is no documentation about ipset.  I read the source code, and found that ipset is for SNAT whose dest is in the ip list. But it seems not so clear . Can you explain it and under what scenario should we use it?

**Comment by ywc689** [comment]
ipset & outwall is something like strategy routes in Linux. But it's a very simple version which enable only one another route table other than the default main route table.
