### ISSUE TITLE
性能数据为什么只有7个核

### ISSUE THREAD

**Issue by jlijian3** [iqiyi/dpvs#57]
E5-2650 v3双路cpu加起来有20个核了，为什么只有7个核的数据？
1600w pps不算高，我们内核版的lvs都跑到3000w pps了，用了32个核。

**Comment by beacer** [comment]
Is your NIC 25G or 40G ? we use 10G NIC. And will test 25G/40G next step.

**Comment by jlijian3** [comment]
I get it. We use 40G NIC.

**Comment by lvsgate** [comment]
You can use 2 x 10G nic, may be crossing numa node kill the performance?
