### ISSUE TITLE
存在长连接流量时更改keepalived.conf中laddr会导致 lcore 的 laddr 配置不一致

### ISSUE THREAD

**Issue by legend050709** [iqiyi/dpvs#575]
（1）问题
存在长连接流量时，keepalived.conf 中 laddr 存在更新（比如增加一个laddr ip）; keepalived 会先删除 laddr group, 再添加 laddr group；
底层dpvs 的 长连接所在的 lcore 在添加 laddr ip，设置 laddr 的 sapool 时，如果 laddr 刚好是 本 lcore上的长连接用到的 laddr ，则会由于设置 fdir filter 出错，导致设置 laddr 的 sapool 失败；
使用 dpip addr show dev lan -v 可以看到 lcore 间的 laddr 不一致；

（2）报错信息
May 18 16:40:02 : NETIF: dpdk_set_fdir_filt: fdir filt set failed for lan -- Invalid argument(-22)#012!
May 18 16:40:02 : IFA: [24] ifa_entry_add: add ifaddr 192.21.2.5 failed -- failed dpdk api
May 18 16:40:12 : IFA: ifaddr_get_stats: ifa naddr does not match -- master=6, slave[24]=5
May 18 16:40:14 : IFA: ifaddr_get_verbose: ifa naddr does not match -- master=6, slave[24]=5

**Comment by mscbg** [comment]
lip的修改不能在线操作。需要重启。

**Comment by ywc689** [comment]
`May 18 16:40:02 : IFA: [24] ifa_entry_add: add ifaddr 192.21.2.5 failed -- failed dpdk api`
 keepalived reload 时， dpdk fdir 接口因调用频率太高会报错，如果用 keepalived 配置 lip，建议在启动的时候配置好，启动后不要用 reload/restart keepalived 的方式更新 lip.
