### ISSUE TITLE
TC限速不成功，是我打开方式不对吗？

### ISSUE THREAD

**Issue by MangoDowner** [iqiyi/dpvs#582]
如题，有大佬成功限速过么...可否提供限速方法？

**Comment by MangoDowner** [comment]
好吧，要打开一些配置才可以，比如：
dpip link set tc-egress on

**Comment by xgfone** [comment]
我打开了 TC 功能（在同一块网卡同时开启了 `tc_ingress` 和 `tc_egress`），只要一添加 `dpip cls` 规则，HTTP访问立即中断；只要删除所有 `dpip cls`规则，只保留`dpip qsch`，规则，HTTP访问立即恢复。

哪位大佬知道原因吗？求教！

**Comment by MangoDowner** [comment]
你应该再开个issue提问，这个issue被关闭了,可能没什么人关注了
