### ISSUE TITLE
dpvs compiling error iftraf.c:388:5: error: this ‘if’ clause does not guard

### ISSUE THREAD

**Issue by vincentmli** [iqiyi/dpvs#585]
I am trying to compile and install dpvs in Ubuntu 18.04 with gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0.  it errors out with :
<pre>
make[1]: Entering directory '/usr/src/dpvs/src'
  cfgfile.o
  common.o
  ctrl.o
  debug.o
  global_conf.o
  global_data.o
  icmp.o
/usr/src/dpvs/src/iftraf.c: In function ‘iftraf_sockopt_get’:
/usr/src/dpvs/src/iftraf.c:388:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (!conf || size < sizeof(struct dp_vs_iftraf_conf) || !out || !outsize)
     ^~
/usr/src/dpvs/src/iftraf.c:390:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  cf = conf;
  ^~
/usr/src/dpvs/src/iftraf.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-stringop-truncation’ [-Werror]
cc1: all warnings being treated as errors
Makefile:74: recipe for target '/usr/src/dpvs/src/iftraf.o' failed
make[1]: *** [/usr/src/dpvs/src/iftraf.o] Error 1
make[1]: Leaving directory '/usr/src/dpvs/src'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 1

</pre>

any idea?

**Comment by vincentmli** [comment]
ok, indentation is the problem, correct it:

<pre>
diff --git a/src/iftraf.c b/src/iftraf.c
index cb3c024..ca06b08 100644
--- a/src/iftraf.c
+++ b/src/iftraf.c
@@ -387,7 +387,7 @@ int iftraf_sockopt_get(sockoptid_t opt, const void *conf, size_t size,
 
     if (!conf || size < sizeof(struct dp_vs_iftraf_conf) || !out || !outsize)
         return EDPVS_INVAL;
-       cf = conf;
+    cf = conf;
 
     if (cf && strlen(cf->ifname)) {
         port = netif_port_get_by_name(cf->ifname);
</pre>

**Comment by anshulthakur** [comment]
The issue seems to have cropped up as of the latest commit. 

https://github.com/iqiyi/dpvs/blob/7357bf5ab7ab8ca597d8a841833f14b7658afe8d/src/iftraf.c#L390
