### ISSUE TITLE
keepalived_netlink.c:1634:35: error: ‘IPV4_DEVCONF_ARP_IGNORE’ undeclared

### ISSUE THREAD

**Issue by vincentmli** [iqiyi/dpvs#586]
keepalived compiling error:
<pre>

keepalived_netlink.c: In function ‘parse_af_spec’:
keepalived_netlink.c:1634:35: error: ‘IPV4_DEVCONF_ARP_IGNORE’ undeclared (first use in this function); did you mean ‘HAVE_DECL_IPV4_DEVCONF_ARP_IGNORE’?
    ifp->arp_ignore = inet_devconf[IPV4_DEVCONF_ARP_IGNORE - 1];
                                   ^~~~~~~~~~~~~~~~~~~~~~~
                                   HAVE_DECL_IPV4_DEVCONF_ARP_IGNORE
keepalived_netlink.c:1634:35: note: each undeclared identifier is reported only once for each function it appears in
keepalived_netlink.c:1635:35: error: ‘IPV4_DEVCONF_ARPFILTER’ undeclared (first use in this function); did you mean ‘IPV4_DEVCONF_ARP_IGNORE’?
    ifp->arp_filter = inet_devconf[IPV4_DEVCONF_ARPFILTER - 1];
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   IPV4_DEVCONF_ARP_IGNORE
keepalived_netlink.c:1637:35: error: ‘IPV4_DEVCONF_RP_FILTER’ undeclared (first use in this function); did you mean ‘IPV4_DEVCONF_ARPFILTER’?
     ifp->rp_filter = inet_devconf[IPV4_DEVCONF_RP_FILTER - 1];
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   IPV4_DEVCONF_ARPFILTER
keepalived_netlink.c:1639:44: error: ‘IPV4_DEVCONF_PROMOTE_SECONDARIES’ undeclared (first use in this function); did you mean ‘IPV4_DEVCONF_ARP_IGNORE’?
    ifp->promote_secondaries = inet_devconf[IPV4_DEVCONF_PROMOTE_SECONDARIES - 1];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                            IPV4_DEVCONF_ARP_IGNORE
Makefile:373: recipe for target 'keepalived_netlink.o' failed
make[4]: *** [keepalived_netlink.o] Error 1
make[4]: Leaving directory '/usr/src/dpvs/tools/keepalived/keepalived/core'
Makefile:584: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/usr/src/dpvs/tools/keepalived/keepalived'
Makefile:427: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/dpvs/tools/keepalived'
Makefile:24: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/usr/src/dpvs/tools'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 1
</pre>

**Comment by vincentmli** [comment]
this is on Ubuntu 18.04

**Comment by vincentmli** [comment]
I copied from linux/ip.h and added an header file in the keepalived source directory,  and included the header file in keepalived_netlink.c to workaround the problem, let me know if there is better way to do it:

cat tools/keepalived/keepalived/include/vrrp_ip.h
<pre>

/* index values for the variables in ipv4_devconf */
enum
{
        IPV4_DEVCONF_FORWARDING=1,
        IPV4_DEVCONF_MC_FORWARDING,
        IPV4_DEVCONF_PROXY_ARP,
        IPV4_DEVCONF_ACCEPT_REDIRECTS,
        IPV4_DEVCONF_SECURE_REDIRECTS,
        IPV4_DEVCONF_SEND_REDIRECTS,
        IPV4_DEVCONF_SHARED_MEDIA,
        IPV4_DEVCONF_RP_FILTER,
        IPV4_DEVCONF_ACCEPT_SOURCE_ROUTE, 
        IPV4_DEVCONF_BOOTP_RELAY,
        IPV4_DEVCONF_LOG_MARTIANS,
        IPV4_DEVCONF_TAG,
        IPV4_DEVCONF_ARPFILTER,
        IPV4_DEVCONF_MEDIUM_ID,
        IPV4_DEVCONF_NOXFRM,
        IPV4_DEVCONF_NOPOLICY,
        IPV4_DEVCONF_FORCE_IGMP_VERSION,
        IPV4_DEVCONF_ARP_ANNOUNCE,
        IPV4_DEVCONF_ARP_IGNORE,
        IPV4_DEVCONF_PROMOTE_SECONDARIES,
        IPV4_DEVCONF_ARP_ACCEPT,
        IPV4_DEVCONF_ARP_NOTIFY,
        IPV4_DEVCONF_ACCEPT_LOCAL,
        IPV4_DEVCONF_SRC_VMARK, 
        IPV4_DEVCONF_PROXY_ARP_PVLAN,
        IPV4_DEVCONF_ROUTE_LOCALNET,
        IPV4_DEVCONF_IGMPV2_UNSOLICITED_REPORT_INTERVAL,
        IPV4_DEVCONF_IGMPV3_UNSOLICITED_REPORT_INTERVAL,
        IPV4_DEVCONF_IGNORE_ROUTES_WITH_LINKDOWN,
        IPV4_DEVCONF_DROP_UNICAST_IN_L2_MULTICAST,
        IPV4_DEVCONF_DROP_GRATUITOUS_ARP,
        __IPV4_DEVCONF_MAX
};
</pre>

**Comment by wangxp006** [comment]
我在内核4.19.90   gcc版本7.3.0  编译dpvs的master代码 遇到了同样的问题，这个问题一直没有修复么。

**Comment by wangxp006** [comment]
@ywc689 如果需要复现，可以使用openEuler 的20.03 LTS版，下载地址https://openeuler.org/zh/download.html

**Comment by ywc689** [comment]
OK. We'll try to reproduce it on Unbuntu Vm first.

**Comment by SimonCZW** [comment]
My simple solution:

```
---
 tools/keepalived/configure.ac | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tools/keepalived/configure.ac b/tools/keepalived/configure.ac
index 3f19553..74d135d 100644
--- a/tools/keepalived/configure.ac
+++ b/tools/keepalived/configure.ac
@@ -1070,7 +1070,7 @@ AM_CONDITIONAL([BUILD_GENHASH], [test $BUILD_GENHASH = Yes])

 dnl ----[ Check for IPv4 devconf netlink support ]----
 IPV4_DEVCONF=No
-if test .$enable_vrrp != .no; then
+if test .$enable_vrrp = .no; then
   dnl ----[Check have IPV4_DEVCONF defines - since Linux 3.11]----
   SAV_CPPFLAGS="$CPPFLAGS"
   CPPFLAGS="$CPP_FLAGS $kernelinc"
--
```

**Comment by azura27** [comment]
The phenomenon is result from the macro definition's difference of linux/ip.h HEADER file different systems.
--in Ubuntu there are definition of IPV4_DEVCONF_ARP_IGNORE&IPV4_DEVCONF_ACCEPT_LOCAL & IPV4_DEVCONF_RP_FILTER& IPV4_DEVCONF_ARPFILTER, but not in CentOS
-- thus IPV4_DEVCONF is OFF in CentOS, ON in Ubuntu

a simple solution is to delete the block of "if test .$enable_vrrp != .no; then" in /tools/keepalived/configure.ac

**Comment by phonzia** [comment]
ubuntu 20.04, gcc-9.3.0 虚拟机上碰到了同样的问题

**Comment by fallenwood** [comment]
same issue, on debian 10 buster amd64, hyper-v

**Comment by jesson1** [comment]
same issue on centos7.4 amd64  kvm
