### ISSUE TITLE
不支持虚拟机？

### ISSUE THREAD

**Issue by pingliu** [iqiyi/dpvs#59]
请问下，这个是不支持虚拟机？只能跑在物理机器上？

**Comment by beacer** [comment]
DPVS (or DPDK) support VM, but pls note if the resource is enough (CPU cores, memory ...), as well as NIC compatible issues. If memory is not enough or NIC is not compatible DPDK or not support flow director, DPVS cannot be used.
DPVS is used for the case where high performance needed (e.g., 100M+ connection, 10M+ pps, 10G bps, or more), to use VM with limited CPU/memory is not good use case I think.

**Comment by beacer** [comment]
Pls check the `tutorial.md` for launching `DPVS` on Ubuntu VM.
