### ISSUE TITLE
dpvs 支持vxlan型组网的探讨

### ISSUE THREAD

**Issue by wangxp006** [iqiyi/dpvs#604]
Hi，各位大佬，当前计划向社区贡献支持vxlan型组网的实现，先大概描述下价值和大概的实现，看看是否可以接纳,如果OK的话，后续我会把代码提上来。

需求价值
1. 对于云场景，租户之间需要进行vxlan的隔离
2. 公私网之间IP协议族不一致的情况，使用Vxlan进行封装。

大概实现
1. 在发送报文时的vxlan hdr的封装、接收报文时的解封装
2.  封装、解封装后可能引起的报文的分片、聚合.

**Comment by ywc689** [comment]
vxlan 需求没有问题，欢迎贡献这部分功能代码。关于该功能的实现，有如下建议：

1. 尽量实现比较完整的vxlan功能，包括vxlan接口设备和协议，可以参考linux kernel vxlan 实现和 dpvs gre 实现。
2. 实现要考虑多核场景的性能问题，尽可能避免使用锁。

**Comment by SimonCZW** [comment]
Could you describe how to implement vxlan packet lockless?

**Comment by panzhengyu** [comment]
VIP是内网IP吗，云场景怎么隔离啊

**Comment by wangxp006** [comment]
由于工作原因，暂时无法投入该功能的开发，后续有空再reopen

**Comment by luzhongzhou** [comment]
> VIP是内网IP吗，云场景怎么隔离啊
@panzhengyu 请问有方案吗，可以讨论下
