### ISSUE TITLE
Stop dereferencing DPDK log internal

### ISSUE THREAD

**Issue by david-marchand** [iqiyi/dpvs#613]
*Disclaimer* I am unsure of what version of DPDK is in use in the project. So you might as well ignore this if you are still using a 18.11 version.

Starting 20.11, the rte_logs symbol will be removed from the export list, as announced in the past: https://git.dpdk.org/dpdk/commit/?id=e4c36e84566ede5bb2fa9c467f9d55f74901e908
Accessors have been added in previous releases and should be simple drop-in replacements for the current uses I saw in src/log.c.

**Comment by ywc689** [comment]
DPVS is using DPDK 18.11 now.
DPDK 20.11 is excpected to be LTS, and DPVS plans to upgrade to use it.  We will do some adaptation work then.

**Comment by david-marchand** [comment]
No problem.
If you can confirm the existing accessors will fit your needs, that would be great.

I am fine with closing this "issue", my main point was to give a heads-up.
