### ISSUE TITLE
添加对AWS平台ENA驱动的支持

### ISSUE THREAD

**Issue by davidshtian** [iqiyi/dpvs#624]
测试在AWS平台上使用EC2部署dpvs，在启动时会报如下错误：

```
EAL: Error - exiting with code: 1
  Cause: No dpdk ports found!
Possibly nic or driver is not dpdk-compatible.
```
后经调查发现是原因是dpvs默认没有添加ENA网卡驱动的参数，而ENA本身是受DPDK支持的，可以参考 [DPDK网卡支持列表](https://core.dpdk.org/supported/) 和 [驱动支持列表](http://doc.dpdk.org/guides/nics/overview.html)。

解决方法是修改src/dpdk.mk文件，添加ena参数-lrte_pmd_ena再重新编译。
```
LIBS += -Wl,--no-as-needed -fvisibility=default \
        -Wl,--whole-archive -lrte_pmd_vmxnet3_uio -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_ena \
...
```

**Comment by ywc689** [comment]
你应该已经修复了这个问题：https://github.com/iqiyi/dpvs/pull/625。这个 Issue 先关了。
