### ISSUE TITLE
ipvsadm --add-laddr报错

### ISSUE THREAD

**Issue by NicoSpec** [iqiyi/dpvs#63]
./ipvsadm --add-laddr -z 私网IP -t 公网IP:80 -F dpdk0
MSGMGR: [sockopt_msg_send:msg#400] errcode set in sockopt msg reply: failed dpdk api
[sockopt_msg_recv] errcode set in socket msg#400 header: failed dpdk api(-11)

**Comment by beacer** [comment]
Is the NIC support Flow Director ? If not, FullNAT and SNAT mode cannot be used.
http://dpdk.org/doc/nics
http://dpdk.org/doc/guides/nics/overview.html#id1

**Comment by NicoSpec** [comment]
谢谢，我们的网卡是I350，不支持Flow Director
