### ISSUE TITLE
netif.c 2239行rte_pktmbuf_adj失败时是否忘记释放mbuf

### ISSUE THREAD

**Issue by ahuzjx** [iqiyi/dpvs#636]
if (unlikely(NULL == rte_pktmbuf_adj(mbuf, sizeof(struct ether_hdr))))
        return EDPVS_INVPKT;

**Comment by ywc689** [comment]
是的。我们后续会修复这个BUG，或者您可以提交一个PR 修复该问题。

**Comment by ywc689** [comment]
这个问题已在 Pr #615 中修复。
