### ISSUE TITLE
keepalived checker_queue很大的时候reload 关闭healthychecker子进程导致服务被关闭

### ISSUE THREAD

**Issue by silveric10** [iqiyi/dpvs#650]
你好，当我vip和vip的服务端口比较多的时候(checker_queue > CHECKERS_CHILD_NUM_MAX) , healthy_checker的进程会新启一个。正常第一次起来是没问题的，但是当我reload keepalived的时候发现reload_check_thread里面会杀掉同一个group id的新起的那个healthy_checker进程，这样就会导致所有服务全部被shutdown了，请问这样算是什么问题？

截了一部分log在下面

> Aug 28 18:20:59 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8594]:0
> Aug 28 18:20:59 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8595]:0
> Aug 28 18:20:59 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8595]:0
> Aug 28 18:20:59 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8596]:0
> Aug 28 18:20:59 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8596]:0
> Aug 28 18:21:22 w-test01 Keepalived[10765]: Reloading ...
> Aug 28 18:21:22 w-test01 Keepalived[10765]: Opening file '/etc/keepalived/keepalived.conf'.
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10766]: Reloading
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10766]: Got SIGHUP, reloading checker configuration
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10766]: Child process 10765 in our process group 10765
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_80]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_80]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10766]: Opening file '/etc/keepalived/keepalived.conf'.
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8000]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8000]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8001]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8001]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8002]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8002]:0
> Aug 28 18:21:22 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8003]:0
。。。
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8694]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8695]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8695]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8696]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8696]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8697]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8697]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8698]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8698]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8699]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8699]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.102]:tcp:80 (unset,dead) from VS [vip_group_1_8700]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Shutting down service [172.24.0.103]:tcp:80 (unset,dead) from VS [vip_group_1_8700]:0
> Aug 28 18:21:23 w-test01 Keepalived_healthcheckers[10771]: Stopped
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Starting Healthcheck child process, pid=10817
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_80]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_80]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8000]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8000]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8001]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8001]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8002]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8002]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8003]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8003]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8004]:0
。。。

> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8155]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8156]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8156]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.102]:tcp:80 for VS [vip_group_1_8157]:0
> Aug 28 18:21:25 w-test01 Keepalived_healthcheckers[10766]: Activating healthchecker for service [172.24.0.103]:tcp:80 for VS [vip_group_1_8157]:0

当最后日志里显示全部active的时候，ipvsadm -Ln里面显示却是空的，一个vip没有

**Comment by ywc689** [comment]
v1.8.4 keepalived 有个遗留的bug，最多支持1K个 RS的健康检查。我们已经修复，请用最新 devel 分支代码验证看看。

**Comment by DavidLeeUX** [comment]
> v1.8.4 keepalived 有个遗留的bug，最多支持1K个 RS的健康检查。我们已经修复，请用最新 devel 分支代码验证看看。

哪个commit ，解决的 ？

**Comment by ywc689** [comment]
commit d0abf73a4bba896bd7d7df9719f510239b65b051

**Comment by huxiaoning1990** [comment]
> commit [d0abf73](https://github.com/iqiyi/dpvs/commit/d0abf73a4bba896bd7d7df9719f510239b65b051)

这个代码有bug，keepalived stop的时候，通过ipvsadm -ln查看里面的数据不会清理掉，当有很多端口的配置项reload的到一个很少端口的配置项时，ipvsadm -ln里面还有老的端口的残留
