### ISSUE TITLE
when i compile the dpvs ,i suffer "OPENSSL_init_crypto" in keepalived,how can i do it ?

### ISSUE THREAD

**Issue by beckhamaaa** [iqiyi/dpvs#653]
**my os :ubuntu 16.04 server**

make log:
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/usr/local/dpvs/tools/keepalived/keepalived/etc'
make[4]: Leaving directory '/usr/local/dpvs/tools/keepalived/keepalived/etc'
make[4]: Entering directory '/usr/local/dpvs/tools/keepalived/keepalived'
  CCLD     keepalived
check/libcheck.a(check_ssl.o): In function `build_ssl_ctx':
/usr/local/dpvs/tools/keepalived/keepalived/check/check_ssl.c:77: undefined reference to `OPENSSL_init_crypto'
/usr/local/dpvs/tools/keepalived/keepalived/check/check_ssl.c:92: undefined reference to `TLS_method'
check/libcheck.a(check_ssl.o): In function `ssl_connect':
/usr/local/dpvs/tools/keepalived/keepalived/check/check_ssl.c:235: undefined reference to `BIO_up_ref'
/usr/local/dpvs/tools/keepalived/keepalived/check/check_ssl.c:236: undefined reference to `SSL_set0_rbio'
/usr/local/dpvs/tools/keepalived/keepalived/check/check_ssl.c:237: undefined reference to `SSL_set0_wbio'

**my config.log:**
# cat config.log |grep OPENSSL_init_crypto
configure:7920: checking for OPENSSL_init_crypto
ac_cv_func_OPENSSL_init_crypto=yes

how can i do it ? thanks a lot!

**Comment by ywc689** [comment]
Maybe openssl-devel is not installed in your environment.
