### ISSUE TITLE
无法正常对RS服务进行健康检查

### ISSUE THREAD

**Issue by NiDaYeHa** [iqiyi/dpvs#66]
TCP_CHECK {
      nb_sock_retry 2
      connect_timeout 3
      connect_port 80
     }
对RS进行健康检查。RS服务器正常，却无法加入到LVS的集群里面

**Comment by NiDaYeHa** [comment]
重启了下DPDK，健康检查的时候，RS服务不正常，却依然在LVS的集群里面

**Comment by beacer** [comment]
What do you mean "not be added to" or "still in LVS cluster" ? `Keepalived` just change the `weight` for RSs to enable/disable them, instead of add/remove RSs. Do you mean when RS is not available, it's weight is still not zero ?

**Comment by NiDaYeHa** [comment]
经过多次实验出现过有两种情况：
1. RS is not available, it's weight is still not zero 
2. RS is available, it's weight is still zero

**Comment by NiDaYeHa** [comment]
![image](https://user-images.githubusercontent.com/34677780/34249629-57d43d56-e675-11e7-9ed3-73a1dedc21cc.png)

**Comment by beacer** [comment]
Ok pls show keepalived and dpvs related logs in `/var/log/message`. 
BTW, `keepalived` just check if TCP port is listening on RS, instead of any HTTP access.
For example,
```
Dec 21 17:34:33 10 Keepalived_healthcheckers[10735]: TCP connection to [10.15.204.50]:80 failed !!!
Dec 21 17:34:33 10 Keepalived_healthcheckers[10735]: Disabling service [10.15.204.50]:80 from VS
```

**Comment by beacer** [comment]
I tested locally, it works. The RS weight changes as expected and the log is also ok.

**Comment by NiDaYeHa** [comment]
第二种情况的日志：RS is available, it's weight is still zero
![image](https://user-images.githubusercontent.com/34677780/34250820-0bb4547a-e679-11e7-8635-a10437e0f549.png)

**Comment by NiDaYeHa** [comment]
Dec 21 17:34:33 10 Keepalived_healthcheckers[10735]: TCP connection to [10.15.204.50]:80 failed !!!
Dec 21 17:34:33 10 Keepalived_healthcheckers[10735]: Disabling service [10.15.204.50]:80 from VS
就是这种情况，用的是tcp检查端口

**Comment by NiDaYeHa** [comment]
健康检查的时候，是用DPDK的网卡对RS进行检查的吗？还是普通的网卡？

**Comment by beacer** [comment]
Not DPDK NIC, you need config kni device with IP for keepalived.

**Comment by NiDaYeHa** [comment]
找到问题了，dpdk的网段和正常网卡的网段是不能互通的。所以检测RS认为not available状态
