### ISSUE TITLE
支持Nginx1.19.0版本？

### ISSUE THREAD

**Issue by test-demo2020** [iqiyi/dpvs#663]
支持Nginx-1.19.0吗？

**Comment by ywc689** [comment]
不确定你说的支持是哪方面。
1. DPVS是四层负载均衡器，nginx 作为 DPVS 的 backend 是支持的。
2. 对于 FullNAT 转发，如果要在 backend 上获取源 IP， 需要 安装 TOA 内核模块。
3. 如果是 NAT64 转发，nginx 需要 patch以支持TOA功能， 我们提供了 nginx1.14.0的 [NAT64 patch](https://github.com/iqiyi/dpvs/tree/devel/kmod/toa/example_nat64)，其它版本可以参考这个patch 适配。

**Comment by test-demo2020** [comment]
现在用的就是1.14.0版本的，想找个适配最新的因为1.14.0版本的nginx 存在https 漏洞 。我不懂C语言。。。

>

**Comment by test-demo2020** [comment]
参考的这里:https://blog.csdn.net/weixin_39961559/article/details/87935873

**Comment by furyamber** [comment]
后端是java程序，能支持用toa获取到tcp option里的源IP啊，死活不能获取啊，后端是nginx能正常获取到

**Comment by test-demo2020** [comment]
> 后端是java程序，能支持用toa获取到tcp option里的源IP啊，死活不能获取啊，后端是nginx能正常获取到
等待作者更新下吧，现在dpvs 中获取IPV6 也是需要toa支持的，如果k8s中用nginx-ingress 用起来需要改好多。

**Comment by furyamber** [comment]
感谢楼上的，不过这个好想跟dpvs没关系把，我四层代理负载均衡用的lvs+fullnat,后端用的华为云上提供的编译出来toa.ko。后端是nginx就能获取，后端是java程序就获取不了。 阿里云上的toa也试过 好像也不行。  你这个toa模块是从哪里获取到的

**Comment by test-demo2020** [comment]
> 感谢楼上的，不过这个好想跟dpvs没关系把，我四层代理负载均衡用的lvs+fullnat,后端用的华为云上提供的编译出来toa.ko。后端是nginx就能获取，后端是java程序就获取不了。 阿里云上的toa也试过 好像也不行。 你这个toa模块是从哪里获取到的

我用的是：
    作者提供了 nginx1.14.0的 NAT64 patch，我现在想在1.19.0使用这个功能。并且想在nginx-ingress上也支持这个

**Comment by hroost** [comment]
Would be cool if dpvs will support proxy protocol. Nginx can natively retrieve original IP with that. See also https://github.com/iqiyi/dpvs/issues/207

**Comment by ywc689** [comment]
> Would be cool if dpvs will support proxy protocol. Nginx can natively retrieve original IP with that. See also #207

Proxy protocol was supported by pr #634 and in review now.
