### ISSUE TITLE
ospf/bgp ecmp 路由流量与业务流量隔离 后期有计划支持吗？

### ISSUE THREAD

**Issue by sjaliang** [iqiyi/dpvs#665]
在基于ospf/bgp ecmp实现的dpvs ha方案中，ospf/bgp路由流量与业务流量是混在一起 使用相同的cpu来处理，在业务流量较大的场景下  存在路由流量延迟较大 导致dpvs节点运行的quagga 与接入leaf硬件交换机之间的ospf/bgp邻居关系异常  dpvs上的vip 路由器信息无法对外发布的风险

**Comment by ywc689** [comment]
ospf/bgp流量走kni接口，pr #601 可以解决这个问题，我们后续会accept这个patch。

**Comment by donghaobo** [comment]
流量特别大的情况，需要在网卡上对协议报文做分流，将协议报文分发到独立的队列，这样才可能不丢包。目前还没有人这么做。设备打满不是一个合理的情况，扩容才是解决方式。

**Comment by ywc689** [comment]
pr #672 已解决了 kni 隔离的问题。
