### ISSUE TITLE
感觉文档精简 对上手门槛比较高 

### ISSUE THREAD

**Issue by tianya1993** [iqiyi/dpvs#673]

**Comment by ywc689** [comment]
DPVS 文档要求有一定的网络和负载均衡背景知识，后续我们会更新文档，但不可能做到细致入微。如有问题，可以申请假如DPVS交流微信群和大家交流。

**Comment by beckhamaaa** [comment]
谢谢，我怎么加入dpvs微信交流群？

**Comment by ywc689** [comment]
> 谢谢，我怎么加入dpvs微信交流群？

请参考 Issue #147
