### ISSUE TITLE
The  dpvs is not runing

### ISSUE THREAD

**Issue by tianya1993** [iqiyi/dpvs#678]
env :

i have  a Centos VM  ,nic  is  Red Hat, Inc Virtio network device， 

[root@localhost bin]# lspci |grep Eth
00:03.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:06.0 Ethernet controller: Red Hat, Inc Virtio network device
00:07.0 Ethernet controller: Red Hat, Inc Virtio network device
[root@localhost bin]# uname  -r
3.10.0-693.el7.x86_64
[root@localhost bin]# cat  /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@localhost bin]# ./dpvs  -v
dpvs version: 1.8-4, build on 2020.11.10.23:20:44
[root@localhost bin]# ls
dpip  dpvs  ipvsadm  keepalived
[root@localhost bin]# cd  ..
[root@localhost dpvs]# ls
bin		 core.29864	      kmod	     patch	src
conf		 doc		      LICENSE.GPLv2  pic	test
CONTRIBUTING.md  dpdk-18.11.2.tar.xz  LICENSE.md     README.md	tools
core.29796	 include	      Makefile	     scripts

log 
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:07.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
DPVS: dpvs version: 1.8-4, build on 2020.11.10.23:20:44
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 1
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
[ 2667.268430] rte_kni: kni_net_process_request: wait_event_interruptible timeout
linux_set_if_mac: fail to set dpdk0.kni's MAC address: Timer expired
IPSET: ipset_init: lcore 2: nothing to do.
IPSET: ipset_init: lcore 3: nothing to do.
IPVS: dp_vs_conn_init: lcore 2: nothing to do.
IPVS: dp_vs_conn_init: lcore 3: nothing to do.
[ 2670.281994] rte_kni: kni_net_process_request: wait_event_interruptible timeout
Segmentation fault (core dumped)

**Comment by ywc689** [comment]
It's suggested that DPVS run on physical server rather than VM.
If you are using VM to test DPVS, make sure that your VM  satisfies the following requirements.
* 2 cores at least, one for master, another for slave worker.
* 8GB memory,
* virtual nic supports flow director, configure one worker only if not.

In case of core dump, you could enable the DEBUG flag in src/Makefile and `gdb` it. Many more clues may be found then.
