### ISSUE TITLE
dpvs是否支持centos 6.x以及支持dpdk中的bond口

### ISSUE THREAD

**Issue by saga1015** [iqiyi/dpvs#68]
rt
还请大神解惑呀。
如果dpvs目前就支持centos 7.x，是不是dpvs跟kernel的版本有关联

**Comment by beacer** [comment]
1. DPVS does not support CentOS 6 because the keepalived/ipvsadm compatible issue.
2. and DPVS **do** support DPDK bond. pls check the doc for setting up the bonding interface.

**Comment by beacer** [comment]
I think your 2 questions are answered, so I'll close this issue. If you still have any problem, pls feel free to reopen or create new issues as needed.
