### ISSUE TITLE
TCP_OPT_TIMESTAMP

### ISSUE THREAD

**Issue by glennWang** [iqiyi/dpvs#681]
https://github.com/iqiyi/dpvs/blob/master/include/ipvs/proto_tcp.h#L46

请问大佬，

tsval 单位是纳秒，且是一个占4个字节的数字，最大能盛放 4,294,967,295 纳秒 （4秒多）

不应该是当前时刻吗？

没明白生成 tsval 时，为什么要这样计算 ？

`((tm_spec).tv_sec % 100) * 1000000 +   ((tm_spec).tv_nsec / 1000)`

**Comment by ywc689** [comment]
以上计算方式是将时间单位转换成微秒。
