### ISSUE TITLE
fnat laddr 数量能超过核数吗？

### ISSUE THREAD

**Issue by DavidLeeUX** [iqiyi/dpvs#682]
在配置laddr时，发现laddr超过了配置的核数，就有不通的现象？

**Comment by ywc689** [comment]
laddr 和核数没有直接关系，但 laddr 的 sapool 需要较多内存，如果 laddr 数量多可能因内存不足导致配置失败。如果你在用最新的代码，你可以用 `dpip addr show -s -v` 查看每个核上的 laddr 配置情况。

**Comment by DavidLeeUX** [comment]
![image](https://user-images.githubusercontent.com/16267902/99213084-a8fd8080-2807-11eb-9601-fde17337b129.png)
@ywc689  为什么不是所有的laddr使用连接， 是需要哪里做设置吗？

**Comment by ywc689** [comment]
请检查DPVS内存是否充足。

**Comment by DavidLeeUX** [comment]
内存足够

KiB Mem : 65681380 total, 47600072 free, 17278252 used,   803056 buff/cache
KiB Swap:  8388604 total,  8388604 free,        0 used. 48011336 avail Mem

**Comment by ywc689** [comment]
`dpip addr show -s -v` 查看是不是所有local IP都分配了 sapool

**Comment by DavidLeeUX** [comment]
valid_lft forever preferred_lft forever sa_used 0 sa_free 0 sa_miss 0
这是不是没有分配到？  给每个lip 分配sapool 是哪一项配置？

**Comment by ywc689** [comment]
lip 数量太多了，dpvs 分配的内存不够用了。减少lip数量试试吧。
