### ISSUE TITLE
EAL: Error - exiting with code: 1   Cause: Cannot init mbuf pool on socket 1

### ISSUE THREAD

**Issue by SpiritComan** [iqiyi/dpvs#69]
[root@localhost bin]# ./dpvs &
[1] 3718
EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f rte_em_pmd
EAL: PCI device 0000:02:02.0 on NUMA socket -1
EAL:   probe driver: 8086:100f rte_em_pmd
EAL: PCI device 0000:02:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100f rte_em_pmd
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
NETIF: worker cpu2:dpdk0 rx_queue_id += 1
NETIF: worker cpu2:dpdk0 tx_queue_id += 1
NETIF: worker cpu3:dpdk0 rx_queue_id += 2
NETIF: worker cpu3:dpdk0 tx_queue_id += 2
NETIF: worker cpu4:dpdk0 rx_queue_id += 3
NETIF: worker cpu4:dpdk0 tx_queue_id += 3
NETIF: worker cpu5:dpdk0 rx_queue_id += 4
NETIF: worker cpu5:dpdk0 tx_queue_id += 4
NETIF: worker cpu6:dpdk0 rx_queue_id += 5
NETIF: worker cpu6:dpdk0 tx_queue_id += 5
NETIF: worker cpu7:dpdk0 rx_queue_id += 6
NETIF: worker cpu7:dpdk0 tx_queue_id += 6
NETIF: worker cpu8:dpdk0 rx_queue_id += 7
NETIF: worker cpu8:dpdk0 tx_queue_id += 7
EAL: Error - exiting with code: 1
  Cause: Cannot init mbuf pool on socket 1
[1]+  Exit 1                  ./dpvs

**Comment by SpiritComan** [comment]
hello,when i try to run dpvs with the step in README,i had some errors.I try it again and again,but it always occured。I have no idea how to solve the problem,I need your help!Thank You!

**Comment by PolluxAvenger** [comment]
The same error! need help!!!

**Comment by beacer** [comment]
Seems you have the same issue with #58, are you also using VM to run DPVS ?
Cannot say why it fails to init mbuf pool, we didn't see it on our development environment, may need some debugging.

**Comment by SpiritComan** [comment]
i check the source code of dpvs,fouded that the errors assert at the api of dpdk.But i can run the samples of the dpdk. Do gdb the dpvs is what you want me doing?

**Comment by beacer** [comment]
Yes, if possible, pls help to debug it, and provide more info. Because we didn't see this issue on our development and production environment. Thanks for help.
To enable debug for `DPVS`, pls modify the `src/Makefile`, to enable DPDK lib's debug, refer this link. http://dpdk.org/ml/archives/dev/2015-August/022592.html

**Comment by ywc689** [comment]
Close expired issue.
