### ISSUE TITLE
Centos 7.6 reports an error, there is only one node0,How to start node1，Do I need two network cards eth0 and eth1

### ISSUE THREAD

**Issue by luo964973791** [iqiyi/dpvs#693]
echo 8192 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
echo 8192 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages
[root@localhost ~]# numastat 
                           node0
numa_hit                  994158
numa_miss                      0
numa_foreign                   0
interleave_hit             16160
local_node                994158
other_node                     0
[root@localhost ~]# ls

**Comment by luo964973791** [comment]
LD dpdk-test-eventdev
  INSTALL-APP dpdk-test-eventdev
  INSTALL-MAP dpdk-test-eventdev.map
Build complete [x86_64-native-linuxapp-gcc]
[root@seesaw-config1 dpdk-stable-17.11.2]# echo $?
0
[root@seesaw-config1 dpdk-stable-17.11.2]# numastat 
                           node0
numa_hit                 7967681
numa_miss                      0
numa_foreign                   0
interleave_hit             16143
local_node               7967681
other_node                     0
[root@seesaw-config1 dpdk-stable-17.11.2]# uname -r 
3.10.0-1160.11.1.el7.x86_64
[root@seesaw-config1 dpdk-stable-17.11.2]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@seesaw-config1 dpdk-stable-17.11.2]#

**Comment by ywc689** [comment]
Maybe your machine isn't the NUMA platform.
