### ISSUE TITLE
full-nat 有计划开源toa模块么 

### ISSUE THREAD

**Issue by xiujie-jiang** [iqiyi/dpvs#70]
full-nat 有计划开源TOA模块吗 
我的RS 用的2.6内核 打上了 阿里开源版本full-nat  的TOA 获取不到CLIENTIP

**Comment by beacer** [comment]
TCP option format for TOA is not changed, 2.6 RS should able to get client IP.

**Comment by xiujie-jiang** [comment]
有没有针对取client ip 的配置 我测试了阿里的full-nat  后端的RS可以取到真实的client ip，dpvs 取到的client ip 是 LIP，测试中 使用同一个RS

![image](https://user-images.githubusercontent.com/3118029/34330748-164c7892-e95b-11e7-9268-7052f0436d86.png)

**Comment by xiujie-jiang** [comment]
有没有针对取client ip 的配置 我测试了阿里的full-nat 后端的RS可以取到真实的client ip，dpvs 取到的client ip 是 LIP，测试中 使用同一个RS

**Comment by okletswin** [comment]
在rs上tcpdump抓包，wireshark打开看看，options里的内容是什么

**Comment by lvsgate** [comment]
https://docs.ucloud.cn/security/uads/faq/game
http://ddospcap.ufile.ucloud.cn/toa_centos6.5_v2.tar.gz
http://ddospcap.ufile.ucloud.cn/toa_centos7_v3.tar.gz
ucloud有源代码下载，直接编译安装，不需要重新安装内核和重启系统。
但是ucloud吧OPT_CODE改成252了，你要改成跟dpvs一致

**Comment by beacer** [comment]
@xiujie-jiang is the issue fixed ? if not, pls show the TCP address option by tcpdump or wireshark.

**Comment by icymoon** [comment]
You can try https://github.com/Huawei/TCP_option_address.git

**Comment by zjlletian** [comment]
@lvsgate 我们目前项目用的rs是 lvs_v3的toa，发现能兼容 lvs_v2 和 lvs_v3 (tcp option格式没变？)， 想请问一下，这个是那个版本的 tcp option呢？

**Comment by beacer** [comment]
As discussed above, `TOA` is already "open-sourced" by other companies, the real servers (RS) for  `DPVS` can use them.
Pls check `tutorial.md` to found the TOA resources.
