### ISSUE TITLE
Make failed due to complie warning as error

### ISSUE THREAD

**Issue by Xiangpeng-Sun** [iqiyi/dpvs#701]
在基于最新版 master 5346e4c645c8dd0f0d833a302bc3670fa2132980 分支代码进行编译时，make 会出现如下报错

/root/DevEnv/DPVS/dpvs/src/eal_mem.c: 在函数‘dp_vs_get_eal_mem_seg’中:
/root/DevEnv/DPVS/dpvs/src/eal_mem.c:98:5: 错误：不建议使用‘rte_memseg_walk’(声明于 /root/DevEnv/DPDK/dpdk-stable-18.11.2/build/include/rte_memory.h:231)：Symbol is not yet part of stable ABI [-Werror=deprecated-declarations]
     rte_memseg_walk(dp_vs_fill_mem_seg_info, eal_mem_segs);
     ^
cc1: all warnings being treated as errors
make[1]: *** [/root/DevEnv/DPVS/dpvs/src/eal_mem.o] 错误 1

通过关闭 src/Makefile 中的 Werror 可以规避掉，但是继续编译过程中会出现如下报错
/usr/bin/ld: 找不到 -lrte_pmd_pcap
/usr/bin/ld: 找不到 -lpcap
collect2: 错误：ld 返回 1
make[1]: *** [dpvs] 错误 1

另外目前最新的 master 分支在编译前需要设置 RTE_TARGET，否则会报错

以上问题均未出现在上个master版本中

**Comment by jonas32** [comment]
Same Problem here.
The problem is not based on the compile warning but on 
/bin/ld: cannot find -lrte_pmd_pcap
/bin/ld: cannot find -lpcap
You can skip this error/warning above it by adding -Wno-error=deprecated-declarations to the src/Makefile CFLAGS

**Comment by ywc689** [comment]
Maybe your DPDK missed the patches.
```
0004-rm-rte_experimental-attribute-of-rte_memseg_walk.patch
0005-enable-pdump-and-change-dpdk-pdump-tool-for-dpvs.patch
```

**Comment by Xiangpeng-Sun** [comment]
> Maybe your DPDK missed the patches.
> 
> ```
> 0004-rm-rte_experimental-attribute-of-rte_memseg_walk.patch
> 0005-enable-pdump-and-change-dpdk-pdump-tool-for-dpvs.patch
> ```

打了两个补丁后可以正常编译了，谢谢

**Comment by jonas32** [comment]
> 
> 
> Maybe your DPDK missed the patches.
> 
> ```
> 0004-rm-rte_experimental-attribute-of-rte_memseg_walk.patch
> 0005-enable-pdump-and-change-dpdk-pdump-tool-for-dpvs.patch
> ```

Thats it! Thank you!

**Comment by marchlhw** [comment]
for i in src tools; do make -C $i || exit 1; done
make[1]: Entering directory `/home/cmpt/dpvs-1.8.12/src'
  eal_mem.o
  global_conf.o
/home/cmpt/dpvs-1.8.12/src/eal_mem.c: In function ‘dp_vs_get_eal_mem_seg’:
/home/cmpt/dpvs-1.8.12/src/eal_mem.c:98:5: error: ‘rte_memseg_walk’ is deprecated (declared at /home/cmpt/dpdk-stable-18.11.2/build/include/rte_memory.h:231): Symbol is not yet part of stable ABI [-Werror=deprecated-declarations]
     rte_memseg_walk(dp_vs_fill_mem_seg_info, eal_mem_segs);
     ^
cc1: all warnings being treated as errors
make[1]: *** [/home/cmpt/dpvs-1.8.12/src/eal_mem.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/cmpt/dpvs-1.8.12/src'
make: *** [all] Error 1



我也有同样的报错，按照上述方案操作了，依然报错
