### ISSUE TITLE
black-list 怎么使用

### ISSUE THREAD

**Issue by xiujie-jiang** [iqiyi/dpvs#71]
black-list 是把恶意请求的ip自动加入到 black-list 还是手动配置的 
我只在ipvsadm 看到 有--get-blklst 参数

**Comment by beacer** [comment]
Currently, have to use `keepalived` to configure black list. Give you the example later. And we'll support black-list on `ipvsadm` in the future.

**Comment by mscbg** [comment]
@xiujie-jiang ：You can configure black-list in keepalived just like local ip, and get/show them by ipvsadm. It don't add atomatic. Here is an example:

deny_address_group 192.1.1.1_deny {
192.1.1.2
192.1.2.1-24 #24 black-list
}
virtual_server  group 192.1.1.1_group _default {
XXXXXX
daddr_group_name 192.1.1.1_deny
XXXXXXX
}

Then you should reload or restart keepalived. You can show them by ipvsadm -B.

**Comment by xiujie-jiang** [comment]
在测试这个功能的时候 发现一个 状况，我添加了一个 ip 段（24位掩码）  ipvsadm -B 只显示25个DENY_IP

**Comment by xiujie-jiang** [comment]
black-list只支持 25个ip吗

**Comment by beacer** [comment]
No, we support 10W items at most.
