### ISSUE TITLE
Topology Tunnel mode be configured with keepalived?

### ISSUE THREAD

**Issue by thanhdat9526** [iqiyi/dpvs#715]
Can single-branch and two-branch topology **Tunnel mode** be configured with **keepalived**? I'm interested in using dpvs with keepalived.

**Comment by ywc689** [comment]
yes.  you can configure tunnel ipvs forwarding mode by keepalived like this.

```
virtual_server  group mygroup {
    lb_kind TUN
    ...
}
```
