### ISSUE TITLE
Stress tests have a lot of errors

### ISSUE THREAD

**Issue by NicoSpec** [iqiyi/dpvs#72]
we used tsung to test dpvs appearing lots of errors

Name                                      |Highest Rate | Total number

error_abort_max_conn_retries | 99.3 / sec     | 2557
error_abort_max_send_retries | 3.6 / sec        | 73
error_connect_eaddrinuse       | 21.7 / sec      | 779
error_connect_etimedout        | 133 / sec       | 20857
error_connection_closed         | 17.2 / sec       | 360
error_timeout                          | 39.5 / sec       | 811

**Comment by ywc689** [comment]
How much traffic used for the stress tests? Was there any error logs in the system?
Possibly not enough local IPs configured. Try 'dpip addr show' to find if there exists sa_miss in stress test. If so, configure more local IPs and try again.

**Comment by beacer** [comment]
Any update @NicoSpec . Can you show us the test env and configure? for example the client tool, server, DPVS's configure file. and dpvs's log.

**Comment by NicoSpec** [comment]
Our test tool is tsung,
This is tsung's configure,concurrency is 50,000:
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/local/share/tsung/tsung-1.0.dtd">
<tsung loglevel="notice" version="1.0">
  
  <clients>
 <client host="bx_tsung_11" weight="2"  maxusers="4000000" cpu="20">
	<ip value="client ip1"></ip>
	<ip value="client ip2"></ip>
	<ip value="client ip3"></ip>
	<ip value="client ip4"></ip>
           </client>
<client host="bx_tsung_12" weight="2"  maxusers="4000000" cpu="20">
        <ip value="client ip5"></ip>   
	<ip value="client ip6"></ip>
	<ip value="client ip7"></ip>
	<ip value="client ip8"></ip>
	</client>
<client host="bx_tsung_13" weight="2"  maxusers="4000000" cpu="20">
        <ip value="client ip9"></ip>
        <ip value="client ip10"></ip>
        <ip value="client ip11"></ip>
        <ip value="client ip12"></ip>
        </client>
<client host="bx_tsung_14" weight="2"  maxusers="4000000" cpu="20">
        <ip value="client ip13"></ip>
        <ip value="client ip14"></ip>
        <ip value="client ip15"></ip>
        <ip value="client ip16"></ip>
        </client>
<client host="bx_tsung_15" weight="2"  maxusers="4000000" cpu="20">
        <ip value="client ip17"></ip>
        <ip value="client ip18"></ip>
        <ip value="client ip19"></ip>
        <ip value="client ip20"></ip>
        </client>
  </clients>
  
  
<servers>
  
  <server host="server ip" port="80" type="tcp"></server> 
            
  
</servers>

   
   <monitoring>  
 	 <monitor host=" bx_tsung_11" type="erlang"></monitor>   
	 <monitor host=" bx_tsung_12" type="erlang"></monitor>
	 <monitor host=" bx_tsung_13" type="erlang"></monitor>
	 <monitor host=" bx_tsung_14" type="erlang"></monitor>
	 <monitor host=" bx_tsung_15" type="erlang"></monitor>
    </monitoring> 
  
  <load>
  
   <arrivalphase phase="1" duration="3" unit="minute">

 	<users maxnumber="5000000" arrivalrate="50000" unit="second"></users> 
   </arrivalphase>
  </load>

  <options>
   <option type="ts_http" name="user_agent">
    <user_agent probability="80">Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.8) Gecko/20050513 Galeon/1.3.21</user_agent>
    <user_agent probability="20">Mozilla/5.0 (Windows; U; Windows NT 5.2; fr-FR; rv:1.7.8) Gecko/20050511 Firefox/4.0.4</user_agent>
   </option>
	<option name="ports_range" min="1025" max="65000"/>
	<option name="hibernate" value="infinity"></option>
	 <option name="tcp_snd_buffer" value="4096"></option>
  	<option name="tcp_rcv_buffer" value="4096"></option>
	  <option name="idle_timeout" value="180000"></option>
  <option name="global_ack_timeout" value="600000"></option>
  
</options>

  

 <sessions>
  <session name="http-example" probability="100" type="ts_http">
    
   
  <for from="1" to="50" var="ab">
   <for from="1" to="100" var="counter"> 
    <request> <http url="/ten.html" method="GET" version="1.1" >

	</http> </request>
</for>
  
</for>
  </session>
 </sessions>
</tsung>

DPVS's configure is default configure file.

 dpvs's log have some error's log,for example:
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
IPVS: dp_vs_sched_persist: persist-schedule: no dest found.
This is error reports of tsung:
![default](https://user-images.githubusercontent.com/19813367/34659546-db90210c-f474-11e7-89f7-a24d6d5fb83e.png)

**Comment by beacer** [comment]
Can you show the output of `dpip addr show`, `ipvsadm -ln`, `ipvsadm -G`, `dpip -s link show` , `dpip -s link show cpu` ?
The log `persist-schedule: no dest found.` could be warning not error, the tool we're using are `wrk`, `ab` and `webbench`, while `wrk` is highly recommend.

**Comment by ywc689** [comment]
1`no dest found` indicates your backend servers may be the bottleneck of the stress test. Add more backend servers, or use high performance servers instead. 

Are you really need persistent connections? If not,  turn off it may improve performance.

**Comment by NicoSpec** [comment]
Hi,
@beacer @ywc689 
Now,we use "Intel(R) 10 Gigabit PCI Express Network" to test dpvs and close nginx's persistent connection.dpvs's log haven't any warning and tsung's report almost no error.
PPS also reached the official test results.
Thank you very much for your support.
