### ISSUE TITLE
双臂模式KNI IP无法SSH登录

### ISSUE THREAD

**Issue by Moke-bala** [iqiyi/dpvs#723]
你好，我使用的是FNAT双臂模式，规划如下：
wan-dpdk0：互联ip为10.128.92.20/25，互联口交换机ip 10.128.92.1 
local-dpdk1 : ip配置 10.128.248.101/24，网关ip 10.128.248.1

dpdk0，dpdk1连到同一台交换机上，划分到不同的vlan

dpdk路由如下：
![image](https://user-images.githubusercontent.com/22319787/112006500-bbdde400-8b5e-11eb-8756-43babb141d18.png)
同时配置了
dpdk0.kni  10.128.92.20/25
dpdk1.kni  10.128.248.101/24
路由如下：
![image](https://user-images.githubusercontent.com/22319787/112006907-2131d500-8b5f-11eb-8d26-93b29f5a544b.png)

从别的网段ping 10.128.92.20及10.128.248.101都正常，但是抓包dpdk0.kni，dpdk1.kni均无数据包

[C:\~]$ ping 10.128.248.101

正在 Ping 10.128.248.101 具有 32 字节的数据:
来自 10.128.248.101 的回复: 字节=32 时间=7ms TTL=55
来自 10.128.248.101 的回复: 字节=32 时间=5ms TTL=55
来自 10.128.248.101 的回复: 字节=32 时间=5ms TTL=55
来自 10.128.248.101 的回复: 字节=32 时间=5ms TTL=55

[C:\~]$ ping 10.128.92.20

正在 Ping 10.128.92.20 具有 32 字节的数据:
来自 10.128.92.20 的回复: 字节=32 时间=5ms TTL=55
来自 10.128.92.20 的回复: 字节=32 时间=6ms TTL=55
来自 10.128.92.20 的回复: 字节=32 时间=5ms TTL=55
来自 10.128.92.20 的回复: 字节=32 时间=5ms TTL=55

但是我想通过SSH登录却不成功，在dpvs服务器上ping网关不通

C:\~]$ ssh 10.128.248.101 16120
Connecting to 10.128.248.101:16120...
Could not connect to '10.128.248.101' (port 16120): Connection failed.

![image](https://user-images.githubusercontent.com/22319787/112007796-ea0ff380-8b5f-11eb-8520-9430e959d5ff.png)

请问如果配置才能使KNI IP生效？让SSH可以使用，谢谢！

**Comment by ywc689** [comment]
1. dpdk0.kni/dpdk1.kni 两个接口为 `NO-CARRIER` 状态，可能是 kni 模块加载的时候没有`carrier=on`参数。
2. 如果 packet 匹配了 DPVS 的路由，DPVS 不会将它传给 KNI，这种情况下，如果要把这类包传给 kni，需要添加 scope 类型为 kni_host 的路由。

```
dpip route add 10.128.92.20/32 dev dpdk0 scope kni_host
dpip route add 10.128.248.101/32 dev dpdk1 scope kni_host
```

**Comment by Moke-bala** [comment]
> 1. dpdk0.kni/dpdk1.kni 两个接口为 `NO-CARRIER` 状态，可能是 kni 模块加载的时候没有`carrier=on`参数。
> 2. 如果 packet 匹配了 DPVS 的路由，DPVS 不会将它传给 KNI，这种情况下，如果要把这类包传给 kni，需要添加 scope 类型为 kni_host 的路由。
> 
> ```
> dpip route add 10.128.92.20/32 dev dpdk0 scope kni_host
> dpip route add 10.128.248.101/32 dev dpdk1 scope kni_host
> ```

根据指导，加上 `carrier=on` 参数及kni_host类型路由可以了，非常感谢！！
