### ISSUE TITLE
Mellanox网卡bond4模式，交换机口lacp协商失败

### ISSUE THREAD

**Issue by LittleWindy** [iqiyi/dpvs#725]
在用Mellanox 25g网卡 bond的时候：bond2模式交换机和dpvs端口都正常；bond4模式交换机协商lacp不成功

**Comment by wDCat** [comment]
可以参考这个issue里的方式patch dpdk
https://bugs.dpdk.org/show_bug.cgi?id=343
，或者修改dpvs关闭dedicated queue

**Comment by LittleWindy** [comment]
> 可以参考这个issue里的方式patch dpdk
> https://bugs.dpdk.org/show_bug.cgi?id=343
> ，或者修改dpvs关闭dedicated queue

多谢，问题已解决

**Comment by ywc689** [comment]
Fixed in pr #734 .
