### ISSUE TITLE
dpvs 运行不通 哪位大侠能帮忙看一下，十万火急

### ISSUE THREAD

**Issue by 316953425** [iqiyi/dpvs#73]
您好，爱奇艺的开发者们

非常感谢你们开源了dpvs这个优秀的项目，我最近在学习使用它，在使用的过程中我遇见
了一些问题，希望您们能帮组我解决一下

我的配置如下
+ ./dpip addr add 10.114.249.201/24 dev dpdk0
+ ./dpip route add default via 10.114.249.254 dev dpdk0
+ ./ipvsadm -A -t 10.114.249.201:80 -s rr
+ ./ipvsadm -a -t 10.114.249.201:80 -r 10.112.95.3 -b
+ ./ipvsadm --add-laddr -z 10.114.249.202 -t 10.114.249.201:80 -F dpdk0

我仅仅使用了一个网卡（X710）

我dpvs的配置文件为dpvs.conf.single-nic.sample
我发现一个奇怪的现象，只用我当的网卡队列数设置为1的时候，是可以curl成功的

如果为其他则访问不通，我看代码原以为是fdir没有设置成功，但是我通过gdb调试发现fdir设置成功了

麻烦您们能帮组我解答一下吗？

非常感谢~

**Comment by beacer** [comment]
Pls open `CONFIG_DPVS_IPVS_DEBUG` in `src/Makefile` to check if all packet in same connection recieved by same CPU core.

**Comment by 316953425** [comment]
Makefile：

#CFLAGS += -O3
CFLAGS += -g -O0
CFLAGS += -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes
CFLAGS += $(USER_FLAGS)
CFLAGS += -I $(SRCDIR)/../include/

#CFLAGS += -D CONFIG_RECORD_BIG_LOOP
CFLAGS += -D CONFIG_DPVS_SAPOOL_DEBUG
CFLAGS += -D CONFIG_DPVS_IPVS_DEBUG
#CFLAGS += -D CONFIG_SYNPROXY_DEBUG
#CFLAGS += -D CONFIG_TIMER_MEASURE
#CFLAGS += -D DPVS_CFG_PARSER_DEBUG

同时我也在dpvs.conf中设置了log基本为DEBUG，但是我看dpvs.log中没有任何相关的log 输出啊~

**Comment by beacer** [comment]
/var/log/message.

**Comment by 316953425** [comment]
/var/log/messages中关于dpvs的log只有

Dec 25 11:50:01 bj-gc3-10-114-249-8 systemd: Starting Session 851 of user root.
Dec 25 11:51:48 bj-gc3-10-114-249-8 dpvs: dpvs_running: Remove a zombie pid file /var/run/dpvs.pid
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: PMD: bnxt_rte_pmd_init() called for (null)
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: EAL: PCI device 0000:04:00.0 on NUMA socket 0
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: EAL:   probe driver: 8086:1572 rte_i40e_pmd
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: EAL: PCI device 0000:04:00.1 on NUMA socket 0
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: EAL:   probe driver: 8086:1572 rte_i40e_pmd
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: PMD: eth_i40e_dev_init(): FW 5.60 API 1.5 NVM 05.06.00 eetrack 80002dac
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: CFG_FILE: log_level = DEBUG
Dec 25 11:51:54 bj-gc3-10-114-249-8 dpvs[24462]: CFG_FILE: log_file = /var/log/dpvs.log
Dec 25 11:51:55 bj-gc3-10-114-249-8 kernel: KNI: Creating kni...



没有别的相关信息啦~

**Comment by oupeng007** [comment]
i40e驱动没设置dst_port_mask，flow director没命中

**Comment by autumn0207** [comment]
> dst_port_mask

这个有方法规避吗
