### ISSUE TITLE
DPDK L3fwd ACL: EAL Error - exiting with code 1 Cause: Cannot init mbuf pool on socket 0

### ISSUE THREAD

**Issue by shashankbr11** [iqiyi/dpvs#736]
I have been running the executable of L3fwd ACL in a setup of loopback manner. I have been facing the EAL error mentioned after the ACL entries are initially parsed.
Kindly suggest any method to workaround this issue if come across in a similar application.

**Comment by ywc689** [comment]
Check if the hugepage is set properly. Refer to DPDK l3fwd for more details.
https://doc.dpdk.org/guides/sample_app_ug/l3_forward.html

Besides, this is not an issue of DPVS. We'll closing it soon.
