### ISSUE TITLE
客户端curl VIP地址 时通时不通

### ISSUE THREAD

**Issue by CZILYYZ** [iqiyi/dpvs#738]
用的官方的版本18.11.2，网卡inter I350 系统内核版本2.10.0-1127.el7.x86_64 centos7.8 按照官网的步骤一步步配置，发现curl时通时不通，我理解是不通的时候包没有被dpdk劫持，送到内核去处理了。有朋友遇到过类似的问题吗

**Comment by ywc689** [comment]
可能是packet 和 per-lcore 的session匹配失败导致的，可以用一个worker试试，或者打开 dpvs 的 conn redirect 配置。

**Comment by CZILYYZ** [comment]
worker我用了一个的话，发现问题解决了，那假如我要用多个work该怎么解决呢，怎么才能解决packet 和 per-lcore 的session匹配失败的问题，有什么排查手段吗

**Comment by CZILYYZ** [comment]
> 可能是packet 和 per-lcore 的session匹配失败导致的，可以用一个worker试试，或者打开 dpvs 的 conn redirect 配置。

worker我用了一个的话，发现问题解决了，那假如我要用多个work该怎么解决呢，怎么才能解决packet 和 per-lcore 的session匹配失败的问题，有什么排查手段吗

**Comment by CZILYYZ** [comment]
> 可能是packet 和 per-lcore 的session匹配失败导致的，可以用一个worker试试，或者打开 dpvs 的 conn redirect 配置。

worker我用了一个的话，发现问题解决了，那假如我要用多个work该怎么解决呢，怎么才能解决packet 和 per-lcore 的session匹配失败的问题，有什么排查手段吗

**Comment by ywc689** [comment]
可以打开 `src/config.mk` 中的宏定义 `CFLAGS += -D CONFIG_DPVS_IPVS_DEBUG`，然后将 DPVS 日志级别调到 DEBUG，通过 session 日志可以确认该问题。

如果确认是 session miss 导致的，说明你的网卡不支持需要的 flow 特性（参考 [FAQ](https://github.com/iqiyi/dpvs/blob/master/doc/faq.md#nic))。这种情况下，如果要用多个worker，可以配置 DPVS 的 `redirect` 配置。

**Comment by first98K** [comment]
可以先把队列数设置为1，看看是否正常。如果正常可能与fdir没生效有关
