### ISSUE TITLE
keepalived启动和连接状态停留在SYN_RECV问题

### ISSUE THREAD

**Issue by CZILYYZ** [iqiyi/dpvs#740]
./keepalived -f /etc/keepalived/keepalived.conf启动之后用systemctl status keepalived 提示Unit keepalived.service could not be found.看log显示：Jul  5 23:53:57 pdvs-LVS-2 Keepalived[4101]: Opening file '/etc/keepalived/keepalived.conf'.
Jul  5 23:53:57 pdvs-LVS-2 Keepalived[4101]: daemon is already running
这样就算启动成功了吗？然后我发现客户端curl VIP地址不通：
[root@pdvs-LVS-2 bin]# ./ipvsadm -lcn
[3]tcp 30s    SYN_RECV    172.16.37.60:42044 123.1.2.3:80       172.10.0.2:1026    172.16.37.59:80
[3]tcp 30s    SYN_RECV    172.16.37.60:42046 123.1.2.3:80       172.10.0.2:1034    172.16.37.60:80
状态停留在recv，请问这个哪里出问题了？ 
![image](https://user-images.githubusercontent.com/86775639/124540264-9cd73980-de51-11eb-9e11-f59ceaff2982.png)
这个是拓扑，keepalived.conf 配置如下：
! Configuration File for keepalived

global_defs {
    notification_email {
        foo@example.com
    }
    notification_email_from bar@example.com
    smtp_server 1.2.3.4
    smtp_connect_timeout 60
    router_id DPVS_DEVEL
}

local_address_group laddr_g1 {
    172.10.0.2 dpdk1    # use DPDK interface
}

#
# VRRP section
#
vrrp_instance VI_1 {
    state MASTER                  # master
    interface dpdk1.kni           # should be kni interface
    dpdk_interface dpdk1         # should be DPDK interface
    virtual_router_id 123         # VID should be unique in network
    priority 100                  # master's priority is bigger than worker
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1234
    }

    virtual_ipaddress {
        123.1.2.3
    }
}

#
# Virtual Server Section
#
virtual_server_group 123.1.2.3-80 {
    123.1.2.3 80
}

virtual_server group 123.1.2.3-80 {
    delay_loop 3
    lb_algo rr         # scheduling algorithm Round-Robin
    lb_kind FNAT       # Forwarding Mode Full-NAT
    protocol TCP       # Protocol TCP

    laddr_group_name laddr_g1   # Local IP group-ID

    real_server 172.16.37.59 80 { # real-server
        weight 100
        inhibit_on_failure
        TCP_CHECK {    # health check
            nb_sock_retry 2
            connect_timeout 3
            connect_port 80
        }
    }

    real_server 172.16.37.60 80 { # real-server
        weight 100
        inhibit_on_failure
        TCP_CHECK { # health check
            nb_sock_retry 2
            connect_timeout 3
            connect_port 80
        }
    }
}

**Comment by ywc689** [comment]
two-arm 场景下 LIP 用于 DPVS 与 RS 之间的连接，应该配置在内网 DPVS 的内网接口上，并且与 RS 的网络能连通。
