### ISSUE TITLE
单网卡配置fullnat，dpip配置ip不通问题

### ISSUE THREAD

**Issue by sunlihui** [iqiyi/dpvs#741]
本机可以ping通地址，但是实际服务不能生效，其他机器也无法ping通
`# dpip addr show
inet 10.89.89.11/32 scope global dpdk0
     valid_lft forever preferred_lft forever
inet 10.89.89.10/24 scope global dpdk0
     valid_lft forever preferred_lft forever
# ipvsadm  -Ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
UDP  10.89.89.10:53 rr
  -> 10.2.30.100:53               FullNat 1      0          0
`

**Comment by ywc689** [comment]
请参考 [tutorial 文档](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#fnat-keepalive) 配置。

**Comment by zhouyangchao** [comment]
service没配置LIP

**Comment by legend050709** [comment]
> service没配置LIP

good; HHH

**Comment by sunlihui** [comment]
thanks
