### ISSUE TITLE
如下信息，配置Full-NAT with Keepalived (one-arm) 后，可以ping通，但是七层访问不通，nmap显示端口被 filtered，请问是什么问题？

### ISSUE THREAD

**Issue by sunlihui** [iqiyi/dpvs#744]
`Starting Nmap 6.40 ( http://nmap.org ) at 2021-07-17 16:15 CST
Nmap scan report for 10.89.89.10
Host is up (0.00039s latency).
Not shown: 997 closed ports
PORT    STATE    SERVICE
22/tcp  open     ssh
80/tcp  filtered http
111/tcp open     rpcbind

Nmap done: 1 IP address (1 host up) scanned in 2.73 seconds
root@infra-ansible-pro-1 ~ $ ping 10.89.89.10
PING 10.89.89.10 (10.89.89.10) 56(84) bytes of data.
64 bytes from 10.89.89.10: icmp_seq=1 ttl=63 time=0.111 ms
64 bytes from 10.89.89.10: icmp_seq=2 ttl=63 time=0.882 ms`

[root@sh1-arch-dns-2 ~]# dpip addr show
inet 10.89.89.11/32 scope global dpdk0
     valid_lft forever preferred_lft forever
inet 10.89.89.12/32 scope global dpdk0
     valid_lft forever preferred_lft forever
inet 10.89.89.10/32 scope global dpdk0
     valid_lft forever preferred_lft forever
[root@sh1-arch-dns-2 ~]# ipvsadm -ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.89.89.10:80 rr
  -> 10.3.10.195:8000             FullNat 100    0          0

**Comment by ywc689** [comment]
请参考 [tutorial 文档](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#fnat-keepalive)。

注意，DPVS  one-arm 转发需要保证：
* DPVS 和 RS  之间网络连通性没问题（最好让 DPVS 的 local IP 和 RS 的 IP 在同一网段）
* FullNat 网卡支持 flow director（如果不确定你的网卡是否支持，可以使用一个 worker 先试试）
* DPVS 路由配置正确

**Comment by sunlihui** [comment]
谢谢解答！
使用一个worker测试，如何来做，是修改 dpvs.conf配置文件 worker_defs里面，只留一个worker吗？

**Comment by ywc689** [comment]
是的，dpvs.conf 里只保留一个worker。
