### ISSUE TITLE
求救dpvs启动失败

### ISSUE THREAD

**Issue by zhangli1616** [iqiyi/dpvs#749]
./dpvs -- --lcores 0@2,1@4,2@6,3@8,4@10,5@12,6@14,7@16,8@18 &
[1] 94790
current thread affinity is set to FFFFFFF
EAL: Detected 28 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
[root@3.sys.dpvs.tt.bjs.p1staff.com bin]$ EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:154d net_ixgbe
EAL: PCI device 0000:03:00.1 on NUMA socket 0
EAL:   probe driver: 8086:154d net_ixgbe
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
DPVS: dpvs version: 1.8-10, build on 2021.08.01.19:21:15
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: dpdk1:rx_queue_number = 8
NETIF: worker cpu1:bond0 rx_queue_id += 0
NETIF: worker cpu1:bond0 tx_queue_id += 0
NETIF: worker cpu2:bond0 rx_queue_id += 1
NETIF: worker cpu2:bond0 tx_queue_id += 1
NETIF: worker cpu3:bond0 rx_queue_id += 2
NETIF: worker cpu3:bond0 tx_queue_id += 2
NETIF: worker cpu4:bond0 rx_queue_id += 3
NETIF: worker cpu4:bond0 tx_queue_id += 3
NETIF: worker cpu5:bond0 rx_queue_id += 4
NETIF: worker cpu5:bond0 tx_queue_id += 4
NETIF: worker cpu6:bond0 rx_queue_id += 5
NETIF: worker cpu6:bond0 tx_queue_id += 5
NETIF: worker cpu7:bond0 rx_queue_id += 6
NETIF: worker cpu7:bond0 tx_queue_id += 6
CFG_FILE: not supported keyword -- icmp_redirect_core
NETIF: worker cpu8:bond0 rx_queue_id += 7
NETIF: worker cpu8:bond0 tx_queue_id += 7
bond_ethdev_mode_set(1685) - Using mode 4, it is necessary to do TX burst and RX burst at least every 100ms.
linux_set_if_mac: fail to set bond0.kni's MAC address: Cannot assign requested address
IPVS: fail to init conn: no memory
EAL: Error - exiting with code: 1
  Cause: failed to init ipvs: no memory

**Comment by selboo** [comment]
内存不够了

**Comment by zhangli1616** [comment]
> 内存不够了

是的，和dpvs.conf参数设置有关系，已解决
