### ISSUE TITLE
1.8.10版本，遇到初始化时，偶发的sa_pool，内存分配在某些线程上为空

### ISSUE THREAD

**Issue by realzhaoxing** [iqiyi/dpvs#758]
![image](https://user-images.githubusercontent.com/89736948/133208917-4b859777-1475-4ccc-80e5-77a2d1c3a90f.png)

**Comment by ywc689** [comment]
检查 DPVS 日志，确认是不是内存不足。

**Comment by realzhaoxing** [comment]
当时确认过，内存是够的。后续机器也没重启过，dpvs重启就不出了。
几台机器都出现了该问题。

**Comment by ywc689** [comment]
该问题是消息超时引起的数据获取不全，v1.9 已优化修复。
