### ISSUE TITLE
log_async_mode需要增加额外的配置吗

### ISSUE THREAD

**Issue by limeix** [iqiyi/dpvs#770]
1.8.8版本，配置log_async_mode on，需要增加额外配置吗

目前测试只开启log_async_mode on，dpvs不能正常工作

**Comment by first98K** [comment]
正确的使用方式没研究明白，但是可以改下初始化顺序：
main()中，log_slave_init()在dpvs_lcore_start(0)之后调用可以规避该问题
备注：
1、dpvs-1.9.0及之前的版本，dpdk-21.08及之前的版本。
2、dpdk-21.11版本已经没有FINISHED状态，等待更新吧。。。

**Comment by limeix** [comment]
感谢回复，自己修改了一版代码，已经可以正常使用了
