### ISSUE TITLE
ipv6 FullNat【LB_RUNNING: Drop invalid packet: No SNAT resource entry for FNAT: invalid parameter】

### ISSUE THREAD

**Issue by zsjlqq** [iqiyi/dpvs#781]
client:
5: p1p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 90:e2:ba:3c:22:bc brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.48/24 scope global p1p1
       valid_lft forever preferred_lft forever
    inet6 2001:db8::59/64 scope global
       valid_lft forever preferred_lft forever

dpvs:
[root@localhost bin]# ./ipvsadm -Ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  [2001:db8::1]:80 wlc synproxy
  -> [2001:db8:10::51]:80         FullNat 1      0          0
[root@localhost bin]# ./dpip addr show dev dpdk0
inet6 2001:db8::2/64 scope global dpdk0
     valid_lft forever preferred_lft forever
inet6 2001:db8::1/128 scope global dpdk0
     valid_lft forever preferred_lft forever
[root@localhost bin]# ./dpip addr show dev dpdk1
inet6 2001:db8:10::240/128 scope global dpdk1
     valid_lft forever preferred_lft forever
inet6 2001:db8:10::23f/128 scope global dpdk1
     valid_lft forever preferred_lft forever
inet6 2001:db8:10::23e/128 scope global dpdk1
     valid_lft forever preferred_lft forever
inet6 2001:db8:10::23d/128 scope global dpdk1
     valid_lft forever preferred_lft forever
.............

server:
7: p5p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f8:f2:1e:74:57:d1 brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8:10::51/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ed55:9684:3537:a0bd/64 scope link
       valid_lft forever preferred_lft forever

client ------- wget  http://[2001:db8::1]:80
error log ：LB_RUNNING: Drop invalid packet: No SNAT resource entry for FNAT: invalid parameter

**Comment by ywc689** [comment]
The config seems OK. Are you using the DPVS versions we release? The error log isn't from DPVS versions that we've released.

**Comment by zsjlqq** [comment]
> The config seems OK. Are you using the DPVS versions we release? The error log isn't from DPVS versions that we've released.

这个是其他厂商修改的版本，可以关掉这个issue即可
