### ISSUE TITLE
ipvs and etc make failed

### ISSUE THREAD

**Issue by iluffk** [iqiyi/dpvs#787]
Hi all. Thanks for your product. I wanted to try it to replace common ipvs to this product and while I try to do 'make' I get problem:

`>root@avi-network-test01:/usr/local/dpvs# make -j 20
>for i in src tools; do make -C $i || exit 1; done
>make[1]: Entering directory '/root/dpvs/src'
>make[1]: Nothing to be done for 'all'.
>make[1]: Leaving directory '/root/dpvs/src'
>make[1]: Entering directory '/root/dpvs/tools'
>if [ ! -f keepalived/Makefile ]; then \
>	cd keepalived; \
>	if [ ! -f keepalived/configure ]; then \
>		./build_setup; \
>	fi; \
>	./configure; \
>	cd -; \
>fi
>for i in keepalived ipvsadm dpip; do make -C $i || exit 1; done
>make[2]: Entering directory '/root/dpvs/tools/keepalived'
>Making all in lib
>make[3]: Entering directory '/root/dpvs/tools/keepalived/lib'
>make  all-am
>make[4]: Entering directory '/root/dpvs/tools/keepalived/lib'
>make[4]: Leaving directory '/root/dpvs/tools/keepalived/lib'
>make[3]: Leaving directory '/root/dpvs/tools/keepalived/lib'
>Making all in keepalived
>make[3]: Entering directory '/root/dpvs/tools/keepalived/keepalived'
>Making all in core
>make[4]: Entering directory '/root/dpvs/tools/keepalived/keepalived/core'
>make[4]: Nothing to be done for 'all'.
>make[4]: Leaving directory '/root/dpvs/tools/keepalived/keepalived/core'
>Making all in vrrp
>make[4]: Entering directory '/root/dpvs/tools/keepalived/keepalived/vrrp'
>make[4]: Nothing to be done for 'all'.
>make[4]: Leaving directory '/root/dpvs/tools/keepalived/keepalived/vrrp'
>Making all in check
>make[4]: Entering directory '/root/dpvs/tools/keepalived/keepalived/check'
>  CC       check_data.o
>  CC       check_parser.o
>check_data.c: In function ‘dump_forwarding_method’:
>check_data.c:368:33: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_IPIP’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>             if (rs->tun_type == IP_VS_CONN_F_TUNNEL_TYPE_IPIP)
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                 IP_VS_CONN_F_TUNNEL
>check_data.c:368:33: note: each undeclared identifier is reported only once for each function it appears in
>check_parser.c: In function ‘svr_forwarding_handler’:
>check_parser.c:370:17: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_IPIP’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>  int tun_type = IP_VS_CONN_F_TUNNEL_TYPE_IPIP;
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                 IP_VS_CONN_F_TUNNEL
>check_parser.c:370:17: note: each undeclared identifier is reported only once for each function it appears in
>check_data.c:372:45: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>                 csum_str = rs->tun_flags == IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM ? ", no checksum" :
>                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                             HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>check_parser.c:373:13: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>  int csum = IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM;
>             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>             HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>check_data.c:373:38: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_CSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>                     rs->tun_flags == IP_VS_TUNNEL_ENCAP_FLAG_CSUM ? ", checksum" :
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                      HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>check_parser.c:402:16: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_GUE’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>     tun_type = IP_VS_CONN_F_TUNNEL_TYPE_GUE;
>                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                IP_VS_CONN_F_TUNNEL
>check_parser.c:405:16: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_GRE’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>     tun_type = IP_VS_CONN_F_TUNNEL_TYPE_GRE;
>                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                IP_VS_CONN_F_TUNNEL
>check_data.c:374:38: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_REMCSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>                     rs->tun_flags == IP_VS_TUNNEL_ENCAP_FLAG_REMCSUM ? ", remote checksum" :
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                      HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>check_data.c:377:33: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_GUE’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>             if (rs->tun_type == IP_VS_CONN_F_TUNNEL_TYPE_GUE)
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                 IP_VS_CONN_F_TUNNEL
>check_parser.c:427:11: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_CSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>    csum = IP_VS_TUNNEL_ENCAP_FLAG_CSUM;
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>check_data.c:380:38: error: ‘IP_VS_CONN_F_TUNNEL_TYPE_GRE’ undeclared (first use in this function); did you mean >‘IP_VS_CONN_F_TUNNEL’?
>             else if (rs->tun_type == IP_VS_CONN_F_TUNNEL_TYPE_GRE)
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                      IP_VS_CONN_F_TUNNEL
>check_parser.c:429:11: error: ‘IP_VS_TUNNEL_ENCAP_FLAG_REMCSUM’ undeclared (first use in this function); did you mean >‘HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM’?
>    csum = IP_VS_TUNNEL_ENCAP_FLAG_REMCSUM;
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           HAVE_DECL_IP_VS_TUNNEL_ENCAP_FLAG_NOCSUM
>make[4]: *** [Makefile:391: check_data.o] Error 1
>make[4]: *** Waiting for unfinished jobs....
>make[4]: *** [Makefile:391: check_parser.o] Error 1
>make[4]: Leaving directory '/root/dpvs/tools/keepalived/keepalived/check'
>make[3]: *** [Makefile:591: all-recursive] Error 1
>make[3]: Leaving directory '/root/dpvs/tools/keepalived/keepalived'
>make[2]: *** [Makefile:427: all-recursive] Error 1
>make[2]: Leaving directory '/root/dpvs/tools/keepalived'
>make[1]: *** [Makefile:24: all] Error 1
>make[1]: Leaving directory '/root/dpvs/tools'
>make: *** [Makefile:33: all] Error 1
>root@avi-network-test01:/usr/local/dpvs# 
`

I do it in directory:
`root@avi-network-test01:/usr/local/dpvs# ls
conf             doc                  dpdk-kmods           get-pip.py  kmod           LICENSE.md  patch  pkg-config-0.29.2         README.md  src   tools
CONTRIBUTING.md  dpdk-20.11.1.tar.xz  dpdk-stable-20.11.1  include     LICENSE.GPLv2  Makefile    pic    pkg-config-0.29.2.tar.gz  scripts    test`

with OS 
`root@avi-network-test01:/usr/local/dpvs# uname -a
Linux avi-network-test01 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux`

What could be problem?
Googling and search in this repo didn't help

**Comment by ywc689** [comment]
Keepalived in dpvs doesn't support tunnel. Disable IPVS_DEST_ATTR_TUN_TYPE and try again.

**Comment by iluffk** [comment]
sorry, but how to do that?

**Comment by ywc689** [comment]
You may have a look at the `autoconf` of keepalived. It's default disabled on my system.

**Comment by difficultwork** [comment]
> You may have a look at the `autoconf` of keepalived. It's default disabled on my system.

some code lack while copying from ip_vs.h. I add the code then fixed.

**Comment by su-wataru** [comment]
> > You may have a look at the `autoconf` of keepalived. It's default disabled on my system.
> 
> some code lack while copying from ip_vs.h. I add the code then fixed.
我也遇到了这个问题，请问您是如何修复的，再或者如何禁用这个选项？我没找到@ywc689 所说的`autoconf`文件。

**Comment by ywc689** [comment]
> > > You may have a look at the `autoconf` of keepalived. It's default disabled on my system.
> > 
> > 
> > some code lack while copying from ip_vs.h. I add the code then fixed.
> > 我也遇到了这个问题，请问您是如何修复的，再或者如何禁用这个选项？我没找到@ywc689 所说的`autoconf`文件。

Yes, you are right! #833 has partly fixed similar problem found in Unbuntu in this way.
