### ISSUE TITLE
是否有讨论群？

### ISSUE THREAD

**Issue by liangfudeng** [iqiyi/dpvs#81]

**Comment by 316953425** [comment]
应该没有吧，用了感觉不稳定，问题也没人回答

**Comment by liangfudeng** [comment]
@316953425 方便告知下什么问题不稳定吗？我觉得这个框架很轻量级，能够方便已经自己的业务再次开发。你还了解到其他类似开源项目吗？基于dpdk的lvs或者snat。

**Comment by 316953425** [comment]
看问题列表就知道了，这个还用我说吗？貌似阿里有个开源的吧

**Comment by beacer** [comment]
See #83.
