### ISSUE TITLE
是否计划支持FNAT46或者FNAT66

### ISSUE THREAD

**Issue by legend050709** [iqiyi/dpvs#812]
是否计划支持FNAT46或者FNAT66？
如果支持，对于intel 82599 的 ipv6 的 fdir signature 冲突问题，如何解决，有没有方案？

**Comment by ywc689** [comment]
PR #746 给出了FNAT46的实现，我们下个版本会评估是否要接受该功能。
当前的版本是支持FNAT66的。
82599 网卡 ipv6 flow 的signature冲突问题暂无计划，并发不大的情况下只用一个local IP可以绕过该问题。

**Comment by legend050709** [comment]
另外问下，mellanox mlx5 pmd是有有上诉问题？intel ice pmd 呢？

**Comment by ywc689** [comment]
> > 
> 
> 只用 一个 ipv6 lip 不会冲突吗？signature 不是基于 lip, port_base 进行 hash ？ lip相同， port_base 不同，hash值也是可能相同的吧？ 另外，一般 fnat 44， fnat 66共存的话，就需要 ipv4 fdir 和 ipv6 fdir 共存，由于 mode 是一个全局的，不可以基于 fdir rule 设置mode，比如ipv4 fdir perfect, ipv6 fdir signature。冲突的可能性更大了吧？fnat44, fnat66 共存的话，就是并发比较大，只用一个ipv6-lip, 一个 ipv4-lip 也不够.

对于 ixgbe 网卡，我们测试单个 ipv6 lip 用signature 没问题，但确实如你所说，理论上是偶hash碰撞的风险的。我们内部几乎没有线上的 fnat66 服务，所以还没太关注这个问题。

**Comment by legend050709** [comment]
> > > 
> > 
> > 
> > 只用 一个 ipv6 lip 不会冲突吗？signature 不是基于 lip, port_base 进行 hash ？ lip相同， port_base 不同，hash值也是可能相同的吧？ 另外，一般 fnat 44， fnat 66共存的话，就需要 ipv4 fdir 和 ipv6 fdir 共存，由于 mode 是一个全局的，不可以基于 fdir rule 设置mode，比如ipv4 fdir perfect, ipv6 fdir signature。冲突的可能性更大了吧？fnat44, fnat66 共存的话，就是并发比较大，只用一个ipv6-lip, 一个 ipv4-lip 也不够.
> 
> 对于 ixgbe 网卡，我们测试单个 ipv6 lip 用signature 没问题，但确实如你所说，理论上是存在哈希碰撞的风险的。我们内部几乎没有线上的 fnat66 服务，所以还没太关注这个问题。

多个 ipv6-lip 有问题吗？这边测试，多个
