### ISSUE TITLE
Question: Mapping Between NIC PCI Address And DPVS

### ISSUE THREAD

**Issue by infinitydon** [iqiyi/dpvs#815]
Hi,

Please I will like to know how NIC PCI addresses are mapped to the actual dpvs interfaces.

For example using the SNAT use-case:

I want to use **_0000:00:06.0_** for the lan side i.e. **_dpdk0_**

I want to use **_0000:00:07.0_** for the wan side i.e. **_dpdk1_**

How will this be mapped on the system?

Also is **_vfio-pci_** driver supported?

**Comment by ywc689** [comment]
Interface names in DPVS can be specified with“netif_defs/device {port_name}"  in /etc/dpvs.conf, i.e. the dpvs config file.  If you are using more than one devices in the config file, the order of device configs matters. You should keep the device config order the same as DPDK PMD found the NICs. 
For your example, DPDK may specify the 00:00:06.0  as Port 0, and 00:00:07.0 as Port 1. In this case, you should confirm that config of device dpdk0 appears before device dpdk1 in /etc/dpvs.conf.

Deep into the functions "netif_port_init" and "netif_port_init" in netif.c source file if you'd like to have further understanding of this problem.

**Comment by infinitydon** [comment]
Thanks for the explanation, clear now..
