### ISSUE TITLE
在kvm平台使用ubuntu20.04编译dpvs失败

### ISSUE THREAD

**Issue by 970603878** [iqiyi/dpvs#818]
1. dpdk-20.11已经编译安装完成
root@localhost:~/dpvs/dpdk/dpdk-stable-20.11.1# ./usertools/dpdk-devbind.py --status
Network devices using DPDK-compatible driver
============================================
0000:00:04.0 'Virtio network device 1000' drv=uio_pci_generic unused=vfio-pci
0000:00:08.0 'Virtio network device 1000' drv=uio_pci_generic unused=vfio-pci
Network devices using kernel driver
===================================
0000:00:03.0 'Virtio network device 1000' if=eth0 drv=virtio-pci unused=vfio-pci,uio_pci_generic *Active*

2. 在dpvs根目录下编译dpvs，报大量网络栈相关的错
root@localhost:~/dpvs# make
for i in src tools; do make -C $i || exit 1; done
make[1]: Entering directory '/root/dpvs/src'
  iftraf.o
cc -c -D DPVS_MAX_SOCKET=2 -D DPVS_MAX_LCORE=64 -D CONFIG_DPVS_FDIR -D CONFIG_DPVS_PDUMP -DALLOW_EXPERIMENTAL_API -include rte_config.h -march=native -I/root/dpvs/dpdk/dpdklib/include -D __DPVS__ -DDPVS_VERSION=\"1.9-0\" -DDPVS_BUILD_DATE=\"2022.04.06.14:59:03\" -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -mcmodel=medium -Wno-format-truncation -Wno-stringop-truncation -Wstringop-overflow=0 -O3 -I /root/dpvs/src//../include /root/dpvs/src/iftraf.c -o /root/dpvs/src/iftraf.o
/root/dpvs/src/iftraf.c: In function ‘iftraf_sockopt_get’:
/root/dpvs/src/iftraf.c:426:36: error: taking address of packed member of ‘struct iftraf_param’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  426 |         iftraf_addr_cpy(entry->af, &array->iftraf[off].saddr, &entry->saddr);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/dpvs/src/iftraf.c:427:36: error: taking address of packed member of ‘struct iftraf_param’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  427 |         iftraf_addr_cpy(entry->af, &array->iftraf[off].daddr, &entry->daddr);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:77: /root/dpvs/src/iftraf.o] Error 1
make[1]: Leaving directory '/root/dpvs/src'
make: *** [Makefile:33: all] Error 1

3. dpvs对操作系统版本和内核有什么要求？虚拟机部署方案是否可行？

**Comment by qq1176914912** [comment]
> 1. dpdk-20.11已经编译安装完成
>    root@localhost:~/dpvs/dpdk/dpdk-stable-20.11.1# ./usertools/dpdk-devbind.py --status
>    Network devices using DPDK-compatible driver
>    ============================================
>    0000:00:04.0 'Virtio network device 1000' drv=uio_pci_generic unused=vfio-pci
>    0000:00:08.0 'Virtio network device 1000' drv=uio_pci_generic unused=vfio-pci
>    Network devices using kernel driver
>    ===================================
>    0000:00:03.0 'Virtio network device 1000' if=eth0 drv=virtio-pci unused=vfio-pci,uio_pci_generic _Active_
> 2. 在dpvs根目录下编译dpvs，报大量网络栈相关的错
>    root@localhost:~/dpvs# make
>    for i in src tools; do make -C $i || exit 1; done
>    make[1]: Entering directory '/root/dpvs/src'
>    iftraf.o
>    cc -c -D DPVS_MAX_SOCKET=2 -D DPVS_MAX_LCORE=64 -D CONFIG_DPVS_FDIR -D CONFIG_DPVS_PDUMP -DALLOW_EXPERIMENTAL_API -include rte_config.h -march=native -I/root/dpvs/dpdk/dpdklib/include -D **DPVS** -DDPVS_VERSION="1.9-0" -DDPVS_BUILD_DATE="2022.04.06.14:59:03" -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -mcmodel=medium -Wno-format-truncation -Wno-stringop-truncation -Wstringop-overflow=0 -O3 -I /root/dpvs/src//../include /root/dpvs/src/iftraf.c -o /root/dpvs/src/iftraf.o
>    /root/dpvs/src/iftraf.c: In function ‘iftraf_sockopt_get’:
>    /root/dpvs/src/iftraf.c:426:36: error: taking address of packed member of ‘struct iftraf_param’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    426 |         iftraf_addr_cpy(entry->af, &array->iftraf[off].saddr, &entry->saddr);
>    |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
>    /root/dpvs/src/iftraf.c:427:36: error: taking address of packed member of ‘struct iftraf_param’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
>    427 |         iftraf_addr_cpy(entry->af, &array->iftraf[off].daddr, &entry->daddr);
>    |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
>    cc1: all warnings being treated as errors
>    make[1]: *** [Makefile:77: /root/dpvs/src/iftraf.o] Error 1
>    make[1]: Leaving directory '/root/dpvs/src'
>    make: *** [Makefile:33: all] Error 1
> 3. dpvs对操作系统版本和内核有什么要求？虚拟机部署方案是否可行？

大佬，我也遇到了第二个同样的问题，看意思是这个问题解决不了吗暂时，要换系统？

**Comment by qq1176914912** [comment]
> 1. 编译错误是数据对齐问题导致的，我们后续修复。
> 2. dpvs 运行在 linux 系统中，对系统和内核版本没有特殊要求。虚拟机如果支持DPDK，是可以部署运行 DPVS的，但性能和一些功能可能受限。

这个问题 目前只能尝试更换系统来解决吗

**Comment by ywc689** [comment]
#833 修复了ubuntu上的编译问题，可以尝试看看。

**Comment by qq1176914912** [comment]
> #833 修复了ubuntu上的编译问题，可以尝试看看。

之前就修复了？但是我我今天下午 5点多的时候 还是遇到了这个报错

**Comment by qq1176914912** [comment]
> #833 修复了ubuntu上的编译问题，可以尝试看看。

![image](https://user-images.githubusercontent.com/79817742/173487229-41530433-a19d-4e53-9ab2-d458dbf20464.png)
我重新弄了一下 还是存在这个问题
我的步骤如下
![image](https://user-images.githubusercontent.com/79817742/173487319-c7610fd7-704f-42f9-a58f-4fff3d32cdaa.png)
![image](https://user-images.githubusercontent.com/79817742/173487349-4ced1edf-d013-42e0-bf86-4b0868f4cf86.png)
大佬，您知道我的问题出在哪里了吗

**Comment by qq1176914912** [comment]
> #833 修复了ubuntu上的编译问题，可以尝试看看。

我想试的是 后端两个网站，然后前面是一个dpvs这个效果，是不是这个东西不适合虚拟机方案？
