### ISSUE TITLE
ipvsadm -ln 报错Memory allocation problem

### ISSUE THREAD

**Issue by arnolix** [iqiyi/dpvs#821]
dpvs 1.9.0版本，  vs条目增加到2万后，systemctl reload keepalived后  dpvs.log中一直 IFA: [00] ifa_entry_add: add ifaddr xx.xx.xx.xx  failed -- already exist ， 观察15分钟仍没停止，感觉是死循环了， 这时候访问vip + port是正常的。

**Comment by ywc689** [comment]
如果使用 keepalived 配置了 fullnat 的 local IP，这个“already exist” 的错误可以忽略，它是 vs 共用的 local ip 产生的告警日志，不影响服务。

另外，keepalived 支持 2w 个 vs 可能会有性能问题，如果只是配置vs，这种情况建议使用ipvsadm工具。

**Comment by ywc689** [comment]
ipvsadm -ln 出现 Memory allocation problem，可以 gdb 调试下，可能是 vs 太多，ipvsadm 申请不到这么大的内存。
