### ISSUE TITLE
命令启动后出现错误Cause: Cannot init mbuf pool on socket 0

### ISSUE THREAD

**Issue by john-jun** [iqiyi/dpvs#823]
[root@localhost bin]# dpvs
current thread affinity is set to 3
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Detected static linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: net_e1000_em (8086:100e) device: 0000:00:08.0 (socket 0)
EAL: No legacy callbacks, legacy socket not created
DPVS: dpvs version: 1.9-0, build on 2022.04.19.18:50:53
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
EAL: Error - exiting with code: 1
  Cause: Cannot init mbuf pool on socket 0

**Comment by TSc2end** [comment]
我部署时候也遇到了，解决方法是增大内存巨页
参考这个issue：https://github.com/iqiyi/dpvs/issues/77
