### ISSUE TITLE
msg_destroy: Assertion `0' failed.

### ISSUE THREAD

**Issue by limeix** [iqiyi/dpvs#834]
dpvs版本1.8.8

msg_destroy: Assertion `0' failed.
```
int msg_destroy(struct dpvs_msg **pmsg)
{
    struct dpvs_msg *msg;

    if (unlikely(!pmsg || !(*pmsg)))
        return EDPVS_INVAL;
    msg = *pmsg;

    if (unlikely(rte_atomic16_read(&msg->refcnt) == 0)) {
        char buf[1024];
        msg_dump(msg, buf, sizeof(buf));
        RTE_LOG(ERR, MSGMGR, "%s: bad msg refcnt at destroy:\n%s", __func__, buf);
        assert(0);
    }
    xxxxxxxx
}
```

**Comment by ywc689** [comment]
可能是内存重复释放导致的，可以看下coredump。如果不是社区发布的1.8.8版本，可以看看是不是自己改动的代码引起的。

**Comment by legend050709** [comment]
有稳定复现的方法吗？

**Comment by limeix** [comment]
> 有稳定复现的方法吗？

一般在dpvs刚启动后，加载keepalived配置时能复现，消息量大时复现率较高，看了下应该不是内存重复释放，refcnt位置的内存可能被写脏了，修改了dpvs_msg结构体，交换了refcnt和其他结构体成员的位置后，出错的位置就变了

之前根据msg dump的信息分析是flags和refcnt不对，做了如下修改后，测试cid和mode出错
![image](https://user-images.githubusercontent.com/59388564/172759469-a7f68653-069e-4b89-b709-d68af2cd115f.png)

<img width="461" alt="0BF25610-6936-4154-97D9-46135D084E82" src="https://user-images.githubusercontent.com/59388564/172759880-b71a6178-9b83-4f3b-be45-c7795468a48a.png">

**Comment by legend050709** [comment]
> 

这个问题，我们也遇到过，最开始也怀疑是重复释放。但是看代码也没发现可以重复释放的地方，也没找到稳定复现的方法。现在看你的测试，更可能是内存写脏了。

**Comment by limeix** [comment]
> > 
> 
> 这个问题，你们有进展吗。最近几天遇到了这个问题。看着就是dpvs_msg结构体偏移量为32-39， 这8个字节被破坏了。其余的成员都没有问题。

目前还没啥进展

**Comment by ywc689** [comment]
Commit 86cccb8e362619f5d6aeb11de1f4601487e6c632 fixes the problem.
