### ISSUE TITLE
使用 .sh文件构建失败了

### ISSUE THREAD

**Issue by qq1176914912** [iqiyi/dpvs#837]
我是用的是Ubuntu server 
步骤是
 1、安装这些依赖库
apt install libnuma-dev
apt-get install libpopt-dev
2、克隆dpvs
git clone https://github.com/iqiyi/dpvs.git
cd dpvs
3、然后执行 dpdk-build.sh文件 
执行过程中出现 构建失败的错误
![image](https://user-images.githubusercontent.com/79817742/173326867-c5f53196-7504-4f51-a7eb-530fc5f491f8.png)
这是怎么回事呢，要怎么解决

**Comment by qq1176914912** [comment]
找到原因了 是因为缺少meson和ninja这个，我想问问 就是 都需要安装什么，因为我在构建的过程中发现很多 警告 如图
![image](https://user-images.githubusercontent.com/79817742/173330597-7e5bdafa-0a59-4dde-a5ae-1504928070a2.png)
![image](https://user-images.githubusercontent.com/79817742/173330622-c277188d-7011-4080-a934-7be459487407.png)
我不知道这有没有影响

**Comment by ywc689** [comment]
需要安装的工具可以根据编译报错信息安装，不同系统发行版不完全一样。首页文档也给出了一部分工具依赖：
```
Build dependencies may be needed, such as pkg-config(version 0.29.2+),automake, libnl3, libnl-genl-3.0, openssl, popt and numactl. You can install the missing dependencies by using the package manager of the system, e.g., yum install popt-devel (CentOS).
Early pkg-config versions (v0.29.2 before) may cause dpvs build failure. If so, please upgrade this tool.
```

**Comment by qq1176914912** [comment]
> Build dependencies may be needed, such as pkg-config(version 0.29.2+),automake, libnl3, libnl-genl-3.0, openssl, popt and numactl. You can install the missing dependencies by using the package manager of the system, e.g., yum install popt-devel (CentOS).
> Early pkg-config versions (v0.29.2 before) may cause dpvs build failure. If so, please upgrade this tool.

好的 知道了 感谢

**Comment by ywc689** [comment]
fixed by #833
