### ISSUE TITLE
ipvsadm -lc cannot open file /proc/net/ip_vs_conn

### ISSUE THREAD

**Issue by zeably** [iqiyi/dpvs#84]
[root@dpvs bin]# ./ipvsadm -lc
cannot open file /proc/net/ip_vs_conn

**Comment by mscbg** [comment]
dpvs don't support show conn yet. We will support this function later.

**Comment by ywc689** [comment]
fixed at commit 545ec7e9c6135d217bc42cb8f484ab6669b123c8
