### ISSUE TITLE
kernel: igb_uio: loading out-of-tree module taints kernel.

### ISSUE THREAD

**Issue by marchlhw** [iqiyi/dpvs#853]
安装1.7.x和1.8.x版本的dpvs，系统日志中抛如下错误
 kernel: igb_uio: loading out-of-tree module taints kernel.
 kernel: igb_uio: module verification failed: signature and/or required key missing - tainting kernel

**Comment by marchlhw** [comment]
# uname -r
3.10.0-327.el7.x86_64

# rpm -qa | grep kernel
kernel-devel-3.10.0-327.el7.x86_64
kernel-tools-libs-3.10.0-327.el7.x86_64
kernel-tools-3.10.0-327.el7.x86_64
kernel-3.10.0-327.el7.x86_64
kernel-headers-3.10.0-327.el7.x86_64

**Comment by ywc689** [comment]
igb_uio 内核模块安装请参考相关 [dpdk 文档](https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html)，该问题与 dpvs 没有关系。可以尝试最新版本的 igb_uio 或者其它 uio 驱动。
