### ISSUE TITLE
User/Admin guide to install and configure

### ISSUE THREAD

**Issue by lukedevon** [iqiyi/dpvs#859]
Hi, 

I am trying to deploy dpvs as a load balancer for two web servers in RHEL 8. However the installation guide is not that clear for me. Could you please share a user guide/admin guide, including the configuration guide  just to start the implementation?

Thanks in advance
Luke

**Comment by ywc689** [comment]
The [Quick Start](https://github.com/iqiyi/dpvs#quick-start) shows the steps to use DPVS starting from scratch. [Tutorial Document](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md) lists some more use cases for DPVS.  We run the examples on Centos7,  and some changes may be needed on RHEL 8.

**Comment by lukedevon** [comment]
Thanks for the reply. I will give a try in RHEL 8 and update you.
