### ISSUE TITLE
Tunneled health-checks support 

### ISSUE THREAD

**Issue by Slepwin** [iqiyi/dpvs#870]
Hi,

I'm going to test DPVS in Tunnel mode (one-arm) with BGP daemon like bird2, but i need to clarify a few questions:
1. Modified Keepalived for TUN VIPs send health checks via IPIP tunnels? To preserve the same network path as data (VIP) traffic.
2. Modified Keepalived does support quorum_up/down configuration knob? Or how i can advertise/withdraw VIP /32 announce?

**Comment by ywc689** [comment]
1. Keepalived health check via IPIP tunnels is not supported. 
2. Keeapived  supports quorum_up/down configurations. You can advertise/withdraw /32 vip routes via [DPVS KNI devices](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#kni). Some examples in [the tutorial doc](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md) may be helpful.

**Comment by Slepwin** [comment]
> 1. Keepalived health check via IPIP tunnels is not supported.
> 2. Keeapived  supports quorum_up/down configurations. You can advertise/withdraw /32 vip routes via [DPVS KNI devices](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#kni). Some examples in [the tutorial doc](https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md) may be helpful.

Could you please add tunneled health checks as feature request.

**Comment by ywc689** [comment]
We considered the feature, but its implementation would not straightforward for health checks are managed by Keepalived and IPIP encapsulations is done in DPVS.
Actually, health checking does work by establishing connections between DPVS KNI IP and Real Servers. Most failures about Real Server could be detected in this way despite that the health checking data is not encapsulated with IPIP.

**Comment by Slepwin** [comment]
> We considered the feature, but its implementation would not straightforward for health checks are managed by Keepalived and IPIP encapsulations is done in DPVS. Actually, health checking does work by establishing connections between DPVS KNI IP and Real Servers. Most failures about Real Server could be detected in this way despite that the health checking data is not encapsulated with IPIP.

Without dst vip in inner header we can't check the real server configured properly (dummy/loopback is configured or not)
You can use https://github.com/andriyanov/check-tun as baseline.

**Comment by ywc689** [comment]
The `check-tun` runs in user-space, no changes was required in kernel/lvs. I think it would also work for DPVS. You could have a try.
