### ISSUE TITLE
ipvsadm设置conhash因子报错hash target not support

### ISSUE THREAD

**Issue by jiemiancom** [iqiyi/dpvs#877]
#DPVS版本： dpvs-1.8.10
#ipvsadm版本：
  ipvsadm  --version
  ipvsadm v1.27 2008/5/15 (compiled with popt and IPVS v1.8.8)
#keepalived版本：
  keepalived --version
  Keepalived v2.0.19 (unknown)
  Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>
  Built with kernel headers for Linux 3.10.0
  Running on Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
  configure options: 
  Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
  System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

通过keepalive 只能设置默认conhash sip

通过ipvsadm设置conhash报错
ipvsadm -A -u xxx.xxx.xxx.xxx.:443 -s conhash -Y qid
hash target not support

怎么才能指定conhash使用的qid呢(我从ipvsadm -h上看是可以支持的)？

**Comment by ywc689** [comment]
请先用 --hash-target 试试
ipvsadm -Au XXX  -s conhash --hash-target qid
