### ISSUE TITLE
dpvs 支持 通过 vlan实现 租户隔离吗？

### ISSUE THREAD

**Issue by wlooppy** [iqiyi/dpvs#882]
场景需求 多租户场景可能会有 不同租户 使用相同 lip 和 rs ip的情况，请问能否使用 vlan 隔离租户流量：
租户一 ：
vip 是 10.233.0.10 ：8000
lip 是 12.100.100.11
rs 是 12.100.100.9：80
单臂组网 vip 在 dpdk0 上
lip 在 dpdk0.1000(dpdk0 vlan 1000 子接口)

租户二 ：
vip 是 10.233.0.11 ：8000
lip 是 12.100.100.11
rs 是 12.100.100.9：80
单臂组网 vip 在 dpdk0 上
lip 在 dpdk0.2000(dpdk0 vlan 2000 子接口)

谢谢

**Comment by ywc689** [comment]
dpvs 现在只有一张路由表，不支持你的这种场景

**Comment by wlooppy** [comment]
明白，谢谢回复，看了代码，手动修改了下，通过 fnat 规则指定出接口，不走路由表，目前看着功能是可以实现了，性能有没有损耗 待测试中
