### ISSUE TITLE
vip的配置如何持久化到dpvs的conf中

### ISSUE THREAD

**Issue by jianweixs** [iqiyi/dpvs#883]
不用通过ipvsadm管理，vip的配置如何持久化到dpvs的conf中，除了keepalived，还有什么好的方案吗？

**Comment by ywc689** [comment]
dpvs 配置文件只用于 dpvs 自身相关配置，不用于业务配置。不用keepalived，业务配置持久化可以自己实现，dpvs 暂不计划支持其他方式。
