### ISSUE TITLE
Should we just new 1 session in icmp for continuous ping? Thanks.

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#89]
In SNAT mode:
Client：ping server -f
Server：
./ipvsadm -ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
MATCH icmp,from=xxx-xxx:0-0,oif=dpdk1 rr
  -> xxxx:0               SNAT    100    0          295577

May be we can just new 1 session for a continuous ping from one internal IP address. Thanks a lot.

**Comment by beacer** [comment]
ICMP use `<proto, saddr, daddr, type-code, echo-id>` for "connection" lookup, if ID is same there should not so many connections. Is every time ID is changed ? and the timeout for ICMP is 300s.
You can use `tcpdump -vv ... ` to check ICMP ID.

**Comment by icymoon** [comment]
This issue can be closed since it was fixed last week ：）
