### ISSUE TITLE
KNI is deprecated in DPDK 23.11 release.

### ISSUE THREAD

**Issue by jihwanseo** [iqiyi/dpvs#892]
According to below dpdk link, KNI is deprecated and will be removed in future. (maybe DPDK 23.11 release)
https://doc.dpdk.org/guides/prog_guide/kernel_nic_interface.html

Do you have a plan to support alternative way like virtio_user or tun/tap ?

**Comment by ywc689** [comment]
Not yet. Possibly DPVS will support one of kni alternatives in feature releases such as v1.10 when it uses a more recent DPDK release. But we have no definite plans for the work now.
