### ISSUE TITLE
support vxlan in rs side

### ISSUE THREAD

**Issue by mingoooo** [iqiyi/dpvs#893]
hi, just want to know about the vxlan feature. I'm found the feature in todo list already
do we have a plan to support that? or there have another solution to support overlay network?

**Comment by ywc689** [comment]
The vxlan feature  is in DPVS's feature plan, but we may not support it recently. Currently we don't have the use case for overlay network. If you're interested in it, you may contribute to the feature.

**Comment by mingoooo** [comment]
> The vxlan feature is in DPVS's feature plan, but we may not support it recently. Currently we don't have the use case for overlay network. If you're interested in it, you may contribute to the feature.

@ywc689  thanks your replay, I'll try to do that.
please point me if there have any suggestions.
