### ISSUE TITLE
UOA: Support IPv6 by Destination Extension Header Option (PR request)

### ISSUE THREAD

**Issue by vksir** [iqiyi/dpvs#894]
**Problem**
Currently, the UOA only support IPv6 on ipo mode, which is using private protocol. If the UOA kmod is not installed on the RS, UDP pkt would not be recognized.

**Solve**
So, why not insert the CIP info as IPv6 Destination Extension Header Option into the pkt, just like ipopt mode. In this way, pkt can be recognized regardless of whether the UOA kmod is installed on the RS.
I hava verified that it is works.

I'd like to ask could you accept this Solution?
If you accept, I'd be happy to submit code to implement this solution.

**Comment by ywc689** [comment]
Sounds great!  UOA IPO mode for IPv6 FullNat is a missing feature now. If you'd like to contribute, please ensure its a new feature, rather than a replacement of current supported UOA opp mode.
