### ISSUE TITLE
dpdk20.11.1是否支持LACP聚合子接口的工作模式？

### ISSUE THREAD

**Issue by Lee786213** [iqiyi/dpvs#895]
服务器网卡：
Mellanox Technologies MT27500 Family [ConnectX-3]
DPDK 能否把两端口 40G做LACP，并配置VLAN子接口去跑业务。
如果这么做，会影响哪些功能？

**Comment by fishyu-mushroom** [comment]
你好，请问MT27500   两端口 40G做LACP 做bond是否成功？应该怎么配置dpvs。
