### ISSUE TITLE
官方文档

### ISSUE THREAD

**Issue by gaoming1227** [iqiyi/dpvs#90]
爱奇艺是中国的公司么？为什么没有中文文档。回答也是英文。难道这样才显得有档次？

**Comment by gaoming1227** [comment]
如果提问是中文的，不能用中文回答么

**Comment by lvsgate** [comment]
腾讯的f-stack也是一样，冲出亚洲，走向世界

2018-01-09 11:44 GMT+08:00 gaoming1227 <notifications@github.com>:
