### ISSUE TITLE
DPVS双主模式 OSPF/ECMP  模拟其中一台宕机后有5s左右的收敛时间切换，有实现无痕切换的方式么？

### ISSUE THREAD

**Issue by vslinux** [iqiyi/dpvs#900]
一台宕机过程中有%3左右的请求超时失败，如何能做到无感知自动切换，目前为双主两台使用相同的VIP，模式为双臂FullNAT+OSPF/ECMP架构.

**Comment by ywc689** [comment]
建议优化路由的收敛时间或者使用BFD加快故障节点的发现和隔离。DPVS还不支持连接同步，故障节点的连接需要重连。
