### ISSUE TITLE
dpvs支持最高的linux内核版本是多少呢？

### ISSUE THREAD

**Issue by lox139** [iqiyi/dpvs#904]
用5.4编译安装会报错，文档推荐3.10，网上的帖子有说4.4编译通过的，官方除了3.10还有更高的兼容内核版本么？

**Comment by ywc689** [comment]
DPVS 是用户态程序，与内核版本没有强制依赖。除了toa和 uoa 内核模块以及一些特定的网卡驱动，DPVS可以在任何版本的内核上编译和执行。
