### ISSUE TITLE
启动dpvs时报错

### ISSUE THREAD

**Issue by lox139** [iqiyi/dpvs#907]
NETIF: Ethdev port_id=0 invalid rss_hf: 0x3afbc, valid value: 0x7ef8 ，这个rss_hf需要在哪里设置呢？
![image](https://github.com/iqiyi/dpvs/assets/60485031/0081aa35-2913-46c3-8956-618008cc4437)
我是按照 https://github.com/iqiyi/dpvs/blob/master/doc/tutorial.md#nat-mode-one-arm  这个模式配置的

**Comment by ywc689** [comment]
这条日志是网卡不支持DPVS默认配置的RSS方式导致的，有时可能会使各个worker的负载不均衡，一般情况下不影响正常使用。
