### ISSUE TITLE
是否支持ICMP协议，以及是否支持任意端口转发

### ISSUE THREAD

**Issue by zqabc** [iqiyi/dpvs#943]
两个问题：
1、是否支持配置ICMP协议的转发？
2、是否支持配置任意端口转发？

我发现ipvsadm --help里都有对应的描述
<img width="717" alt="image" src="https://github.com/iqiyi/dpvs/assets/5118695/54f3fe0a-a7da-439e-92d1-73476d4e3217">

如果不支持的话，是否在roadmap里？

谢谢！

**Comment by ywc689** [comment]
这两项功能目前还不支持，短期内暂无计划

**Comment by zqabc** [comment]
收到
