### ISSUE TITLE
Can't get session status in SNAT mode with ipvsadm, thanks.

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#95]
\# ./ipvsadm  -ln
IP Virtual Server version 0.0.0 (size=0)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
MATCH icmp,from=172.16.0.0-172.16.255.254:0-0,oif=dpdk1 rr
  -> 192.168.10.2:0               SNAT    100    0          0
  -> 192.168.10.4:0               SNAT    100    0          0
  -> 192.168.10.5:0               SNAT    100    0          0
  -> 192.168.10.6:0               SNAT    100    0          0
MATCH tcp,from=172.16.0.0-172.16.255.254:0-0,oif=dpdk1 rr
  -> 192.168.10.2:0               SNAT    100    0          0
  -> 192.168.10.4:0               SNAT    100    0          0
  -> 192.168.10.5:0               SNAT    100    0          0
  -> 192.168.10.6:0               SNAT    100    0          0
MATCH udp,from=172.16.0.0-172.16.255.254:0-0,oif=dpdk1 rr
  -> 192.168.10.2:0               SNAT    100    0          0
  -> 192.168.10.4:0               SNAT    100    0          0
  -> 192.168.10.5:0               SNAT    100    0          0
  -> 192.168.10.6:0               SNAT    100    0          0

\# ./ipvsadm  -ln -c
[sockopt_msg_recv] errcode set in socket msg#900 header: msg dropped(-24)
ip_vs_get_conns: got errcode -24 from dpvs_getsockopt

**Comment by ywc689** [comment]
@icymoon The inter-lcore msg timed out when you get session entries of dpvs. Please increase the msg timeout `ctrl_defs/sync_msg_timeout_us` configured in /etc/dpvs.conf, and then try ` ./ipvsadm -ln -c` again.

**Comment by ywc689** [comment]
`./ipvsadm -ln -c` only supports tcp/udp protocol now.  Icmp may not be displayed properly. I will fix it later.

**Comment by icymoon** [comment]
Thank you very much, @ywc689  :-)

**Comment by ywc689** [comment]
fixed at commit d23fa8ebbaa82b856682ce519d4af7c8bcae6b61
