### ISSUE TITLE
dpvs 初始化 CONFIG_DPVS_MAX_LCORE最大为64

### ISSUE THREAD

**Issue by fishyu-mushroom** [iqiyi/dpvs#955]
使用物理机是256核数的机器时，初始化报错。
发现是CONFIG_DPVS_MAX_LCORE最大限制了64。修改代码的变量值为256，dpvs服务可以启动。

请问这个64有什么特别的意义吗？

**Comment by ywc689** [comment]
DPVS 的消息模块最大支持64核。实际上，对于万兆或者25G网卡的机器，8个核基本上就够了。具体可以参考DPVS性能测试文档。

**Comment by fishyu-mushroom** [comment]
我们测试过了8核是最佳的状态。
我司新采购机器是256核心25G网卡的机器，所以只能在256核心的机器上跑。

DPVS 的消息模块最大支持64核，这个消息模块是不是就是对应 MSG_MAX_LCORE_SUPPORTED？ 如何把这个值也改大，是不是就不会其他限制。

**Comment by fishyu-mushroom** [comment]
在配置文件中我们仅定义了 8个cpu核心，但是为了在256的机器上启动服务，我们在编译前改了这些宏变量值。
修改了CONFIG_DPVS_MAX_LCORE   MSG_MAX_LCORE_SUPPORTED 改到与物理机核心一致256，然后可以正常跑DPVS，但是没有在线上测试过。所以想额外咨询下，这个参数调整了是不是就不会有影响？还是会对DPVS某个模块产生影响，无法支持。

**Comment by ywc689** [comment]
DPVS 的 EAL 启动参数可以解决这个问题。
比如
```sh
./dpvs ... -- -l 1-9 ...
```
具体可以参考help信息
```sh
./dpvs -- --help
```

**Comment by fishyu-mushroom** [comment]
👌好的
