### ISSUE TITLE
synproxy

### ISSUE THREAD

**Issue by Denyme** [iqiyi/dpvs#956]
Hi.
How i can disable syn proxy?

**Comment by ywc689** [comment]
synproxy is disabled by default. You must enable it explicitly with `ipvsadm` or `keepalived`.

```
# ipvsadm -h| grep synproxy  
  --synproxy     -j                   TCP syn proxy
```

**Comment by Denyme** [comment]
in log i have dp_vs_synproxy_ack_rcv: syncookie check failed.
dpvs version 1.9-6

**Comment by ywc689** [comment]
Actually, the problem is not in synproxy. The log implies some tcp ack packets target at a virtual service but its related syn packet didn't received by DPVS.You should look into the problem and find out where the packets come from.
