### ISSUE TITLE
请问大佬如何运行dpvs里面的test内容？

### ISSUE THREAD

**Issue by pengliangyou** [iqiyi/dpvs#960]
makefile没有make test，请问如何运行test呢？test文件夹下的测试如何运行呢？有示例吗？

**Comment by ywc689** [comment]
test 目录目前仅用于存放测试用的代码和脚本，不包含编译和运行依赖的环境。

**Comment by pengliangyou** [comment]
感谢 明白了

wencyu ***@***.***> 於 2024年6月19日 週三 下午5:46寫道：
