### ISSUE TITLE
fullnat模式下，启动后kni配置的ip丢失

### ISSUE THREAD

**Issue by mztmyf** [iqiyi/dpvs#983]
![image](https://github.com/user-attachments/assets/bc8e28ed-3b32-4495-b5ba-a348cb540778)
启动后，配置ip成功，过段时间后看，配置的ip没了：
![image](https://github.com/user-attachments/assets/297cf19e-cdb6-4154-b2f8-406060105af7)

dpvs日志显示：
![image](https://github.com/user-attachments/assets/d66312a6-2765-4130-8307-7420487f388c)

update maddr of dpdk0 OK! 
这个更新地址是什么行为引起呢？
配置文件：
`
    <init> device dpdk0 {
        rx {
            queue_number        16
            descriptor_number   1024
            rss                 all
        }
        tx {
            queue_number        16
            descriptor_number   1024
        }
        mtu                   1500
        allmulticast          disable
        ! promisc_mode
        kni_name                dpdk0.kni
    }

    <init> device dpdk1 {
        rx {
            queue_number        16
            descriptor_number   1024
            rss                 all
        }
        tx {
            queue_number        16
            descriptor_number   1024
        }
        mtu                   1500
        allmulticast          disable
        ! promisc_mode
        ! allmulticast
        kni_name                dpdk1.kni
    }`

大概几分钟后再次配置ip就不会丢失了。

**Comment by ywc689** [comment]
和上面日志没关系，可以看看是不是 NetworkManager 摘除的 IP。

**Comment by mztmyf** [comment]
已经解决，需要先配置ip然后 拉起网卡即可
