### ISSUE TITLE
ipvsadm报错

### ISSUE THREAD

**Issue by bjwxy** [iqiyi/dpvs#984]
ipvsadm -Ln命令会报错：[sockopt_msg_recv] errcode set in socket msg#19 header: msg callback failed(-23)
查看dpvs日志：
MSGMGR: multicast_msg_send:msg@0x16b54034c, mcq(type:112, cid:0->slaves) timeout(20000 us), drop...
SERVICE: dp_vs_service_get: send message fail
MSGMGR: [sockopt_msg_send:msg#DPVS_SO_GET_SERVICES] errcode set in sockopt msg reply: msg callback failed
MSGMGR: msg_master_process:msg@0x1780ae50c, multicast reply msg <type:112, seq:0> from lcore 1 missed
MSGMGR: msg_master_process:msg@0x1780ae50c, multicast reply msg <type:112, seq:0> from lcore 7 missed
MSGMGR: msg_master_process:msg@0x1780ae50c, multicast reply msg <type:112, seq:0> from lcore 3 missed
MSGMGR: msg_master_process:msg@0x1780ae50c, multicast reply msg <type:112, seq:0> from lcore 4 missed

每次执行ipvsadm，lcore n missed不一致，有时候1，2，3，4，5，6，7，8，有时候1，2，3，有时候4，5，6，随机出现missed

**Comment by ywc689** [comment]
可能是某个CPU太慢或者卡住了，检查下worker的配置，尝试逐个命令配置，找出是哪一条命令开始出现的问题。

**Comment by bjwxy** [comment]
> 可能是某个CPU太慢或者卡住了，检查下worker的配置，尝试逐个命令配置，找出是哪一条命令开始出现的问题。

感谢大佬的答复，最终定位到因为某个进程周期性的跑满cpu导致。
