### ISSUE TITLE
执行ipvsadm --start-daemon时报错

### ISSUE THREAD

**Issue by lsq647** [iqiyi/dpvs#999]
背景：
    希望通过ipvsadm来实现dpvs集群间的连接同步。

执行指令：
`./ipvsadm --start-daemon master --mcast-interface dpdk0.kni`
出现`Bad file descriptor`报错，log中看不到其他的日志。

![image](https://github.com/user-attachments/assets/c00d8ad3-47b8-4406-8222-afcd08db40c7)

请问下各位大佬，这种问题应该如何排查？

**Comment by lsq647** [comment]
感谢回复😀 
后续是否有计划支持一下？或者是因为有某些顾虑而没有支持？

**Comment by ywc689** [comment]
fullnat的连接同步实现比较复杂，而且会有性能问题，参考 #476 ，目前暂时还没有好的方案支持这一功能。
